### ISSUE TITLE
cmake JPEG 2000 support

### ISSUE THREAD

**Issue by neurolabusc** [rordenlab/dcm2niix#105]
As first reported by [Jack](https://www.nitrc.org/forum/forum.php?thread_id=8140&forum_id=4703), versions of dcm2niix built cmake using `DUSE_OPENJPEG=ON ..` claim to support JPEG2000, but actually fail to convert this format. At the moment the alternative is to directly compile the software as described in the COMPILE.md file. @ningfei is aware of this issue, and is probably best placed to fix this issue. However, if anyone else has a good solution please suggest a fix.

**Comment by ningfei** [comment]
Fixed in 0102f8b.

**Comment by ChunBoo** [comment]
@ningfei ,I have tried this latest code with one Dicom file,but it failed without any hint，could you please  help to verify if  this issue is related with my file?

BTW, I have tried the version of 29Feb2016 (64-bit),it reported one error:spatial orientation ambiguous(tag 0020,0037 not found),pls see below screenshot:
![image](https://user-images.githubusercontent.com/21964607/27274545-5972d4de-5506-11e7-93aa-3d2cd3f418e2.png)


Thanks,
Chunboo

**Comment by ningfei** [comment]
Hi Chunboo, so they are jpeg dicom files, right? Could you send me the files? So I can have a look here.
