### ISSUE TITLE
fMRI and MRI one series to double nii.gz files

### ISSUE THREAD

**Issue by qinqian** [rordenlab/dcm2niix#119]
Dear Authors,

Thanks for creating such a nice tool. I have some issues when converting fMRI (GE) and MRI (Siemens) dicom data. I used the command, 

`dcm2niix -m y -i n -z y -f %i_%p -o output input_folder_root`

for both of the vendors, for 3-Pl_T2_FGRE series of fMRI and localizer of MRI, I've got two nii.gz files,

fMRI example, there should be 9 DICOM files under the Pl_T2_FGRE series,
id-Pl_T2_FGRE_Eq_1.nii.gz 256, 256, 18
id-Pl_T2_FGRE.nii.gz 256, 256, 9

MRI example, there should be 9 DICOM files under the localizer series,
id_localizer_Eq_1.nii.gz dimension 512, 512, 18
id_localizer.nii.gz  dimension 512, 512, 9

In my understanding, each series will be merged into one 3D (structure) or 4D (function) nii.gz files, what is the reason for generating two files for the above series? Since only one of them seems to have the correct dimension, Is there a way to merge the two files? Or is that right to choose the one without *Eq_1*? By default '-m n', the files would be even more than this, such as *a, *b, what would be the option if we want one nii.gz for one category of series? What is the routine command options for -m and -i would you suggest?

Thanks,
Best,
Qian

**Comment by neurolabusc** [comment]
You should look at the output of the software, it will explain why it was forced to do this. The "Eq" files are only generated when the slices are not equidistant. The NIfTI standard requires all slices in a volume to by equidistant, e.g. for an fMRI scan with 3mm thick slices and a 20% gap, the slice distance is 3.6mm. This is not required by DICOM, for example it is common for CT scans to have more slices near the brain stem and fewer near the top of the head. When my software encounters these volumes it must interpolate in order to create a valid NIfTI file. This is very uncommon for MRI sequences, as changing slice thickness changes SNR and changing slice gap changes interference. Therefore, I think you need to go back to your scanner and make sure all the T2 scans transferred. You generally discard the localizer, so I would not worry about that.

**Comment by neurolabusc** [comment]
@qinqian did you resolve your issue - this behavior is described in the manual
https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Special_Considerations_for_Computed_Tomography_.28CT.2C_CAT.29
