### ISSUE TITLE
No dependencies?

### ISSUE THREAD

**Issue by TheChymera** [rordenlab/dcm2niix#120]
Hi, [as discussed earlier](https://github.com/neurolabusc/dcm_qa/issues/5#issuecomment-317436428), I am trying to package your software.

I haven't found any dependency list in here. Could you provide one if there is one?

**Comment by neurolabusc** [comment]
The basic compile has no dependencies and this is what you get if you type `make` in the `console` folder. For a default installation it might be useful to also ensure the user has pigz installed to provide faster gz compression. 

However, if you want to support (very rare) JPEG2000 images, you will require the OpenJPEG library. This is what you get if run the following from the parent folder:
```
 mkdir build && cd build
cmake -DUSE_OPENJPEG=ON ..
make
```
The [COMPILE.md](https://github.com/rordenlab/dcm2niix/blob/master/COMPILE.md) describes alternate compiles with different dependencies. For example, you may choose to require zlib instead of the default miniz as your internal gz compressor. In practice, for any computer with pigz installed the internal serial compressor is only used if the user explicitly requests it compressor.
