### ISSUE TITLE
single file conversion

### ISSUE THREAD

**Issue by xfgavin** [rordenlab/dcm2niix#121]
How does single file work?
I tried using the -s y option but it still converted all dicoms.

Here is the log
ls
1.2.840.113619.2.374.15512023.5825816.15773.1484445179.999  1.2.840.113619.2.374.15512023.5825816.15773.1484445180.190

dcm2niix -v -s y -z n -f b ./1.2.840.113619.2.374.15512023.5825816.15773.1484445179.999
Compression will be faster with /usr/local/bin/pigz
Chris Rorden's dcm2niiX version v1.0.20170624 (OpenJPEG build) GCC4.8.4 (64-bit Linux)
Found 2 DICOM image(s)
./1.2.840.113619.2.374.15512023.5825816.15773.1484445179.999
 patient position	-159.688	-45	159.688
 acq 1 img 33 ser 1 dim 512x512x1 mm 0.625x0.625x10 offset 14148 dyn 0 loc 36 valid 1 ph 0 mag 0 posReps 0 nDTI 1 3d 0 bits 16 littleEndian 1 echo 1 coil 1 TE 52.624 TR 781.18
./1.2.840.113619.2.374.15512023.5825816.15773.1484445180.190
 patient position	46.6245	-156.25	150.001
 acq 1 img 56 ser 2 dim 256x256x1 mm 1x1x1 offset 14788 dyn 0 loc 208 valid 1 ph 0 mag 0 posReps 0 nDTI 1 3d 1 bits 16 littleEndian 1 echo 1 coil 1 TE 2.92 TR 6.952
Converting ./1.2.840.113619.2.374.15512023.5825816.15773.1484445179.999
Convert 1 DICOM as ./b (512x512x1x1)
Warning: Check that 2D images are not mirrored.
Converting ./1.2.840.113619.2.374.15512023.5825816.15773.1484445180.190
Convert 1 DICOM as ./ba (256x256x1x1)
Warning: Check that 2D images are not mirrored.
Conversion required 0.106976 seconds (0.005265 for core code).

ls
1.2.840.113619.2.374.15512023.5825816.15773.1484445179.999  1.2.840.113619.2.374.15512023.5825816.15773.1484445180.190  b.json  b.nii  ba.json  ba.nii

**Comment by neurolabusc** [comment]
The single file conversion works as expected, you just need to provide level for the 'verbosity', so instead of `dcm2niix -v -s y -z n -f b ./1...` you should write `dcm2niix -v y -s y -z n -f b ./1...` The options for vebosity are **silent** `-v 0` or `-v n` **verbose** `-v 1` or `-v y` or **logorrheic** `-v 2`. To see the options for the software run either `dcm2niix -h y` or simply `dcm2niix` from the command line. This will provide examples for each argument. For example, I tend to include the protocol name and the series number in the file name (`-f %p_%s`).
