### ISSUE TITLE
Unable to convert large numbers of DICOM images

### ISSUE THREAD

**Issue by gbook** [rordenlab/dcm2niix#123]
I recently updated to dcm2niix, but having trouble converting any fMRI series with more than 1000 or so volumes. In the example below, there are only 2162 DICOM files in the directory, and the error repeats until I kill the program.

```
/nidb/programs/./dcm2niix -1 -g y -m y -o '/ado2/data/tmp/irXSbSgY3S' *.dcm

Compression will be faster with /usr/local/bin/pigz
Chris Rorden's dcm2niiX version v1.0.20170528 GCC4.4.7 (64-bit Linux)
Found 2162 DICOM image(s)
slices stacked despite varying acquisition numbers (if this is not desired please recompile)
Error: Too many NIFTI images with the name /ado2/data/tmp/irXSbSgY3S/dicom_BOLD_AP_BIC_Driving_20170809110031_5
Found 2162 DICOM image(s)
slices stacked despite varying acquisition numbers (if this is not desired please recompile)
Error: Too many NIFTI images with the name /ado2/data/tmp/irXSbSgY3S/dicom_BOLD_AP_BIC_Driving_20170809110031_5
```

**Comment by neurolabusc** [comment]
Greg-
  Thanks for the example images. 

1. One minor issue is that you should change `-g y` to read `-z y`. This parameter changed between dcm2nii and dcm2niix. I have updated the code to warn the user when they provide an unknown argument, so hopefully your bug report will help future users avoid this mistake. 

2. I would heed the warning is **Compression will be faster with /usr/local/bin/pigz**. Your sample image is 3.5Gb and the maximum size for a GZip file is 4Gb. If my software can not find pigz, it falls back to the internal single threaded compressor which does everything in RAM. I have updated the code to provide more explicit warnings. Personally, I do not gzip fmri data until after scalp stripping, as due to poor SNR there is not a lot of redundancy in EPI data. In your example `./dcm2niix -1 -z y -m y -o "/Users/rorden/tst" ~/book` (and with pigz in the path) required 190s on my dual core laptop (compressing the image to 2.67Gb). On the other hand `./dcm2niix -z n -m y -o "/Users/rorden/tst" ~/book` required just 27s (and my older dcm2nii requires 98s). So the compression is really the rate limiting step.

3. I am not able to replicate your error regarding the repeating error. The sample you sent me included only a single session and it converted nicely. Is it possible that there is a symbolic link or subdirectories with images in your input folder? Be aware that some scanners save a single series of DICOM data to multiple folders, so my software looks not only in the parent folder but also the child folders. Therefore if your current working directory includes other folders beyond those with the DICOM images, it will take a long time to recursively work through them. 

Please tell me if these suggestions fix your problem and I will close this issue. Since I can not replicate your problem, it is hard to troubleshoot.

**Comment by neurolabusc** [comment]
Greg-
I can see your error. The dcm2niix convention is `dcm2niix [options] <in_folder>`, so a minimum call would be `dcm2niix ~/mydir` and the software will convert all the files it finds in the in_folder (and children folders). In your example you are calling the program 2162 times - once for each file that ends with the .dcm extension! The expansion of *.dcm is done by the shell not by the software, and your shell allows more expansion than mine (my shell generates the error `-bash: ./dcm2niix: Argument list too long`). 

I have updated my code to only convert one folder per call, and it will generate the warning `Warning: only processing last of n input files (recompile with 'myEnableMultipleInputs' to recursively process multiple files)` if a user attempts to convert multiple folders at once. One can restore the old behavior (where specifying multiple folders sequentially converts each) using the myEnableMultipleInputs compiler directive. Since the expansion is done by the shell and not the software, this seems like the only way to avoid this behavior. 

@satra, can you tell me if new behavior causes any problems for nipype or heudiconv? Specifically, in dcm2nii.py what happens if the user specifies multiple values for "source_names"? If it only uses one source name or if it calls dcm2niix once per source name there will be no problems. On the other hand, if dcm2niix is called once with multiple source names, this change will break nipype.
