### ISSUE TITLE
Customize nifti description bit?

### ISSUE THREAD

**Issue by xfgavin** [rordenlab/dcm2niix#128]
Hi Chris,

It would be great if  dcm2niix allows a customized text to write to the description bit of converted nifti file. Is that possible?

Thanks.

**Comment by neurolabusc** [comment]
Please try out the latest source code which includes the comment option (-c). This will be stored in the NIfTI `aux_file` field. If the user does not supply a comment, this field is filled with the DICOM image comments (0020,4000) tag (if provided). Unfortunately, the NIfTI header will only store one or the other (the alternative would be to store the user comment in the NIfTI `db_name` field, but fslhd does not display this field). The comment can be up to 24 characters. The BIDS header will store both the DICOM image comments ("ImageComments") and the comments provided by the user during dcm2niix conversion ("ConversionComments"). You can view the comments using MRIcron (Window/Information menu) or fslhd, for example:
 
```
>dcm2niix -c "my test" ~/tst/T1
>fslhd _tfl3d1_ns_2
filename       _tfl3d1_ns_2.nii
sizeof_hdr     348
 ...
 file_code      1
descrip        TE=2.7;Time=134808.242;phase=1
aux_file       my test
```

@yarikoptic - using this parameter might be a simple way for tools like heudiconv to store their version during image conversion.

**Comment by yarikoptic** [comment]
storing version info is a great idea BUT
@neurolabusc hm... isn't `aux_file` is for pointing to some file?
```c
 char  descrip[80];   /*!< any text you like.    */  /* char descrip[80];    */
 char  aux_file[24];  /*!< auxiliary filename.   */  /* char aux_file[24];   */
```
so it is quite a short/crippled field... ideally we should store the version of heudiconv, checksum of heuristic file (since might be exterior to heudiconv), and then version(s) of dcm2niix etc... I wondered if we might better formalize some nifti extension format to e.g. store a json with versioning etc information in it?  meanwhile, we might better off storing versioning info in the sidecar .json I guess

**Comment by neurolabusc** [comment]
Technically you are correct that the `aux_file` is vaguely referred to in the NIfTI spec as being able to point to a filename (such as color scheme), but both my software and other converters (e.g. dicm2nii) have been using this field for years to store extra text data, so I know of no incompatibilities. We already use the descrip (80 characters) for useful image parameters, so we are left with aux_file (24), data_type (10, unused in NIfTI) and db_name (18, unused in NIfTI) if we want to store any extra text. The latter two are unused, so we could always store text here, but the popular fslhd does not display the contents of these fields (presumably because they are unused). Also, these two fields were [removed from NIfTI2](https://brainder.org/2015/04/03/the-nifti-2-file-format/).
