### ISSUE TITLE
string content is not escaped appropriately in json output

### ISSUE THREAD

**Issue by satra** [rordenlab/dcm2niix#131]
on a sequence i was testing the json bids output returns:

```
{
	"PulseSequenceDetails": "%CustomerSeq%\ep2d_diff_MGH"
}
```

however, the `\` should be escaped `\\`

```
{
	"PulseSequenceDetails": "%CustomerSeq%\\ep2d_diff_MGH"
}
```

more generally the json should be validated before writing.

**Comment by satra** [comment]
here is a bit of playing with this in python:

```
In [31]: a = { "PulseSequenceDetails": "%CustomerSeq%\ep2d_diff_MGH"}

In [32]: a
Out[32]: {'PulseSequenceDetails': '%CustomerSeq%\\ep2d_diff_MGH'}

In [33]: print(json.loads(json.dumps(a)))
{'PulseSequenceDetails': '%CustomerSeq%\\ep2d_diff_MGH'}

In [34]: print(json.loads(json.dumps(a))['PulseSequenceDetails'])
%CustomerSeq%\ep2d_diff_MGH
```

**Comment by neurolabusc** [comment]
This was a recent regression that allows users to specify output folders as well as filenames (e.g. `-f mydir/%p_%s`, please check the latest code which restores previous behavior for json strings so that one gets `"PulseSequenceDetails": "%CustomerSeq%_hcp_mbep2d_diff"` instead of "PulseSequenceDetails": "%CustomerSeq%\hcp_mbep2d_diff". Note, instead of escaping special characters I replace them with an underline so string length does not change.
