### ISSUE TITLE
3.0T GE Discovery 750W fieldmap Superior/Inferior labels flipped

### ISSUE THREAD

**Issue by jdkent** [rordenlab/dcm2niix#134]
Thank you for providing BIDS support, that was tipping point for me to decide to use this tool. While the other image types appear to reconstruct fine (T1w, T2w, funcs, etc), but the fieldmaps have switched superior/inferior labels, where the superior label corresponds to the bottom of the brain and vice versa. [This is a problem shared with other converters as well](https://afni.nimh.nih.gov/afni/community/board/read.php?1,79549,79549#msg-79549)

[Here is a link to an example of the offending fieldmap dicoms](http://www.dicomlibrary.com/?requestType=WADO&studyUID=1.2.826.0.1.3680043.8.1055.1.20170927003639521.875484077.2365279&manage=66bc09cd6130c73c7715024227471ed1)

Any insights into this issue would be appreciated, right now we workaround it using AFNI commands, but if the reconstruction could be done correctly from the get-go, that would be much preferred.

**Comment by neurolabusc** [comment]
Thanks for sharing the sample. Regardless of the conversion tool you use (dcm2niix, dcm2nii, dicm2nii, MRIconvert, mrconvert) the resulting NIfTI image is flipped in the superior-inferior dimension. Looking at the raw DICOMs with a tool like Horos you can see that the error exists in the raw DICOMs: the first slice at the apex of the head is at -89.2mm while the final slice at the base of the brain is at +54.8mm. Given that the DICOM header reports Head-First-Supine this is clearly [incorrect](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Spatial_Coordinates) (and since a head-coil is listed this is clearly not a foot-first supine image).

I am afraid the error is in the DICOM, not the conversion. I suggest you contact the vendor - the software version (0018,1020) is listed as 25\LX\MR Software release:DV25.0_R02_1549.b. This is a clear violation of their DICOM conformance statement, so they should be pretty responsive in fixing this.

You could fix the orientation with a simple [Matlab/SPM script](https://github.com/rordenlab/spmScripts/blob/master/nii_flipz.m). Depending on the tool you are using, you may need to clone the S-Form and Q-Form from the image you are trying to undistort. Also check that the L/R are not mirrored.
