### ISSUE TITLE
adding BIDS EchoTime1, EchoTime2 metadata for fieldmaps?

### ISSUE THREAD

**Issue by kjamison** [rordenlab/dcm2niix#139]
This might not be within the scope of dcm2niix, but for multi-TE B0 fieldmaps, BIDS metadata expects something like "EchoTime1" "EchoTime2", so that you can extract a delta-TE for preprocessing.  Is it possible to automatically add something like that to the BIDS json when appropriate?

**Comment by neurolabusc** [comment]
I do not think this is required, as dcm2niix should save each echo as a separate NIfTI volume with its own json file - so both the NIfTI descrip field and BIDS files should report the echo time for the volume. Images from multiple TRs (e.g. fMRI data) and data with different B-vectors (DTI) are stacked as 4D data, where different echo times and different coils are segmented in different files. I think this is convenient for most tools, which expect data segmented this way. For example it is possible to create fMRI runs with multiple echoes, but the software expects two 4D files with X/Y/Z/T rather than a single volume with X/Y/Z/T/E. As ever, I leave @chrisfilo as the final say for BIDS information, but I think the current solution is consistent and simple. If you have any data that is not segmented like this, I would be interested in seeing a sample.

**Comment by chrisfilo** [comment]
`EchoTime1` and `EchoTime2` fields are only required when the scanner outputs phase difference volume instead of two phase volumes (see https://docs.google.com/document/d/1HFUkAEE-pB-angVcYe6pf_-fVf4sCpOHKesUvfb8Grc/edit#heading=h.fexn37cr2yum).

In case of two separate volumes each should have it's own sidecar file with `EchoTime` field (which is what I think dcm2niix is producing).

**Comment by kjamison** [comment]
The standard Siemens GRE fieldmap outputs 2 Magnitude volumes and 1 Phase
difference volume.  In this case, the typical inputs to a preprocessing
pipeline would be 1 of those magnitude volumes (not necessarily the first
one, as the resulting fieldmaps dont really depend on which magnitude is
selected) and then the 1 (only) phase volume.

Example: My siemens scanner outputs two dicom directories for a GRE fieldmap
MR-SE013_FieldMap (144 dicom files) ... 72 per magnitude volume (2 volumes)
MR-SE014_FieldMap (72 dicom files) ... only 1 phase

The conversion generates:
13_FieldMap.nii.gz (magnitude at TE1), BIDS json "EchoTime: 0.00492"
13_FieldMap_e2.nii.gz (magnitude at TE2), BIDS json "EchoTime: 0.00738"
14_FIeldMap_e2.nii.gz (phase difference), BIDS json "EchoTime: 0.00738"

In this case, if I provide the 13_FieldMap (mag1) and 14_FieldMap_e2
(phase), I will have both TE's that are needed, but if I provide
13_FieldMap_e2 (mag2) and 14_FieldMap_e2 (phase), then I won't.

-Keith


-Keith

**Comment by chrisfilo** [comment]
I see - in this case it would be optimal if dcm2niix produced 14_FIeldMap_e2.json that includes `EchoTime1` and `EchoTime2` fields.

**Comment by mharms** [comment]
Chris Rorden will have to comment, but I’m not sure if that is possible in any straightforward way, because all the slices/DICOMs in the Siemens “Phase Difference” series are stored with a single echo time in the standard DICOM field (0018,0081), corresponding to the 2nd echo time (which is also why the JSON for EchoNumber has the value of 2 for the Phase Difference series):

(0018,0081) DS [7.38]                               #   4, 1 EchoTime
(0018,0086) IS [2]                                  #   2, 1 EchoNumbers

The other echo time *is* lurking the ASCI header, apparently as microseconds (on a VD11 example I had available):
alTE[0]     =    4920
alTE[1]     =    7380

but now you’re taking about adding code to the ‘dcm2niix’ conversion that would have to be customized to a specific type of acquisition and recon.

Cheers,
-MH

BTW, @Keith: This is tangential, but using the latest (20171017) version of ‘dcm2niix’, I don’t get the echo number included in the file name of the Phase Difference series unless I include ‘e%e’ as part of the ‘-f’ flag in ‘dcm2niix’, but then if you’re using the same conversion flags for all series, I’d have expected the file name for the “magnitude recon at TE1” to include “_e1”.


--
Michael Harms, Ph.D.
-----------------------------------------------------------
Conte Center for the Neuroscience of Mental Disorders
Washington University School of Medicine
Department of Psychiatry, Box 8134
660 South Euclid Ave.                        Tel: 314-747-6173
St. Louis, MO  63110                                          Email: mharms@wustl.edu
