### ISSUE TITLE
Problem with 

### ISSUE THREAD

**Issue by zeydabadi** [rordenlab/dcm2niix#142]
Hello all,

I have some d-MRI data that I want to anonymize. I'm using the following script in MATLAB, to anonymize and modify some dicom tags but after doing so the dcm2niix fails to correctly convert the dicom file to nifti format.
Here is part of what dcm2niix outputs:
dcm2niix -z y ./CMRR_MB2_iPAT2_61D_TR6200_b700_SFOV_AP_10
Chris Rorden's dcm2niiX version 10oct2016 (64-bit Linux)
Found 67 DICOM image(s)
slices stacked despite varying acquisition numbers (if this is not desired please recompile)
slices not stacked: protocol name varies
Slice positions repeated, but number of slices (6) not divisible by number of repeats (6): missing images?
 Warning: all images appear to be a single slice - please check slice/vector orientation
Convert 6 DICOM as ./CMRR_MB2_iPAT2_61D_TR6200_b700_SFOV_AP_10/CMRR_MB2_iPAT2_61D_TR6200_b700_SFOV_AP_10 (736x736x1x6)
WARNING: check that 2D images are not mirrored.
compress: "/usr/bin/pigz" -n -f "./CMRR_MB2_iPAT2_61D_TR6200_b700_SFOV_AP_10/CMRR_MB2_iPAT2_61D_TR6200_b700_SFOV_AP_10.nii"
slices stacked despite varying acquisition numbers (if this is not desired please recompile)
slices not stacked: protocol name varies
Error: too many NIFTI images with the name ./CMRR_MB2_iPAT2_61D_TR6200_b700_SFOV_AP_10/CMRR_MB2_iPAT2_61D_TR6200_b700_SFOV_AP_10
slices stacked despite varying acquisition numbers (if this is not desired please recompile)
slices not stacked: protocol name varies

And here is the MATLAB code:

`folder_name = uigetdir
cd(folder_name)
pwd
d = dir('**/*.dcm');
values.StudyInstanceUID     = dicomuid;
values.SeriesInstanceUID    = dicomuid;
values.InstanceCreationDate = '';
values.StudyDate  = '';
values.SeriesDate = '';
values.AcquisitionDate = '';
values.ContentDate     = '';
values.PerformedProcedureStepStartDate = '';
values.PerformedProcedureStepID = 'MR';
for p = 1:numel(d)
    dicomanon([d(p).folder filesep d(p).name], [d(p).folder filesep d(p).name],'keep', {'PatientID'},'update', values);
    %dicomanon([d(p).folder filesep d(p).name], [d(p).folder filesep d(p).name]);
    p
end`

Could someone please let me know what is the problem? and if this is not a good way to anonymize the dicom images what is your suggestion?

Thank you!
Mahmoud

**Comment by neurolabusc** [comment]
Hello, so if I understand correctly, the files converted to NIfTI correctly before you ran the Mathworks proprietary [dicomanon function](https://www.mathworks.com/help/images/ref/dicomanon.html), but not after they are processed? This would suggest the problem is with the Matlab function. Maybe you should see what happened before and after you anonymized them. Since the personal information is not converted to NIfTI, why do you need the anonymization step? In other words, the NIfTI data will be anonymized regardless of the input DICOMs. In general it is a good idea to run my software on the rawest data you can, just in case subsequent steps remove the proprietary vendor tags that contain important sequence information.

My software reports that you have provided it with 67 slices with 6 repeated locations. This suggests that some slices are missing. For example, if you acquired a 4D dataset with 6 slices per volume, one would expect that the number of images would be divisible by six (e.g. 66 slices, or 72 slices). I think you need to check the providence of your images.

I also note you are using an old version of my software, the error messages may be clearer if you use a [recent version](https://github.com/rordenlab/dcm2niix/releases).

**Comment by zeydabadi** [comment]
Dear Chris,
Thanks for your response.
Yes, you are correct that dcm2niix worked fine before anonymization.
The reason that I need to anonymize dicom data is that I need to share the dicom files with another group and then they are going to do some preprocessing on their side and then convert to nifti.
I really appreciate if you could point me to where should I look for discrepancies.

Thank you,
Mahmoud

**Comment by neurolabusc** [comment]
Since I do not have access to your data or the proprietary DICOM anonymization tool you used, it is hard to give specific advice. You could start by seeing how many slices/volumes the original data converted to - this would resolve how 67 images can have the 6 spatial positions repeated.  Since you used a professional tool, you may want to contact MathWorks as they have an obligation to provide robust tools. 

You may also want to try a more popular, free DICOM anonymization tool. A quick google of "DICOM anonymization" should provide a lot of hits. While I have not used them, I have heard of these [dcmtk](https://gist.github.com/tinku99/2652845), [gdcm](https://sourceforge.net/projects/gdcm/), and [DicomCleaner](http://www.dclunie.com/pixelmed/software/webstart/DicomCleanerUsage.html). You may also want to look [here](https://www.researchgate.net/post/Best_free_tool_for_DICOM_data_anonymization).
