### ISSUE TITLE
'TaskName' for functional images was not generated

### ISSUE THREAD

**Issue by ZhenYangCMI** [rordenlab/dcm2niix#148]
Hello,

while using dcm2bids converting functional imaging data to BIDS (dcm2niix version v1.0.20171204), the 'TaskName' field is missing in the .json file. Because of this, we got an error message while running bids-validator (see below for an exemplar error message). May I ask why do we need this field? how can we get the value for this field? Thank you.

"sub-80024_task-rest_run-02_bold.nii.gz

Location:
rawData/sub-80024/func/sub-80024_task-rest_run-02_bold.nii.gz

Reason:
You have to define 'TaskName' for this file. It can be included one of the following locations: /task-rest_bold.json, /sub-80024/sub-80024_task-rest_bold.json, /sub-80024/func/sub-80024_task-rest_run-02_bold.json"

**Comment by chrisfilo** [comment]
Hi,
This field denotes the name of the task used in the scan. Since this information is not included in DICOM headers dcm2niix is not able to propagate it automatically. This will have to be added by you (either manually or via a script).

The value of this field is totally up to you, but should be informative and reflect the nature of the task. In your case simple "rest" would suffice. In addition you can provide a link to an ontology such as [CognitiveAtlas](https://www.cognitiveatlas.org). Like everything else those pieces of metadata can be stored in sidecar JSON files (`/sub-80024/func/sub-80024_task-rest_run-02_bold.json`) or if they apply to all files in one central location (`/task-rest_bold.json`). The content would look something like this:

```
{
    "TaskName": "rest",
    "CogAtlasID": "https://www.cognitiveatlas.org/task/id/trm_4c8a834779883/"
}
```

I'm closing this issue since this is not something that can be extracted from DICOMs, but we can carry on discussing here.

**Comment by ZhenYangCMI** [comment]
Thank you so much for your quick response. This is very helpful. 
Happy holidays!
Zhen
