### ISSUE TITLE
error converting certain slices 

### ISSUE THREAD

**Issue by drspear** [rordenlab/dcm2niix#156]
I'm not an expert but I needed to convert one MRI sequence on my windows 10 computer to Nifti , using the dcm2niix bundled with mRIcroGL or the standalone version (dcm2niix.exe) , the conversion in both cases yielded errors converting certain slices of my sequence  , 23 out of 151 dicom images failed to convert , I get the "Error: Only loaded 0 of xxxxxxxxxx bytes  for [dicom image name and location]
and as a result I get the warning :"Warning: Interslice distance varies in this volume (incompatible with NIfTI format)" 
, any possible causes ?

**Comment by neurolabusc** [comment]
First of all, can you tell me what version of dcm2niix you are using - it is the first thing it reports when it runs. Please make sure you are running the  [latest release](https://github.com/rordenlab/dcm2niix/releases). The issues you are having sound like an incomplete/corrupted transfer of files from your scanner. Interslice distances rarely vary with MRI scans - due to slice interference changes this tends to change the contrast (though variability is common for CT scans). I would go back to the PACS/scanner and make sure you have a complete transfer. If the problem persists, could you privately send me one of the images that reports only 0  bytes were loaded?

**Comment by drspear** [comment]
I'm using standalone module v1.0.20171215 (latest version)
and bundled module v1.0.20170624
they both produce the same error for the same image slices 
my only source of the images is a medical CD given by the hospital where the procedure was done , I had no problem reading the images in the built in Dicom reader , I was also able to convert all images into nifti format using another software (Dicom 2 nifti 1 , but I got a separate .nii file for each dicom image , and I want the end file to be compiled like the way your software does it ) so I'm supposing it's not a corrupt file issue , i will send you a copy of some of the documents privately

**Comment by drspear** [comment]
by the way how can I send you the images , I'm new to this site and I can't find any sort of messaging interface here

**Comment by neurolabusc** [comment]
Easiest is to send a dropbox link to my email (my last name @sc.edu).

**Comment by neurolabusc** [comment]
Fixed - [replication of issue 157](https://github.com/rordenlab/dcm2niix/issues/157)
