### ISSUE TITLE
Diffusion information for DWI series from unknown manufacturers are not always detected

### ISSUE THREAD

**Issue by rdebroiz** [rordenlab/dcm2niix#158]
Hello,

We have secondary DWI DICOM series generated by an internal tool. This Series have `Manufacturer    (0x0008,0x0070)` set to the name of our toolkit.

The Diffusion information  are stored in:
```
DiffusionBValue                         (0x0018,0x9087)
DiffusionGradientOrientation            (0x0018,0x9089)
```
`b-val and b-vec` are not generated when i try to convert it with `dcm2niiX version v1.0.20171215`

If I force  `Manufacturer    (0x0008,0x0070)` to `Philips Medical Systems `, everything works properly.

The Diffusion tags are not stored in a `MRDiffusionSequence  (0x0018,0x9117)` but directly at the 'root' of the dataset. Do you think it could solve the problem? Or dcm2niix rely on the manufacturer of the dataset to detect the diffusion information anyway?

**Comment by neurolabusc** [comment]
In brief, dcm2niix does not handle data from your toolkit as different vendors use different methods to describe diffusion data. It is easy to add support for new vendors, but one needs to be careful to validate the convention used by the vedor.

The issue is that different [vendors describe diffusion parameters differently](https://na-mic.org/wiki/NAMIC_Wiki:DTI:DICOM_for_DWI_and_DTI). Not only do they use different DICOM tags, but they describe space differently. For example, Siemens describes vector directions with respect to the scanner, while GE scanners describe gradient directions with respect to the image slice. Therefore, as you change the angulation of the image with respect to the scanner bore, you get different results. My software converts these coordinates to the image space coordinates expected by FSL tools. The important thing is to document how your internal tool stores vectors when you get have input data from different vendors and when you use different  image angulation with respect to the scanner bore. The [dcm2niix wiki](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Diffusion_Tensor_Imaging) links to a dedicated word document that shows how to validate vector conversion. If your tool always uses the Philips convention, you can easily patch dcm2niix to handle this situation. For example, if your toolkit puts the name `ACME MEDICAL` into the Manufacturer tag  (`0008,0070`)  you could adjust the function `dcmStrManufacturer() `to treat this like a Philips scan:

```
    if ((toupper(cString[0])== 'A') && (toupper(cString[1])== 'C'))
        ret = kMANUFACTURER_PHILIPS;

```

Once you have fully validated this solution, you can submit an issue to have your patch included in the main code.
