### ISSUE TITLE
fliping 2D nii

### ISSUE THREAD

**Issue by anastaco** [rordenlab/dcm2niix#160]
Dear Prof. Rorden,

can I somehow convert 2D dcm in nii and flip the Y-axis with dcm2niix? The images are T1maps of the heart.
I have tried dcm2niix -isFlipY y in batch mode which is giving no output.
dcm2nii -isFlipY y would give me an output, yet without fliping the image.

**Comment by neurolabusc** [comment]
The role of dcm2niix is to generate a pure conversion from DICOM to NIfTI. You can edit `nii_dicom_batch.cpp` so that the line that begins `opts->isFlipY = true;` read `opts->isFlipY = false;` and recompile the software. This will flip the order that the image rows are written to disk. The canonical DICOM orientation is for the first line to be at the top of the screen, with subsequent lines below (like we read English), while the canonical NIfTI orientation is for the Y access to ascend from the bottom of the screen to the top (like we draw the Y axis on a cartesian grid). When flipY is set to false the data is stored in the same order. However, note that when you change these settings both the image data is reversed and so is the S-Form/Q-Form that transforms image space to world space. So an image should appear identical regardless of the flipY setting for any image viewer that uses the spatial transform. Some software allows you to disable the spatial transform (with MRIcron choose the "Reorient images when loading" checkbox in the preferences).

Again, dcm2niix is not designed to allow you to manipulate your images - rather it is designed to give a pure conversion. Flipping the anterior-posterior dimension is not something an image converter should do.  Here is a [simple Matlab script](https://github.com/rordenlab/spmScripts/blob/master/nii_flipap.m) that will flip your images along the Y dimension. Use with caution, as this obscures the true spatial orientation of your image.
