### ISSUE TITLE
Removing 1st couple dicom files 

### ISSUE THREAD

**Issue by dlevitas** [rordenlab/dcm2niix#161]
Hello,

In the past when I've converted DICOM files to NIFTI format, I've usually removed the 1st three dicom files of each functional run in order to account for equilibrium effects. Is there a way this can be done with dcm2niix, or would I need to manually move those first couple of dicom files somewhere else?

**Comment by neurolabusc** [comment]
It is common to discard the first few volumes of an fMRI series due to T1 effects - the first volumes have more signal as the hydrogen has had more time to align with the static field. In fact, many scanners do this by default - our Siemens system does not even reconstruct the first few volumes of data. If your scanner already discarded some volumes, you may not need to remove additional volumes. 

While dcm2niix's predecessor dcm2nii allowed you to skip volumes, dcm2niix no longer provides this function. The idea is dcm2niix is a minimal way to get the pure data from your scanner.

With FSL's FEAT you can discard the first few volumes by setting the [delete volumes](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FEAT/UserGuide#FEAT_Basics). You can also use FSL's command line tool [fslroi](https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=spm;b308c844.1008). For SPM I use the script [nii_cropVolumes](https://github.com/rordenlab/spmScripts/blob/master/nii_cropVolumes.m). Just remember that if you discard images your event timings for fMRI studies needs to be adjusted accordingly.

**Comment by dlevitas** [comment]
Okay, thanks for letting me know.
I was also going through the output, and I'm a little worried by this message:
```
slices stacked despite varying acquisition numbers (if this is not desired please recompile)
```
My data was acquired via interleaved multi-slicing, and I'm unsure if dcm2niix is accounting for this, hence the output message. I checked the corresponding .json file, and as a reference, this is part of the SliceTiming info:
```
"SliceTiming": [
		0,
		0.475,
		0.9475,
		1.42,
		1.8925,
		0.1575,
		0.6325,
		1.105,
		1.5775,
		2.05,
		0.315,
		0.79,
		1.2625,
		1.735,
		0,
		0.475,
		0.9475,
		1.42,
		1.8925,
```

I recall seeing somewhere that I should use the -m option in this case; is that correct?
