### ISSUE TITLE
GE DTI directions for Head First Right Decubital position

### ISSUE THREAD

**Issue by Shotgunosine** [rordenlab/dcm2niix#167]
Hi all,

I've got some DTIs collected on a GE with the participant in head first right decubital position. I'm trying to extract the bvals and bvecs with dcm2niix. This line checks for head first supine and won't generate bvals and bvecs if the orientation is not head first suppine: https://github.com/rordenlab/dcm2niix/blob/8fc0c514a7595d4afb8fac09091f5c54ecbf28ee/console/nii_dicom_batch.cpp#L207

Do you have any suggestions for how I can get the directions for my scans?

**Comment by neurolabusc** [comment]
Can I suggest you comment out lines 204..209
```
//if ((toupper(d->patientOrient[0])== 'H') && (toupper(d->patientOrient[1])== 'F') && (toupper(d->patientOrient[2])== 'S'))
//   ; //participant was head first supine
//else {
// printMessage("GE DTI directions require head first supine acquisition\n");
// return;
//}
```
and recompile the application. You can then validate the output by following the directions listed in the [dedicated document linked in the dcm2niix manual](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Diffusion_Tensor_Imaging). You could also see if the output matches that of the matlab-based dicm2nii. My sense is that this will work as both GE and FSL expect coordinates with respect to the image (rather than scanner space, where you need to correct for orientation differences). However, I have never seen any images that would allow me to test this hypothesis. 

Please tell me if this works, and I will update the code to help other users.

**Comment by Shotgunosine** [comment]
After further investigations with the folks who designed the DTI sequence used for these scans, it appears that they had a custom bvecs file and the directions the scanner wrote into the dicom header were just flat out wrong anyway. So these scans are no help at testing this either. Sorry about that and thank you for your suggestion.
