### ISSUE TITLE
List of suffixes for fieldmaps

### ISSUE THREAD

**Issue by asadmalik85** [rordenlab/dcm2niix#172]
Hi. Is there a list of all the possible suffixes dcm2niix adds to fieldmap filenames, and what they mean?

Thanks,
Asad

**Comment by neurolabusc** [comment]
In general dcm2niix creates images with 3D dimensions, or 4 dimensions when the 4th dimension is time (fMRI) or gradient (DWI). It will use the following extensions to disambiguate additional dimensions from the same series:
 - _c1.._cN  coil ID (only seen if saved independently for each coil)
 - _e2..eN additional echoes (the first echo is implicit)
 - _ph phase map (otherwise magnitude)
 - _phMag rare case where phase and magnitude are saved as the 4th dimension
 - _ADC Philips specific case DWI image where derived isotropic, ADC or trace volume was appended to the series. Since this image will disrupt subsequent processing, and because subsequent processing (dwidenoise, topup, eddy) will yield better images, dcm2niix will also create an additional image without this volume. Therefore, the _ADC file should typically be discarded.

**Comment by asadmalik85** [comment]
Many thanks for your prompt and detailed response. I also sometimes get letters appended - so far I've seen a,b, and c. Could you please describe what these mean as well?

**Comment by neurolabusc** [comment]
Note letters are appended to the end of a filename if images would otherwise overwrite each other for example if you requested filenames base on series number `-f %s`, and series 1 was a localizer scan where three orthogonal directions of slices are acquired (and NIfTI requires all slices in an image are co-planar) you might expect to see "1.nii', '1a.nii', '1b.nii'. Personally, I tend to ignore localizer scans `-i y`. You will also see these appended letters if you process the same images multiple times.

**Comment by mharms** [comment]
N.B. The letter suffixes can also occur in other (more obscure) situations, such as converting a 3D navigator series (e.g., from the MGH vNav sequences).  In that case, the orientation/position of each navigator is changing in space, so 'dcm2niix' writes out each volume as a separate NIFTI.  Note though that you are limited to 27 total files via the "automatic" letter suffixes (and those letters are not necessarily in temporal order of acquisition), so to convert them all, we actually loop through each DICOM separately using the -s flag (single file mode), and assign a unique name to each NIFTI based on the AcquisitionNumber field (which functions to also give us the correct temporal order).

**Comment by sandhitsu** [comment]
when there are three files created _e1 , _e2, and _ph -- does this mean they are magnitude image for echo 1, magnitude image for echo 2, and phase difference image respectively ?

**Comment by neurolabusc** [comment]
dcm2niix file naming is described [here](https://github.com/rordenlab/dcm2niix/blob/master/FILENAMING.md). If your requested file names do not disambiguate different images, the software will append a letter to avoid overwriting an existing image. There are typically two reasons for this:
 1. NIfTI requires all slices in a volume to be co-planar, and therefore if slices in a series are not aligned with each other they will be saved as separate files. The example of this is lozalizer scout scans that are used for planning the other images but are unsuitable for any type of analyses. I always run dcm2niix with the `-i y` to ignore these images.
 2. The filenaming requested is underspecified to disambiguate your files. For example, if you ran `-f %p` and you acquired two series with the protocol name "fMRI", then you would get `fMRIa.nii` and `fMRIb.nii`. In contrast, if you ran `-f %s_%p` to include the series number you might get `4_fMRI.nii`, `5_fMRI.nii`.
