### ISSUE TITLE
dcm2niix reverses Philips PET time series

### ISSUE THREAD

**Issue by elijahrockers** [rordenlab/dcm2niix#184]
The order of frames of dynamic scans acquired on Philips PET Gemini TOF is reversed by dcm2niix. Most likely it is due to "creative" use of the headers on their part..

**Comment by neurolabusc** [comment]
Thanks for this example. There are two issues here:

1. The order of the image instance number (0020,0013) is reverse of the AcquisitionTime (0008,0032). I have never seen this before, and this means the images appear in the reverse order in most DICOM viewing software (not just dcm2niix). When you can't rely on the instance number, you have to question what other parameters are borked. While this may technically be legal in DICOM, it is at the very least obfuscation. From my perspective, this is not a problem with my software (and the plethora of other DICOM viewers), but a problem with the source data. Hopefully the vendor can fix this on their end. 

2. The time between volumes is not consistent. That makes perfect sense for PET scans, but the images can not be saved as a 4D NIfTI, as NIfTI requires equidistant samples. This could be saved as a series of 3D NIfTI images, but you will have to do some leg work to work out the volume timing. These images also will not work with off-the-shelf NIfTI tools like SPM. I assume you will work out your own scripts to compute the mean signal and temporal dynamics. But these are atypical for the NIfTI format. If your goal is to generate a mean signal for all the volumes in a session, preserving the slice order is not important (e.g. you can use a script like nii_mean_stdev), though you may want to weight by time between these. 

For the moment, I have added a basic detection system, which will alert the user to these anomalous images: `Warning: Images sorted by instance number  [0020,0013](1..2430), but AcquisitionTime [0008,0032] suggests a different order (141600..125100) `

**Comment by drmclem** [comment]
Hi
It should also be noted that  (0020,0013) has changed definition - it used to be "image number" and is now "instance number" see for example [dicom standard](https://dicom.innolitics.com/ciods/ct-image/general-image/00200013) and is also type 2 so can be empty. 

Instance numbers do not require mapping to any spatial or temporal order and that should obtained from other values - see for example [stack overflow](https://stackoverflow.com/questions/36729820/sorting-dicom-images-in-matlab) and [this one](https://stackoverflow.com/questions/6597843/dicom-slice-ordering/6598664#6598664) - it's not even guaranteed to be unique.

Matthew

**Comment by drmclem** [comment]
Obviously I agree - part of the problem was that it was never intended as a stand alone file format - it was designed as a communication protocol between servers which is why the disk files were always opaquely named. If you have server you can negotiate your facilities up front before data storage and get the data you expect - whereas file export requires us to store everything that any software might support. 

It would be possible to only store the mandatory fields, no private tags and strip out much of the variable items, however then this would not serve the research (who are bascically the users of DICOM files) as we keep getting requests to add more. This in conjunction with the fact that most research tooling is written as a means to an end and often doesn't attempt to implement the standard as whole which leads to, entirely reasonable, short cuts.

**Comment by neurolabusc** [comment]
I think the vendors could come up with a core specification that would allow them to store private data and yet make it far easier (and faster) for typical tools to parse the datasets. For example, providing nested dataset SQs with explicit lengths at the start would allow tools that are not interested in those block to skip them entirely rather than having to parse them to work out each element length. Well designed, such a core specification could allow vendors to continue to store verbose data but allow tools to rapidly parse the relevant data.
