### ISSUE TITLE
mismatched qform/sform matrixes

### ISSUE THREAD

**Issue by SebastianSpeer** [rordenlab/dcm2niix#197]
Hi,
 
I am a trying to use fmriprep for preprocessing of my fMRI data and used dcm2niix as implemented in nipype (http://nipype.readthedocs.io/en/latest/interfaces/generated/nipype.interfaces.dcm2nii.html) and receive the following error by the BIDS validator:

sform_code and qform_code in the image header are 0.

When running fMRI prep I’m getting the following error:

“mismatched qform/sform matrixes”

I have been advised at neurostars.org to open a new issue here and add an example file.

So here is one file:

[S66.MR.WUR_SEBASTIAN.0003.0001.2018.05.20.14.50.17.406250.115062851.zip](https://github.com/rordenlab/dcm2niix/files/2076625/S66.MR.WUR_SEBASTIAN.0003.0001.2018.05.20.14.50.17.406250.115062851.zip)

Do you know what may cause this issue?

Thanks,

Sebastian

**Comment by neurolabusc** [comment]
I would check you are using [latest release](https://github.com/rordenlab/dcm2niix/releases) - if so you may want to check other code in your toolchain, as dcm2niix populates the sform and qform for your image

```
$ ./dcm2niix -f %s ~/tst/sform
Chris Rorden's dcm2niiX version v1.0.20171215 (OpenJPEG build) Clang8.1.0 (64-bit MacOS)
Found 1 DICOM image(s)
Convert 1 DICOM as /Users/rorden/tst/sform/3 (64x64x37x1)
Conversion required 0.004408 seconds (0.004376 for core code).
Chris-MBP:sform rorden$ fslhd 3.nii
filename       3.nii
...
qform_name     Scanner Anat
qform_code     1
qto_xyz:1      -3.000000  0.000000  -0.000000  98.334839
qto_xyz:2      0.000000  2.598076  -1.755000  -74.942139
qto_xyz:3      0.000000  1.500000  3.039749  -123.742523
qto_xyz:4      0.000000  0.000000  0.000000  1.000000
qform_xorient  Right-to-Left
qform_yorient  Posterior-to-Anterior
qform_zorient  Inferior-to-Superior
sform_name     Scanner Anat
sform_code     1
sto_xyz:1      -3.000000  0.000000  -0.000000  98.334839
sto_xyz:2      -0.000000  2.598076  -1.755000  -74.942139
sto_xyz:3      0.000000  1.500000  3.039749  -123.742523
sto_xyz:4      0.000000  0.000000  0.000000  1.000000

```

**Comment by neurolabusc** [comment]
Please see my [neurostars response](https://neurostars.org/t/fmri-prep-error-mismatched-qform-sform-matrixes/1767/6). I think the issue is the tiny errors introduced converting the s-form's matrix to the q-forms quaterion and back to a matrix to compare to the s-form's matrix. I suspect your code has decided that +0.0000000 is not equal to -0.00000. 

For Python, I think you want to use [numpy.isclose](https://docs.scipy.org/doc/numpy/reference/generated/numpy.isclose.html). With regards to the tolerance, bear in mind that both the s-form and q-form are stored as 32-bit floats in NIfTI1.
