### ISSUE TITLE
2D image is mirrored

### ISSUE THREAD

**Issue by athanell** [rordenlab/dcm2niix#204]
Dear Chris,

I am converting a DICOM X-ray 2D slice to a nifti. The resulted nifti is mirrored as you can see in the attached screenshot (I get a warning during the conversion about the possible mirroring). What causes this mirroring? Is there a particular DICOM tag that dcm2niix needs to correctly position the converted nifti that might be missing in my dataset?  Is there a way to avoid it?

The dcm2niix version I use is v1.0.20180614

![2d_dicom2nifti_mirroring](https://user-images.githubusercontent.com/20206739/42164421-a692f2f8-7e0e-11e8-86f1-0bb51412a3f5.png)

Thank you
Antonios Konstantinos

**Comment by neurolabusc** [comment]
Antonios

 dcm2niix is designed to create 3D volumes. The issue is determining mirroring when the depth is not known: consider looking at someone when you are facing each other nose to nose (so their left is on your right) or when looking at them from behind them like when you are standing in line at a grocery store (where there left is on your left). This also explains why [radiological and neurological views are different](https://www.nitrc.org/plugins/mwiki/index.php/mricrogl:MainPage#Neurological_versus_radiological_convention) :  radiologists imagine seeing the brain as seen from the patients feet (an inferior vantage point), while the neurologist imagines seeing the brain from a vantage point superior to the brain.

For 3D volumes we can look at multiple slices to determine the polarity of the cross product. Certainly the DICOM standard does allow you to determine this, but since 2D slices are not the use case of the NIfTI format, I have not spent time developing a robust solution. Most NIfTI tools will have a very hard time with 2D images, as even simple processes like motion correction can not deal with movement through the plane. This explains the dcm2niix feature `-i y` which ignores (does not convert) 2D slices.

I do think that if you want to work with 2D images, NIfTI is not the appropriate format. However, if you want to develop and a robust solution, please consider generating a pull request to share your solution with others.

**Comment by athanell** [comment]
Dear Chris ,
Thank's a lot for your explanation. If we will come with a solution using NIfTI I will let you know

Best Regards
