### ISSUE TITLE
QoL suggestion: a 'force' command line switch

### ISSUE THREAD

**Issue by kimjetwav** [rordenlab/dcm2niix#206]
Currently, the behaviour of of `dcm2niix` seeks to pre-emptively differentiate the names of output files should the specified output directory contain same-named .nii files as computed by the -f filenaming arguments and the file naming logic.

The -f flag also accepts exact user input (i.e. it will accept a literal string and use that as the output name). Unfortunately, this differentiation behaviour _effectively_ situationally over-rides user specified input, e.g. by accepting a filename and appending elements to it iff same-named .nii files exist (e.g. #188).

Many operating systems' shell applications, including those under both Unix-likes and Windows, provide optional 'force' flags (typically with an argument switch such as f, -f, --force, or -force) for cases in which the user prefers for the program to silently proceed with possibly destructive operations, such as deleting directories recursively, clobbering existing files, etc. These are useful when embedding programs into large scripts or workflow pipelines.

In these cases, the lack of a 'force' switch complicates the processing environment by requiring the pipeline scripts to work around the salient behaviours of the program. Our pipelines, for example, have explicit renaming steps to enforce our own naming convention when dcm2niix mangles it by appending differentiators.

I would like to propose a 'force' switch for dcm2niix that would bypass filename uniqueness logic and silently proceed to replace any existing same-named files in the output directory. It could take the form of an exclusive -F argument, a 'forced -f' that replaces -f in its command line and signals an error if used alongside another -f switch in the same command.

The default behaviour would remain the same, but this would add functionality and improve orthogonality by signalling a use case in which the salient renaming behaviour should be disabled and the filename provided to -F should be applied verbatim even if doing so clobbers existing same-named files.

**Comment by neurolabusc** [comment]
I am sorry, but I really do not know what feature you want. Can you provide an explicit situation for the situation you are having. I also do not know what you are requesting - would the "force" option overwrite a previous file of the same name? If this is what you are requesting, what other unintended consequences must be considered (e.g. if you overwrite a NIfTI file and the previous image had associated bids/bval/bvec files, must these be deleted as well)?

 - Underspecified file names: For example, if you executed "dcm2niix -f %p ~/mydicoms" and there were two series where the protocol name was "fmri", you might end up "fmri.nii', "fmrib.nii", where if you executed "dcm2niix -f %p_%s ~/mydicoms" the files would be differentiated explicitly, "fmri_3.nii", "fmri_4.nii". In this case forcing to only save one dataset would delete an entire series - is this desired?
 - Some series can not be converted to NIfTI. For example, a localizer series where a sagittal, axial and coronal slice are all part of the same series. NIfTI requires all slices must be coplanar, so this would be saved as "scout_1.nii", "scout_1a.nii", "scout_1b.nii". These 2D slices and these localizer sequences are only used for planning, and in this case I would suggest you  use the ignore option ("dcm2niix -i y -f %p_%s ~/mydicoms") which will skip these files.
 - If you run dcm2niix twice on the same dataset with the same command, there will always be naming conflicts. For example, if your naming scheme created a file "fmri_3.nii" and you rerun the same command you will get "fmri_3a.nii" the second time due to the naming conflict (and a clear warning). If this is not the desired effect you can simply clear your output directory before every write.  

Maybe a good place to start is for you to fork dcm2niix and make the changes you desire. This will allow you to test out the use cases and identify any unintended consequences. If there is community interest in your solution, you can generate a pull request to inject your code into the main project.
