### ISSUE TITLE
Support for vNav "Image Comments" aggregation

### ISSUE THREAD

**Issue by hacevedo** [rordenlab/dcm2niix#208]
Hi - my group uses vNav sequences that encode movement data in the "Image comments" field of each DICOM in a series. We're looking to have this information aggregated into an array that is included in the BIDS sidecar. 

The Image Comments fields is not currently part of the BIDS spec, but there's been some [discussion](https://groups.google.com/d/msg/bids-discussion/fzLhKTVam9s/Klsbo7-pAQAJ) about it - suggesting that having Image comments included as an array would be acceptable.

I'm curious if this is something you'd consider including in dcm2niix. I realize it would change some of the data structure assumptions currently being made. I was wondering if it would be possible to add a vNav specific flag or even a more generic flag to allow stacking specified fields into an array?

I'm glad to contribute the changes myself - just want to be sure this is the appropriate place to add this functionality.

**Comment by neurolabusc** [comment]
Have you tried the latest [release](https://github.com/rordenlab/dcm2niix/releases)? If the DICOM Image Comments tag (0020,4000) exists, than the BIDS tag `ImageComments` will be generated. For example:
`
 "ImageComments": "Unaliased_MB4_PE3_SENSE1",
`

**Comment by hacevedo** [comment]
Thanks for the quick reply!

I'm aware that ImageComments exists as a single-value field in the BIDS json. I am asking about having the BIDS tag support an array datatype - for cases like vNav sequences where the tag differs between acquisitions in the series. As mentioned above, allowing an array for this field won't break BIDS compatibility as it isn't currently included in the spec.

vNav sequences are important as they provide motion numbers for structural images. We're hoping that by including it in the BIDS output, we will be able to get them included in mriqc's IQM reports so that we can have all of our QC metrics in one place.

**Comment by neurolabusc** [comment]
Can I suggest you generate a fork and explore this. For classic DICOM scans this should be fairly easy to enable (though I think enhanced DICOM will require a different approach). If you change the function
`  void nii_SaveBIDS(char pathoutname[], struct TDICOMdata d, struct TDCMopts opts, struct nifti_1_header *h, const char * filename) {
`
to be
`void nii_SaveBIDS(char pathoutname[], int nConvert, struct TDCMsort dcmSort[],struct TDICOMdata dcmList[], struct TDCMopts opts, struct nifti_1_header *h, const char * filename) {
`
that will allow the nii_SaveBIDS to access the image comments from all the images in the series. You will want a function that tests wether the image comments vary (which in my experience is rare) and if they do vary to save this as an array. 
A fork will allow you to develop this feature, detect any unintended consequences and use it for your own data. You could also generate a pull request to add your patch into the main project. @chrisfilo is the maintainer for the BIDS support in dcm2niix, so he would decide whether this is a patch that will benefit the general community.

**Comment by mharms** [comment]
Hi,
There is a bigger issue here, which is that each navigator (DICOM) gets converted into a separate (3d) NIFTI volume because the orientation varies between them.
i.e., get the message: slices not stacked: orientation varies (localizer?)
Then, since there are more than 26 localizers, you run into “Error: Too many NIFTI images with the name XXX”

Our solution locally to this problem for HCP has been to simply convert each navigator DICOM one at a time using the ‘-s y’ flag, assigning each output a unique name according to the AcquisitionNumber of the DICOM.  Then, if you want all the navigators as a single 4D volume, you can merge them together (although note that the sform/qform will only be correct for one of the frames).  We also merge the individual json’s together (using a custom bash script) into a single json in which the AcquisitionTime, AcquisitionNumber, ImageComments, and ImageOrientationPatientDICOM” fields are arrays (with the values from each individual navigator).

Note though that this still isn’t quite enough to be able to reconstruct the sform/qform for each individual navigator because we are missing the ImagePositionPatient (0020,0032) entry for each navigator.

Also, as an aside, if you are looking for the actual motion numbers rather than the cryptic ImageComments encoding of the motion (which uses quaterions), there is a python script here that handles that:
https://github.com/MRIMotionCorrection/parse_vNav_Motion

Cheers,
-MH

--
Michael Harms, Ph.D.
-----------------------------------------------------------
Associate Professor of Psychiatry
Washington University School of Medicine
Department of Psychiatry, Box 8134
660 South Euclid Ave.                        Tel: 314-747-6173
St. Louis, MO  63110                          Email: mharms@wustl.edu

**Comment by neurolabusc** [comment]
@mharms - is there a robust way to detect these navigator images? The NIfTI format only provides a single spatial transform for each file, so we can not combine 3D volumes as a 4D file if the image orientation varies. For example, with localizer/scout series where an axial/sagittal/coronal are acquired: we can not combine these 2D slices as a 3D volume. It seems like these navigator scans are a special situation where the varying spatial position is recorded. If we can robustly identify these, we could convert them as a 4D file. Rather than using BIDS to describe motion, perhaps we could use a popular, simple format. I always thought SPM's rp*.txt file was a nice way to encode the realignment parameters. If we used this format SPM would automatically recognize the 4D volume had associated motion.

I am very busy at the moment, and my center does not acquire these scans. I am happy to review a pull request, but realistically will not spend much of my own time on this in the near future.

**Comment by neurolabusc** [comment]
1. If you build the latest code, you  will note that there is a new naming option `-f %s_%r` will name files based on their series number (%s) and the instance number (%r). The instance number (DICOM tag 0020,0013) will typically be zero for the first image in a stacked set, but if the images are not stacked, this should identify each image. This might be helpful to prevent the name clashing. Note that you can zero pad these values, so `-f %2s_%4r` will generate files with names 01_0001, 01_0002...

2. As a bonus, the new code has a new DICOM renaming feature (`-r y`). This is a very fast but rudimentary way to organize/sort DICOM data. For example 
 `dcm2niix -r y -f %s_%d/%4r -o ~/sorted ~/unsorted`
Will renaming DICOM files so into tidy folder:
 ~/sorted/3_fMRI/0001.dcm, ~/sorted/3_fMRI/0002.dcm, ... ~/sorted/T1/0001.dcm, ~/sorted/T1/0002.dcm, ...

**Comment by mharms** [comment]
Our approach to identifying the navigator series is a little ugly, which is part of the reason that I never pushed to include this as part of 'dcm2niix' itself.  Complicating the situation is that the MGH vNav implementation that we are using for HCP runs a very short duration actual "setter" scan (that writes the nav parameters to a disk file for looking up the nav parameters to use during the structural scan itself). The series corresponding to that short "setter" data doesn't use mosaic format, whereas the navs themselves are saved out in mosaic format.  So, altogether the approach that we use to identify the navigator series turns out to be this:
```
  if [[ $image_type == *"MOSAIC"* && $sequence_name == *"ABCD3d1_32ns"* ]]; then
    echo "2nd setter series found. Converting single frames then combining."
...
```
Given that we have a workable solution to this in-house at this time, I also do not plan to spend time on this.

**Comment by chrisfilo** [comment]
Since I was summoned... I see nothing against adding ImageComments to the BIDS spec (but obviously dcm2niix can output it even without that). It might be better to wait for the implementation details to be resolved first so we would know what kind of data to expect.

**Comment by neurolabusc** [comment]
@mharms and @hacevedo can you please build and test the latest commit and see if this resolves your issue. The new code detects if slices are not parallel: in this case separate volumes are generated with the instance number (0020,0013) appended to the name in the format _i%04d, so for a 168 volume vNav with 32 slices per volume, you will get files with names like `3_i00001.nii, 3_i00065.nii, 3_i00097.nii, 3_i00129.nii, ... 3_i05121.nii`. Note in this example the first file has 2 (parallel) volumes, while all others have just one. Perhaps this is typical of vNav motion detection, and perhaps you simply exclude the first volumes due to T1 effects, otherwise you may want to parse these. Regardless, with this system each NIfTI file correctly reports its' orientation, and therefore should provide an excellent starting estimate for co-registration. 

Personally, I prefer this method to @hacevedo's suggestion of saving the different rotations in a non-standard BIDS tag, which would require us to intentionally violate the NIfTI format. These images should be easy to detect and merge with subsequent scripts, if that is what you desire.

Previous versions of dcm2niix would not convert these vNav files if the user wanted to "ignore derived, localizer and 2D images" (`-i y`), as the non-parallel planes triggered the localizer detection. The new version now converts these files, and any other non-parallel volumes that are stored in mosaic format. Be aware that the upcoming Siemens DICOM XA format deprecates mosaic format, so we may need to tune the vNav detection for Vida users.
