### ISSUE TITLE
Slice orientation

### ISSUE THREAD

**Issue by eduardor2k** [rordenlab/dcm2niix#217]
Hi, it seems that during the conversion, the orientation is not taken into account:

![imagen](https://user-images.githubusercontent.com/318278/44664140-b2298980-aa12-11e8-9326-acda394656d3.png)

When the image should look like this:

![imagen](https://user-images.githubusercontent.com/318278/44664258-03d21400-aa13-11e8-93d7-fa54cd2592bd.png)

**Comment by neurolabusc** [comment]
Looks like you are using MRIcro (from 1999) which was designed for the Analyze format. The NIfTI format was developed in 2003 and includes spatial orientation parameters. Can I suggest you use MRIcron (MRIcro for NIfTI) or if your hardware can support it try [MRIcroGL](https://www.nitrc.org/plugins/mwiki/index.php/mricrogl:MainPage). MRIcro is great if you are using SPM2 or earlier. Most modern tools (FSL, SPM5+, AFNI, etc) support the spatial transforms (sforms) introduced with the NIfTI format. MRIcro shows image data as it is stored on the disk. With MRIcron you can choose the preferences to select whether the data is reoriented or not.

**Comment by eduardor2k** [comment]
Is there a way to force the nifti orientation ouput?

**Comment by neurolabusc** [comment]
dcm2niix always provides both sforms and qforms in the NIfTI headers. However, tools created prior to the NIfTI standard do not recognize these. You could reslice your data on disk so it roughly matches canonical space - e.g. using [fslreorient2std](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/Fslutils). Use those tools with caution, as it can disrupt fMRI slice timing and any other processing that assumes the the slices are stored on disk in a temporal rather than spatial order. For that reason, this reslicing is beyond the scope of dcm2niix. The job of dcm2niix is to provide you with a lossless conversion of the DICOM data.
