### ISSUE TITLE
GE dwi not right

### ISSUE THREAD

**Issue by njhunsak** [rordenlab/dcm2niix#220]
Hi,

I have dwi sequence from a GE scanner that I'm trying to convert. I'm using dcm2niix version v1.0.20180826 BETA, but my NIFTI images look all wrong.

<img width="709" alt="screen shot 2018-09-06 at 1 11 32 pm" src="https://user-images.githubusercontent.com/4333838/45180063-91fa8700-b1d7-11e8-8201-79b2a10ecc01.png">

I'm using the basic command:

```bash
dcm2nii -f dwi -z y ~/dicomdir
```

Naomi

**Comment by neurolabusc** [comment]
Thanks for sharing samples. The issue exists in the DICOM images: dcm2niix is faithfully converting these images. You can use your favorite DICOM viewer to verify (it appears you are using a MacOS computer, so you may want to try out the fantastic [open source Horos](https://horosproject.org/)). The slice you show above is image instance 1163.

Specifically, the issue here is aliasing. Many of the slices exhibit aliasing/leakage that look like classic (though severe) [multi-band artifacts](https://practicalfmri.blogspot.com/2016/06/starting-points-for-sms-epi-at-3-t-part.html#more).
