### ISSUE TITLE
Field Map JSON file contains T1w Information 

### ISSUE THREAD

**Issue by dlevitas** [rordenlab/dcm2niix#234]
Hello,
I have some data that was acquired on a Siemens MAGNETOM Prisma, and am converting it using dcm2bids, which calls dcm2niix `version v1.0.20171215 GCC4.4.7 (64-bit Linux)`. The field mapping was acquired, consisting of two spin echo maps (PA and AP) phase encoding directions; however, when I was going over the JSON files, the file for the first spin echo (PA), contains the information of the T1w anatomical, which was run just before the field mapping. The JSON file for the 2nd spin echo does not have this problem, containing all the pertinent field map information. I'll check to see if there's something wrong with the config file, but I wanted to see if someone has had this issue occur, and what possible solutions there may be?

Thank you for the help.

Dan

**Comment by dlevitas** [comment]
I was able to resolve the issue. I had mislabeled something in my config file, which was causing the problem. I'm closing issue now.

**Comment by neurolabusc** [comment]
I would suggest the following

1. Does the [latest stable release](https://github.com/rordenlab/dcm2niix/releases) (v1.0.20180622) solve your problem?
2. Does the latest development release solve your problem? For Windows users you click the green [AppVeyor button](https://ci.appveyor.com/project/neurolabusc/dcm2niix) from the dcm2niix Github home page and then press Artifacts. For Unix users

```
$ git clone https://github.com/rordenlab/dcm2niix.git
$ cd dcm2niix/console
$ make
$ ./dcm2niix
Chris Rorden's dcm2niiX version v1.0.20180918  GCC6.1.0 (64-bit MacOS)
...
```
 
3. Does the Matlab-based [dicm2nii](https://github.com/xiangruili/dicm2nii) exhibit the same issue - if so this suggests that the issue is with the DICOM images, not the converter. If not, it suggests an issue with dcm2niix.

I can not replicate your issue, and it is not observed in any of the AP/PA datasets in [dcm_qa](https://github.com/neurolabusc/dcm_qa) which is used to validate every dcm2niix commit. I think if dicm2nii does not exhibit this problem I would need to see the dataset to understand the issue.
