### ISSUE TITLE
Direction error lead to mask mismath

### ISSUE THREAD

**Issue by huawenqing** [rordenlab/dcm2niix#249]
After I used dcm2nii to convert the original image DICOM series into a nii volume, the mask direction changed by inversion and led to mismatch between the original image and mask. My original image is DICOM and segmentation mask is Nifti, I want to process them in Nii format. I did nothing to nii mask and the  orignal image direction looks normal after convertion. Why the problem happened?

**Comment by neurolabusc** [comment]
The issue you have is not with dcm2niix but the software you are using to view your images. You are using software that does not account for the fact that NIfTI uses a different coordinate system than DICOM. Specifically, DICOM images use the convention that the first line is at the top of the line with subsequent lines below: analogous to how we read English from top to bottom. On the other hand, NIfTI displays images with the first rows at the bottom and subsequent rows ascending. This is exactly the way we draw a graph with cartesian coordinates: Y increases as we move up the page. This issue is described on the dcm2niix [wiki page](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Spatial_Coordinates). Popular tools that show NIfTI images incorrectly include MIPAV and ImageJ.

There are many great tools that display NIfTI images correctly. My personal favorites include:
 - [MRIcroGL](https://www.nitrc.org/projects/mricrogl) requires OpenGL leading to fast graphics.
 - [MRIcron](https://www.nitrc.org/projects/mricron) does not require OpenGL for more compatibility.
 - [FSLeyes](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FSLeyes) 
 - [nii_viewer](https://github.com/xiangruili/dicm2nii) for Matlab.
 - [Mango](http://ric.uthscsa.edu/mango/).
 - [Papaya](http://ric.uthscsa.edu/mango/).

For completeness, dcm2niix has a hidden feature invoked with `-y y` which flips the storage to disk of the y-coordinate. This transform is stored in the header S-Form and Q-Form, so images should appear correct in tools that use this to reorient images, and images will typically look correct in tools that expect DICOM ordering (MIPAV, ImageJ). However, images will now look upside down in Analyze/NIfTI viewers that ignore the S-Form and Q-Form. I would discourage use of this feature, but it might help you in a pinch. 

Others have reported this situation before - see issues [26](https://github.com/rordenlab/dcm2niix/issues/26), [160](https://github.com/rordenlab/dcm2niix/issues/160) and [here](https://www.nitrc.org/forum/forum.php?thread_id=9324&forum_id=4703). I strongly encourage you to lobby the developers of the popular tools that do not handle NIfTI appropriately to update their software.
