### ISSUE TITLE
Conversion problems with IconImageSequence

### ISSUE THREAD

**Issue by hwahlukdd** [rordenlab/dcm2niix#250]
Hi,

I use dcm2niiX version v1.0.20181108  (JP2:OpenJPEG) (JP-LS:CharLS) Clang7.0.2 (64-bit MacOS) and have stumbled over the following problem:

In my dicom-files is an unknown (to me) field called "IconImageSequence", with the following output from pydicom:

> (0088, 0200)  Icon Image Sequence   1 item(s) ----
   (0008, 2111) Derivation Description              ST: 'LossLess compression with JPEG 2K, compression ratio 1.906'
   (0008, 9215)  Derivation Code Sequence   1 item(s) ----
      (0008, 0100) Code Value                          SH: '121327'
      (0008, 0102) Coding Scheme Designator            SH: 'DCM'
      (0008, 0104) Code Meaning                        LO: 'Full fidelity image, uncompressed or lossless compressed'
      ---------
   (0028, 0002) Samples per Pixel                   US: 1
   (0028, 0004) Photometric Interpretation          CS: 'MONOCHROME2'
   (0028, 0010) Rows                                US: 64
   (0028, 0011) Columns                             US: 64
   (0028, 0034) Pixel Aspect Ratio                  IS: ['1', '1']
   (0028, 0100) Bits Allocated                      US: 8
   (0028, 0101) Bits Stored                         US: 8
   (0028, 0102) High Bit                            US: 7
   (0028, 0103) Pixel Representation                US: 0
   (7fe0, 0010) Pixel Data                          OB: Array of 2166 bytes

When I convert my dicoms to nifti using dcm2niix, I get nifti files not with the original inplane resolution of 256x256 voxel, but 64x64, the resolution of the icon image. The only tool which so far could 1) handle the lossless j2000 compression and 2) convert these dicoms correctly is [https://de.mathworks.com/matlabcentral/fileexchange/42997-xiangruili-dicm2nii](dicm2nii) for MATLAB.

This was seen with dicoms from Philips and GE machines, but from the same study center. I suspect their PACS is responsible for this.

Is this a known matter?

**Comment by neurolabusc** [comment]
I suspect these images were touched by a PACS system running an old version of the GEIIS PACS system (see issue [113).](https://github.com/rordenlab/dcm2niix/issues/113) The GEIIS would insert thumbnails that broke strict DICOM compatibility. Since these broken images were so common, most tools (including dcm2niix) include kludges to handle these files. However, if the images are modified by a system that is unaware of the thumbnails the issue can be compounded - for example a tool that converts explicit to implicit VRs can hide some of the private SQs inserted by the PACS system. Likewise, tools that attempt to change the transfer syntax of these tainted images often compound the problem. 

It seems like you have three options:
1. Get a copy of the images prior to them being tampered with by the GEIIS system. Ideally upgrade the PACS - the resulting images are not legal DICOMs and even if we develop a kludge they are likely to create archival problems.
2. If (1) is impossible, see if you can prevent any further manipulation (VR conversion, transfer syntax conversion, etc) after the images have been borked by the PACS. 
3. Send me a copy and I can add a detection kludge.
4. Adapt the code of dcm2niix to identify your variant of these images (hint: the isIconImageSequence flag detects other variants of this problem).

The big challenge is correctly converting your broken images without the unintended consequence of breaking conversion of legitimate DICOM images.

**Comment by hwahlukdd** [comment]
Thanks for your response and insight. Options 1,2,4 are out of my technical reach, so I could bother you with option 3.

But I played around a little and that the following method works wonders: Just delete the data element. It's a bit of a sledgehammer method, but dcm2niix now works fine.

**Comment by neurolabusc** [comment]
Feel free to share an image directly with me if you want me to add a kludge. For others, can you share your method for removing the offending icon, e.g. what command did you run. I assume you could do this with `gdcmanon`.

**Comment by hwahlukdd** [comment]
Of course, I used the following [incomplete] python-code (tested on Python 3.6):

`from pydicom import read_file`
`from copy import deepcopy`    

`dcm = read_file(filepath)`
` # just to be sure to not mess with the original dicoms`
`dcm_new = deepcopy(dcm)`
`try:
     del dcm_new.IconImageSequence`
`except:     pass`
`dcm_new.save_as(new_filepath)`
