### ISSUE TITLE
Incorrect UINT16 conversion

### ISSUE THREAD

**Issue by alund** [rordenlab/dcm2niix#251]
The attached [dcm2niix_bug.zip](https://github.com/rordenlab/dcm2niix/files/2665084/dcm2niix_bug.zip) contains 2 DICOM files which seem to me to be converted incorrectly by `dcm2niix`. Also included are a couple of scripts that (with the appropriate Python packages) demonstrate the problem.  The script converts the DICOM files to NIfTI using both `dcm2nii` and `dcm2niix`, and then prints the range of pixel values (using Python and `nibabel`). Slicer reports the same pixel value ranges for the two files.

```
Converting to NIfTI using dcm2nii
==================================
Chris Rorden's dcm2nii :: 4AUGUST2014 (Debian) 64bit BSD License
Data will be exported to dcm2nii.d/
Validating 2 potential DICOM images.
Found 2 DICOM images.
Converting 2/2  volumes: 1
MR-ST001-SE029-0001.dcm->18991230_000000s029a1001.nii
Warning: for compatibility, converting UINT16->FLOAT32, range: 34101
 If you prefer filesize over compatibility, edit your preference named UINT16toFLOAT32
GZip...18991230_000000s029a1001.nii.gz

Pixel value range
dcm2nii.d/18991230_000000s029a1001.nii.gz  0.0  34101.0

Converting to NIfTI using dcm2niix
==================================
Chris Rorden's dcm2niiX version v1.0.20181125  (JP2:OpenJPEG) (JP-LS:CharLS) GCC5.5.0 (64-bit Linux)
Found 2 DICOM file(s)
Convert 2 DICOM as dcm2niix.d/output.nii.gz (136x136x2x1)
Conversion required 0.003205 seconds (0.003201 for core code).

Pixel value range
dcm2niix.d/output.nii.gz.nii.gz  -31435  32696
```

I get the same results from v1.0.200180622 (the only other version I have at hand).

**Comment by neurolabusc** [comment]
@alund - can you try out version v1.0.20181210 on the developmental branch> It turns out that BOTH dcm2nii and dcm2niix got this wrong. The correct pixel range should be 0..4054.

Furthermore, every DICOM viewer I tried displayed these images incorrectly! The issue is that the header specifies Bits Allocated (0028,0100) = 16 and Bits Stored (0028,0101) = 12, so the pixels should have a maximum range of 0..4095 (assuming slope 1 and intercept of zero). However, most tools just read these as 16 bits, assuming the top 4 bits are zeros. I am not sure if the DICOM standard requires this, but it is a good idea for image compression, ensuring no buffer overflow, and faster reads. This is not the case with your data - I assume there is some buffer overflow in the unused 4 bits. One hopes this is not leaking private information. My kludge now ensures 12-bit data is clipped to 0..4095 - at the cost of a small performance hit.

Can you tell me if these images were generated by Siemens or by local software? If these were generated by Siemens, please contact your research collaboration manager. This data breaks most viewing tools and might be leaking private details. I would not consider these DICOMs archival quality. In addition, I note the required Type I tags Intercept (0028,1052) and Slope (0028,1053) are missing, as well as the Type 3 (but very useful) protocol name (0018,1030). I am not sure if these were removed by anonymization software but I would ensure they exist in archival data.

**Comment by alund** [comment]
Thanks for the investigation. I figured it was something unusual.

The Protocol Name was stripped during anonymization; it was "diff_15iso_b15k_54dir_AP". The slope and intercept were missing.

I do not know the history of the files, but I will see if I can find out. I was just doing an exhaustive comparison of `dcm2nii` with `dcm2niix` using as many DICOM series as I could find, as I am in the process of (finally!) converting our computational pipeline to use `dcm2niix`.

I will also try v1.0.20181210.

**Comment by alund** [comment]
v1.0.20181210 fixes the problem. I have not yet been able to confirm the history of these files. This was the only series out of a large number I tested that triggered this problem so a systematic problem seems unlikely.

Thank you so much for your prompt response and attention to detail.

**Comment by alund** [comment]
I have now confirmed that the data was produced by experimental local software, not by Siemens.

**Comment by neurolabusc** [comment]
Thanks for the feedback, I am glad that in this case the error was local software. I will keep this fix in future versions of dcm2niix to ensure no private data leaks into the image data. One of the reasons I really like the [gdcm](http://gdcm.sourceforge.net/wiki/index.php/Pixel_Padding_Value) tools is that they are so robust for DICOM images seen in the wild rather than just as specified in the complicated standard. As noted in the gdcm guidelines for DICOM display/conversion: 

> one cannot assume that the bits above the Bits Stored (0028,0101) range of values (i.e. above the high bit) will be zeroes, or will contain 1's for sign extension of signed pixel representations, or not contain overlay - i.e. one cannot just ignore Bits Stored (0028,0101) and treat every stored pixel as if it is a valid 16 bit unsigned or signed value.
