### ISSUE TITLE
Number of volumes

### ISSUE THREAD

**Issue by sandhitsu** [rordenlab/dcm2niix#257]
I have looked at options and BIDS specifications, and it does not look like number of volumes in a converted 4D acquisition is stored in the json file that dcm2niix create, nor is there an option to do it. Is that right ?

**Comment by neurolabusc** [comment]
BIDS is the combination of a NIfTI image and a JSON sidecar. The sidecar is designed to extend but not replicate information in the NIfTI header (with the exception of [TR](https://groups.google.com/forum/#!topic/bids-discussion/RkPN7B6-oWg)). This is intententional, as it avoids conflicts if there was a discrepancy between these two sources of information. The number of volumes is stored in dim[4]..dim[7] of the NIfTI header (virtually always dim[4]). Since it is present in the NIfTI header, it is intentionally not included in the sidecar. You can extract information from  the NIfTI header using many tools including nibabel, fslhd, nii_tool, load_untouch_header_only, etc.
