### ISSUE TITLE
Bvec calculation for Siemens

### ISSUE THREAD

**Issue by ZviBaratz** [rordenlab/dcm2niix#269]
Hi all,

I'm not really sure this is an issue, however I didn't really know where I should ask - 
I'm getting slightly different values when extracting the (0019, 100e) tag from my Siemens DTI images and comparing to the output from dcm2niix. 
Here is an example:

![image](https://user-images.githubusercontent.com/22370149/52709574-cdbf2700-2f95-11e9-8dc3-5c8a9e2ca1ba.png)

I'm getting differences of up to 0.05527 in this case. Am I missing a computational step? I tried to look over the [nii_dicom_batch.cpp](https://github.com/rordenlab/dcm2niix/blob/master/console/nii_dicom_batch.cpp) file in this repo but unfortunately my C++ is non-existent and I didn't get very far. In any case I was hoping this isn't problem with dcm2niix's extraction of the data and that you might be able to tell me what I'm missing.

Thank you very much and all the best,
Zvi

**Comment by neurolabusc** [comment]
FSL bvec vectors are relative to the image, while Siemens reports gradients relative to the scanner bore. Therefore, dcm2niix [rotates](https://github.com/rordenlab/dcm2niix/tree/master/Siemens) the vectors appropriately.I assume your Python script is reporting the raw data. Also, be aware that DICOM and NIfTI use different spatial frames of [reference](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Spatial_Coordinates). For Siemens Axial DTI data, dcm2niix will reverse the order of the rows in the image data: the default for DICOM is to have the first line at the top of the screen, while for NIfTI the first line is at the bottom.

**Comment by ZviBaratz** [comment]
I'll dive into the links and figure out how to best implement the conversion for the gradients. I don't actually need the conversion to NIfTI, just the vector data.
Thank you very much for your help and generally for the great work you do here!

**Comment by neurolabusc** [comment]
@ZviBaratz this sounds fine. For dcm2niix the relevant function is `siemensPhilipsCorrectBvecs()`. If you are going to apply this to images converted by another tool, you will want to make sure that you deal with special situations:
 1.) Is the order of the rows the same as DICOM, or flipped to match NIfTI convention. Note that dcm2niix can be compiled either to flip or not flip the Y axis and the bvecs are adjusted accordingly (see the code `if (!opts.isFlipY ) {`).
 2.) Be cautious that for historical reasons FSL makes strong assumptions regarding the bvecs and the orientation of your image. This is described [here](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FDT/FAQ#What_conventions_do_the_bvecs_use.3F) as well as [here](http://justinblaber.org/brief-introduction-to-dwmri/). Its been a while since I played with this, but I think you will see a special warning for a negative determinate (`kSliceOrientMosaicNegativeDeterminant`) to detect this. This effectively detects if the volume is saved using right-hand rule or not.
 3.) Unlike the other vendors, GE uses the image frame of reference (“MR physics” logical coordinates: phase, frequency and slice directions).

**Comment by ZviBaratz** [comment]
Thank you so much for all this valuable information!
