### ISSUE TITLE
ENH: Request command line option to abort on file overwrite

### ISSUE THREAD

**Issue by hjmjohnson** [rordenlab/dcm2niix#276]
There are times when the same dcm2niix command may accidentally be run for the same inputs/outputs.

It would be nice if dcm2niix had a command line option to simply abort if the action would result in overwriting an existing file of the same name.

```bash
## -w write output behavior ( 0 = write nothing for a file that exists with desired name  1 = overwrite existing file with same name, default 2 = write with new suffix as a new file ) 

dcm2niix -w -b y -z y -f %p_%t_%s -o my_img dcm_dir  #<- Results in a new image written my_img_blah_blah_blah.nii

dcm2niix -w -b y -z y -f %p_%t_%s -o my_img dcm_dir  #<- Results nothing written to disk, but a warning "Filename: my_img_blah_blah_blah.nii, already exists, 
```

Currently I write the file to a temporary location, use bash to see if the file exists in the final location, and then move or delete the temporary files.

Thank you for your consideration.

**Comment by neurolabusc** [comment]
@hjmjohnson 

Can you test the latest developmental commit? It includes the feature you request.

```
-w : write behavior for name conflicts (0,1,2, default 2: 0=skip duplicates, 1=overwrite, 2=add suffix)
```

I do have a few comments:

- The overwrite option will delete all pre-existing matching files with the extensions [.nii,.nii.gz, .nrrd, .nhdr, .raw.gz, .json, .bval, .bvec]. In other words, if a T1 scan overwrites a DWI scan we want to make sure that we not only overwrite the NIfTI image but also eliminate the DWI's associated bval/bvec files.
- Note that the impacts file overwrites both within and between calls to dcm2niix. In other words, consider a study where a T1, T2 and fMRI scan are all acquired in the same session. Running the command "dcm2niix -f %t ~/myDir" does not disambiguate between these different images, since they have the same study time. If this is done with the default `dcm2niix -f %t -w 2 ~/myDir` then the user will get three images `20081029124138.nii`, `20081029124138a.nii`, `20081029124138b.nii`. However, running `dcm2niix -f %t -w 0 ~/myDir` or `dcm2niix -f %t -w 1 ~/myDir` will only create a single image as output (albeit warnings are generated). Clearly, the user should be requesting a better file name, e.g. `dcm2niix -f %t_%s -w 0 ~/myDir` disambiguates between the different image series. For a beginning user, it may be unclear why only one image was created. Therefore, this is a pretty advanced option with potential for unintended consequences.

**Comment by hjmjohnson** [comment]
@neurolabusc Thank you for this.  I'll test during my next data migration over the next month.
