### ISSUE TITLE
Filenaming Option for Alpha Character Added in Filename Conflicts

### ISSUE THREAD

**Issue by jrussell9000** [rordenlab/dcm2niix#278]
Currently, when dcm2niix detects a filename conflict, it appends an alpha character to the end of the filename (great!).  Would it be possible to add a filename option for this character, allowing the user to position the character in the filename?  Relatedly, would it be possible to add an option to select whether to use letters of numbers?  This would come in handy for identifying run numbers (e.g., in BIDS format) in similarly named sequences of scans. 

I'm using dcm2niix v1.0.20181114.

**Comment by neurolabusc** [comment]
Please see the [filenaming](https://github.com/rordenlab/dcm2niix/blob/master/FILENAMING.md) page for more details (until the next stable release, you may want to look at the [developmental page](https://github.com/rordenlab/dcm2niix/blob/development/FILENAMING.md)).

dcm2niix uses characters at the end of a name as a last resort to avoid overwriting files. With the exception of localizer scans (which you never want to save anyway, and can typically be skipped if you use `-i y`), I tend to think of the appearance of these characters as a sign that something went wrong in the conversion. The typical problem is that the user failed to provide a naming scheme to correctly disambiguate their images. For example, if you use `-f %t` the resulting file names are based on the study time, so different series from a single time will conflict with each other. On the other hand, `-f %t_%s_%p` will ensure that each series is saved separately and the protocol name is added for context.

Be aware that the file naming conflict character is dcm2niix's last desperate attempt to help the user understand their data. You should use it as an opportunity to work out a new naming scheme to separate your images. Since different vendors use DICOM differently, dcm2niix you will want to customize the file naming for your study. Be aware that the order of the letters 'a', 'b',...etc. are not based on any properties of the images. Rather the label simply reports the order that the conflict was detected, and typically reflect the order that the computer's file system returned the images to dcm2niix. So you can not infer from the file names "conflictedName.nii", "conflictedNamea.nii", "conflictedNamec.nii" any property of the acquisition: it is entirely possible that the "b" file was acquired prior to the "a" file. 

There are no plans to change this. I think it is important for dcm2niix to report error codes in a consistent way, and an overwrite situation should be considered an error not a desired outcome.

Any reason you prefer using an old developmental release rather than a more recent [stable](https://github.com/rordenlab/dcm2niix/releases) release or the current developmental release?

**Comment by jrussell9000** [comment]
Excellent explanation, thank you!  I seem to have entered a typo in my last, I'm currently using v1.0.20181125 (running dcm2niix -u tells me I'm using the latest release).
