### ISSUE TITLE
SliceTiming question

### ISSUE THREAD

**Issue by stilley2** [rordenlab/dcm2niix#286]
Hello,

I am having trouble understanding the SliceTiming results I'm getting. They appear to be in 1e-4 seconds, but I'm not sure. The RepititionTime is 3.

```bash
        "SliceTiming": [
                0,
                15333,
                666,
                16000,
                1333,
                16666,
                2000,
                17333,
                2666,
                17999,
                3333,
                18666,
                4000,
                19333,
                4666,
                19999,
                5333,
                20666,
                6000,
                21333,
                6666,
                22000,
                7333,
                22666,
                8000,
                23333,
                8666,
                24000,
                9333,
                24666,
                9999,
                25333,
                10666,
                26000,
                11333,
                26666,
                12000,
                27333,
                12666,
                28000,
                13333,
                28666,
                14000,
                29333,
                14666   ],
```

The data were acquired on a GE SIGNA_HDx with the EP_GR scanning sequence. I'm not sure if these values are meaningless or if they're correct but just in the wrong units. Any help/advice would be greatly appreciated. For reference, I'm using the development branch built today (2019-04-08).

Thanks!

**Comment by neurolabusc** [comment]
I would have to see a sample dataset to provide more information. You could use dcmdump, gdcmdump or `dcm2niix -v 2` to investigate this yourself. The tags and formulas dcm2niix relies on to estimate slice timing from GE datasets is [described here](https://github.com/rordenlab/dcm2niix/tree/master/GE).

**Comment by neurolabusc** [comment]
We are using the undocumented and private RTIA Timer (0021,105E) tag to determine slice timing. It seems like the units have changed - your old software (14.0) uses 1/10000 seconds while more recent software (24.0) uses seconds. Please test the latest developmental build (v1.0.20190410) which will attempt to automatically detect the units. Since this is not a public tag, we need to reverse engineer this tag. As noted in the [dcm2niix GE](https://github.com/rordenlab/dcm2niix/blob/master/GE/README.md) notes, modern GE product sequences use a public time (0018,1060). Therefore, this is an issue with older datasets and research sequences. 

@nikadon is it possible to restore your [github](https://github.com/nikadon/cc-dcm2bids-wrapper/tree/master/dicom-qa-examples/ge-mr750-slice-timing) repository with sample GE data? It is a great archive of recent GE images.

**Comment by stilley2** [comment]
Thanks @neurolabusc ! I just built from the development branch and that seems to work.
