### ISSUE TITLE
DICOM conversion issue with MultiEcho Data

### ISSUE THREAD

**Issue by dlevitas** [rordenlab/dcm2niix#300]
Hello,

I'm using dcm2niix ```version v1.0.20181125  GCC6.3.0 (64-bit Linux)``` and have run into an issue when converting multiecho anatomical dicoms. I've attached a screenshot where the converted nifti file appears "stripped". I was wondering if there is a workaround to this, as I'm trying to convert some dicom information that contains this type of anatomical data.
![Screen Shot 2019-05-21 at 2 05 14 PM](https://user-images.githubusercontent.com/25011343/58124629-aef7ae80-7bdc-11e9-83fc-e25df624e384.png)

Thank you for the help,

Dan

**Comment by Aghaeifar** [comment]
Hi
Can you upload your dicoms somewhere, so I can give a try.
The dcm2niix works fine for all of my multi-echo GREs.

**Comment by neurolabusc** [comment]
Thanks for the sample images. The issue with your data appears to be the fact that two derived images were created with the same SeriesInstanceUID (0020,000e) and differing  MediaStorageSOPInstanceUID (0002,0003). This instructs dcm2niix to stack these two images as the same volume. I do not know why your scanner created both a "MEAN"/"RMS" image as well as a "MEAN\MEAN"/"RMS RMS" image. Note that there is a naming conflict with instanceNumber (0020,0013) with the "RMS" and "RMS RMS" having identical series and instance numbers, but this is allowable by DICOM and used by some vendors. The image data in these two images is slightly different, and the file naming is interleaved such that the "RMS" filenames end in an odd number (e.g. 001_000029_000351.dcm) and the "RMS RMS" filenames end with an even number (e.g. 001_000029_000352.dcm). However, these two derived volumes should have been given different  SeriesInstanceUIDs to disambiguate them. From my perspective, this is a problem with the DICOM data, not a problem with dcm2niix - it is correctly doing what it is instructed to do. Any attempt to correct this is likely to have major unintended consequences.

I was able to separate out the first volume by running the command
`./dcm2niix -r y -f %t/%s_%p/%4r.dcm -o ~/tst/issue300/out ~/tst/issue300/in`
 which renames the files based on series and instance number. Since series and instance numbers are repeated, this generates warning of skipping files. On my file system, it read the files in alphabetical order, so it copied the "RMS" images and skipped the "RMS RMS" images.

Here are relevant tags from 001_000029_000351.dcm
```
(0008,0008) CS [ORIGINAL\PRIMARY\OTHER\ND\NORM\MEAN]    #  36, 6 ImageType
(0008,103e) LO [tfl_mgh_multiecho RMS]                  #  22, 1 SeriesDescription
(0002,0003) UI [1.3.12.2.1107.5.2.43.67093.2019042513281777149005151] #  52, 1 MediaStorageSOPInstanceUID
(0020,000e) UI [1.3.12.2.1107.5.2.43.67093.2019042513212157396399516.0.0.0] #  58, 1 SeriesInstanceUID
```
and here is 001_000029_000352.dcm
```
(0008,0008) CS [ORIGINAL\PRIMARY\OTHER\ND\NORM\MEAN\MEAN] #  40, 7 ImageType
(0008,103e) LO [tfl_mgh_multiecho RMS RMS]              #  26, 1 SeriesDescription
(0002,0003) UI [1.3.12.2.1107.5.2.43.67093.2019042513281777743405153] #  52, 1 MediaStorageSOPInstanceUID
(0020,000e) UI [1.3.12.2.1107.5.2.43.67093.2019042513212157396399516.0.0.0] #  58, 1 SeriesInstanceUID
```

I think you could write a simple script to selectively delete the "RMS RMS" files (or better yet, give them a unique series number) and be fine.

By the way, it looks like you are using E11B. I would encourage you to get this upgraded. It is my belief that the parallel development of XA10 and E11 stretched the Siemens engineering resources very thin, resulting in releases that had a number of issues. In my experience, E11C fixes most of the major issues (though the Siemens DWI sequence still has confirmed problems with phase-encoding reversal while copying slice references and the monopolar DWI uses half-sphere gradients, so for the moment I would recommend the excellent CMRR sequences for your DWI needs).

```
(0002,0013) SH [MR_VD11A_SXG10]                         #  14, 1 ImplementationVersionName
(0018,1020) LO [syngo MR E11]                           #  12, 1 SoftwareVersions
"ConsistencyInfo": "N4_VE11B_LATEST_20150530"
```

**Comment by dlevitas** [comment]
Thanks Chris! I'll work on this and try posting a solution before closing this issue. I'll also talk to our MRI physicist about looking into the E11C upgrade.

Dan

**Comment by dlevitas** [comment]
Solution I'm using is to just remove the even-numbered dicoms, since they're the ```RMS RMS``` files causing the issue.
