### ISSUE TITLE
multiple NIFTI scans generated from one volume even the Instance number of DICOMs are continuous

### ISSUE THREAD

**Issue by RiqiangGao** [rordenlab/dcm2niix#302]
Hi, 

I encounter some examples that, even the instance number of DICOMs are continuous, I can not use dcm2niix to convert those DICOMs to a single NIFTI. I also the slice distance of DICOMs and find them vary a little. Could you please tell me if you have any suggestion about those kinds of scans? Does it means that those scans still lose slices even when the instance number of DICOMs is "good"?

Thanks very much.

**Comment by neurolabusc** [comment]
Hello,
  It is worth remembering that the "instance numbers" are not well specified in the DICOM standard - there is no need for them to be sequential or even unique! Therefore, since vendors have used instance numbers in creative (yet technically legal) ways, they are not a robust method for sorting or combining DICOM images. 
 Usually, the output of dcm2niix will provide hints regarding why images from the same DICOM series were saved as separate NIfTI images. For example, variations in slice angulation, echo time, coil, study time, and X-ray exposure are all good reasons to segment data (as these properties can not be encoded in NIfTI). 
  As a first pass, you could try the `-m y` parameter, which will force DICOM images from the same series to be merged as a single NIfTI image regardless of these properties. If this does not help, perhaps you can share the text output that may shed light on your issue.

**Comment by RiqiangGao** [comment]
Thanks very much! And here is the output when I convert one example. But this example has continuous instance number. Could you please tell if this session is "valid"? If not, If there any code (e.g. python code) to verify the session is good or not? 

Thanks again, I can send this session to you if it can bring more detail. 


<
Chris Rorden's dcm2niiX version v1.0.20170624 (OpenJPEG build) GCC4.8.4 (64-bit Linux)
Found 99 DICOM image(s)
Dims 512 512 99 1 1
Warning: Interslice distance varies in this volume (incompatible with NIfTI format).
 Distance from first slice:
dx=[0 1.25 2.5 3.75 5 6.25 7.5 8.75 10 11.25 12.5 13.75 15 16.25 17.5 18.75 20 21.25 22.5 23.75 25 26.25 27.5 28.75 30 40 41.25 42.5 43.75 45 46.25 47.5 48.75 50 51.25 52.5 53.75 55 56.25 57.5 58.75 60 61.25 62.5 63.75 65 66.25 67.5 68.75 70 71.25 72.5 73.75 75 76.25 77.5 78.75 80 100 101.25 102.5 103.75 105 106.25 107.5 108.75 110 111.25 112.5 113.75 115 116.25 117.5 118.75 120 121.25 122.5 123.75 125 126.25 127.5 128.75 130 131.25 132.5 133.75 135 136.25 137.5 138.75 140 141.25 142.5 143.75 145 146.25 147.5 148.75 150]
Convert 99 DICOM as new_NIFTI/DICOM_CHEST_WO_20140829131112_102 (512x512x99x1)
compress: "/usr/bin/pigz" -n -f "new_NIFTI/DICOM_CHEST_WO_20140829131112_102.nii"
compress: "/usr/bin/pigz" -n -f "new_NIFTI/DICOM_CHEST_WO_20140829131112_102_Eq_1.nii"
Conversion required 1.632794 seconds (0.393660 for core code).
>

**Comment by neurolabusc** [comment]
The NIfTI format requires that all slices in a volume are equidistant from each other. This is not the case with your data: most slices are separated by 1.25mm between voxel centers, but there is one 10mm gap (between positions 30mm and 40mm) and one 20mm gap (80mm and 100mm). For this reason, your series can not be losslessly converted to NIfTI format. The software has created a volume where it interpolated equidistant slices (appending '_Eq' to the filename). 

This is not a limitation of dcm2niix. Rather, it reflects the fact that your raw data can not be precisely described as a single NIfTI volume. You may want to check whether this is how your slices were acquired (varying slice distances is common in CT scans like yours, though rare in MRI) or whether some DICOM files were lost. If the former and you are still acquiring data, you may want to see if you can adapt your acquisition to capture volumes with equidistant slices.

**Comment by RiqiangGao** [comment]
Thanks very much. It is very helpful for me to understand this problem.
