### ISSUE TITLE
.bvec imprecision 

### ISSUE THREAD

**Issue by CarolineBeese** [rordenlab/dcm2niix#307]
Hi,

I have DWI data recorded with a Trio scanner from Siemens. I have data from two time points. The data from time point 1 was converted with dcm2nii (from mricron 2012 lx64.zip). Now I'm analyzing time point 2 and would love to use dcm2niix (04/2019) as I have restructured all data to BIDS. 

I noticed that the precision of the .bvec values differs between dcm2nii 2012 and dcm2niix 2019, e.g.,

dcm2nii:     0.576571404933930
dcm2niix:   0.576571000000000

Where does the imprecision come from and would it possible to increase the precision of the .bvec values for dcm2niix?

**Comment by octomike** [comment]
Some additional info to this issue:

The code is using `printf()`'s `%g` conversion, which by default only uses 6 significant digits:

https://github.com/rordenlab/dcm2niix/blob/54cfd5176cb9f50c1c66d2f2e96beadf60e2edb4/console/nii_dicom_batch.cpp#L1732

From the man page:

```
       g, G   The double argument is converted in style f or e (or F or E for G conversions). 
              The precision specifies the number of significant digits.  If the precision is 
              missing, 6 digits are given; [...]
```

**Comment by neurolabusc** [comment]
There are small differences in how dcm2nii and dcm2niix handle the bvector transform, with dcm2nii using extended precision (80-bit) and printing a lot of digits. In contrast, dcm2nii uses single precision (32-bit) and printing fewer decimals. However, both are far in excess of the precision provided by the DICOM image, and the differences reflect rounding errors. Rather than reporting a single value, remember the vector direction is the normalized value of the three components - the difference in vector directions between these methods is exceptionally small. Therefore, while the results of these tools is **different**, they are both more than sufficient for the task at hand.

With regards to precision, the rate limiting factor is the  DICOM tag "image position patient" which is typically only reported with three decimals of precision, e.g.

`  (0020,0032) DS [-205.600\-188.000\-4.250]               #  24, 3 ImagePositionPatient
`
This value is used to transform the vectors from scanner space to image space.

**Comment by CarolineBeese** [comment]
Thank you so much for the immediate and precise response!
