### ISSUE TITLE
Effective Echo Spacing on old Siemens

### ISSUE THREAD

**Issue by orchid666** [rordenlab/dcm2niix#315]
Hello Chris, 

a little follow up on our old siemens data, I noticed that the 'EffectiveEchoSpacing' tag is missing in the json file on data from our Allegra, although it is present fr our prisma data. 
Is it possible to calculate  it with the olde header version?

Thanks a lot.

**Comment by neurolabusc** [comment]
I briefly looked into this. Both dcm2niix and d[dicm2nii](https://github.com/xiangruili/dicm2nii) use BandwidthPerPixelPhaseEncode to determine BandwidthPerPixelPhaseEncode. However, if this is not available, dicm2nii will use SliceMeasurementDuration from the ASCII portion of the CSA header. This tag is available in older scanners. However, I am not convinced this is a reliable solution. For example, (this image)[https://github.com/neurolabusc/dcm_qa/tree/master/In/TotalReadoutTime/PF_PAT_POS_PFOV_PEres_INTERP_test2/NOPF_NOPAT_NOPOS_PERES100_ES1P00_BW2222_AP_0024) reports a SliceMeasurementDuration of 9000.00000000 where we would expect it to be 90. I suspect Siemens uses some flags to denote the units for this tag, but since this is a private field we do not know how to decode this. I would rather not report items than provide data that I know is sometime erroneous. Perhaps your Siemens Research Collaboration Manager can help you reliably decode this - if you find a robust solution please reopen this issue.

Regardless, the EffectiveEchoSpacing and TotalReadoutTime tags only influence the scaling of the calibrated images. As long as you have sequences where the values are identical between your phase encoding directions, this parameter has no impact on the images you will use for subsequent processing.
