### ISSUE TITLE
Code Style

### ISSUE THREAD

**Issue by ASVBPREAUBV** [rordenlab/dcm2niix#318]
I have been working on a little feature (writing the gantry-tilt-offset values to the JSON) over the last days. My IDE (CLion) keeps messing up the styling. Do you follow a code-style? Sorry for the question, im new to c++

**Comment by neurolabusc** [comment]
There is no formal code style. Much of the code was written by me, so it is fairly consistent. However, some sections have been written by others and I retain their style as these are likely the people who will maintain and extend these portions of code. What feels familiar to them is a good idea. In general, I try to stick with C rather than C++. This looks more explicit to me and tends to reduce the dependency and compiling across systems.

In general, I would discourage a pull request that reformats the style, as it makes it hard to see the specific changes and may make code less familiar to the developers who maintain and extend the code.

**Comment by ASVBPREAUBV** [comment]
Thanks for the fast reply. Will create no pull request with formated files.
Do you have plans to move to a certain style system?

**Comment by neurolabusc** [comment]
No plan to change style. I prefer to keep the code familiar to the original authors, who are likely to be the ones to maintain/extend the functions they created.
