### ISSUE TITLE
make -v report version so it is easy to compare to the ConversionSoftwareVersion value in sidecar

### ISSUE THREAD

**Issue by yarikoptic** [rordenlab/dcm2niix#326]
ATM (well, a few releases back but I do not think it has changed)
```shell
$ git grep -h ConversionSoftwareVersion | sort | uniq        
  "ConversionSoftwareVersion": "v1.0.20190410  (JP2:OpenJPEG) GCC6.3.0"
```
but `dcm2niix -v` is too verbose and this version is embedded within a line making it hard to impossible to compare robustly within a shell script:
```shell
$ dcm2niix -v                                         
Chris Rorden's dcm2niiX version v1.0.20190410  (JP2:OpenJPEG) GCC6.3.0 (64-bit Linux)
v1.0.20190410
```

may be, if really all pieces are needed, it could become something like 

```shell
v1.0.20190410
Build: v1.0.20190410  (JP2:OpenJPEG) GCC6.3.0 (64-bit Linux)
Author: Chris Rorden
```
and ConversionSoftwareVersion adjusted to include the `(64-bit Linux)` which is imho is also good to know.
Or if sacrifices to be made, could be just 
```
v1.0.20190410  (JP2:OpenJPEG) GCC6.3.0 (64-bit Linux)
```

Also I just mentioned that `-h` output is not exhaustive for `-v` I guess:
```
$> dcm2niix -h | grep -e -v
  -v : verbose (n/y or 0/1/2 [no, yes, logorrheic], default 0)
```

**Comment by neurolabusc** [comment]
I would use the following command to get the version number (e.g. v1.0.20190808), which is the second line when you run the version argument:

```
 >dcm2niix -v | sed -n 2p
v1.0.20190808
```

The first line is always generated regardless of what arguments are provided. This is useful for bug reporting. It has been around since the origin of the software and since other tools may use it I would be reluctant to change it. It reveals if the software was compiled to support rare transfer syntaxes (JP2 = JPEG2000) (JP-LS: JPEG-LS, a lossless variant not to be confused with the more common JPEG-lossless), the compiler used and the operating system. 

I agree that the `dcm2niix -v`  is not documented, and is confusing as `-v` is also used to control verbosity, e.g. `dcm2niix -v ~/dcm`.  What do you think about adding the argument `--version`, this could be added and documented along with the Slicer compatible `--xml` and `--progress` arguments once @lassoan signs off on it.

**Comment by yarikoptic** [comment]
I would like to match not just a version but a type of build (eg version wouldn't change access Debian package revisions if I change build options) since you thought it is important to include within ConversionSoftwareVersion ;-)

Adding --version sounds good, that is what we have in our tools and expect from others ;-)

**Comment by neurolabusc** [comment]
With regards to the BIDS JSON file, if that file is created it indicates that the Transfer Syntax was supported. Since the BIDS file is generated on successful conversion, the additional fields, e.g. `(JP2:OpenJPEG) (JP-LS:CharLS) Clang10.0.1 (64-bit MacOS)` are superfluous. I think the primary version number is all you have to extract (e.g. `v1.0.20190808`)

**Comment by neurolabusc** [comment]
Latest commit should address this issue.

- New `--version` argument
- BIDS field now only reports version number, not feature. E.G. `"ConversionSoftwareVersion": "v1.0.20190808`
 - An unrelated but important change is that the `-n` argument now reports and expects the CRC of the Series UID, not the series number. This allows it to discriminate between different studies that share the same series number.

If you are happy with this, please close this issue.

**Comment by yarikoptic** [comment]
> Since the BIDS file is generated on successful conversion, the additional fields, e.g. `(JP2:OpenJPEG) (JP-LS:CharLS) Clang10.0.1 (64-bit MacOS)` are superfluous

hm... in principle -- yeah, assuming that "the others are always right and I am also doing it correctly always" ;) i.e. in principle every of those details might matter, but hey -- it is turtles all the way down...
I will try running a build of neurodebian pkg of dcm2niix (which runs its tests at build time) on s390 tomorrow.
But in general I agree -- version should in general be enough (especially for my  particular use case) and definitely better than no version ;)

**Comment by yarikoptic** [comment]
ok, for s390 a separate report is coming.  I guess since only "Version" is promised to be recorded in the side car file indeed could close this one
