### ISSUE TITLE
ENH: Choco windows packages

### ISSUE THREAD

**Issue by muschellij2** [rordenlab/dcm2niix#331]
Would it be possible to bundle the releases into a choco package:
https://chocolatey.org/docs/create-packages ?
Then on things like appveyor, you can run `choco install dcm2niix`.  I'm not sure how much work it is, but may be useful.  But, like you, I don't have a Windows machine to do this.

**Comment by neurolabusc** [comment]
I am not familiar with chocolatey, if anyone wants to submit a pull request to support this, I would take a look. I do have two comments. First, chocolatey is not open source though it is free. This is not a huge issue (Github is similar), but not ideal. Second, I am not sure how much maintenance would be required to support chocolatey. At the moment, AppVeyor and Travis automatically build a MacOS, Windows and Linux compilation with each commit.

An alternative is to use [glare](https://github.com/Contextualist/glare). Since curl is common in Unix and provided with Windows 10 (1803 and later), one can download the latest stable release for each OS with one line:

```
curl -fLO https://glare.now.sh/rordenlab/dcm2niix/win.zip
curl -fLO https://glare.now.sh/rordenlab/dcm2niix/lnx.zip
curl -fLO https://glare.now.sh/rordenlab/dcm2niix/mac.zip
```

The one issue is if the glare website gets hacked, and redirects to a malicious download. While unlikely, the Unix code below ensures that the latest stable release download comes from the legitimate GitHub site (MacOS in this example):

```
redir=`curl https://glare.now.sh/rordenlab/dcm2niix/mac.zip`
url=$(echo $redir |  grep -o '"https://github.com/rordenlab.*.zip"')
url=$(echo $url |  grep -o 'https://github.com/rordenlab.*.zip')
curl -fLO $url
```

I would think this could be ported to support Windows for an easy command line or batch shell for installing the latest stable build.

**Comment by neurolabusc** [comment]
As noted, with Windows 10 (1803 and later) you should be able to download the latest stable release with
```
curl -fLO https://glare.now.sh/rordenlab/dcm2niix/win.zip
```

To be extra careful, you could verify that the file is downloaded from GitHub. Here is a Windows port for the Unix command I gave in the first section:

```
@ECHO off
SETLOCAL EnableDelayedExpansion
FOR /F "tokens=*" %%g IN ('curl -s https://glare.now.sh/rordenlab/dcm2niix/win.zip') DO (SET redir="%%g")
FOR /F delims^=^"^ tokens^=2 %%a IN (%redir%) DO (
    SET url=%%a
	IF "!url:~0,37!"=="https://github.com/rordenlab/dcm2niix" (
		curl -o win.zip -fLOs !url! 
	)
)
```

**Comment by neurolabusc** [comment]
Thanks to @ningfei, the latest stable compiled release can be installed for Linux, MacOS and Windows with the following commands:

```
curl -fLO https://github.com/rordenlab/dcm2niix/releases/latest/download/dcm2niix_lnx.zip
curl -fLO https://github.com/rordenlab/dcm2niix/releases/latest/download/dcm2niix_mac.zip
curl -fLO https://github.com/rordenlab/dcm2niix/releases/latest/download/dcm2niix_win.zip
```

These are the versions created by Travis/AppVeyor, with the Travis version validated for regressions. The one caveat is that the Linux compilation requires a relatively recent version of Linux. Users with old Linux distributions may want to want to get the compiled dcm2niix included with [MRIcroGL](https://github.com/rordenlab/MRIcroGL12/releases) which is [compiled with Holy Build Box](https://github.com/phusion/holy-build-box) for backward compatibility.
