### ISSUE TITLE
pigz number of cores

### ISSUE THREAD

**Issue by muschellij2** [rordenlab/dcm2niix#340]
Using dcm2niix on cluster.  When using `pigz` for compression, is it possible to pass `-p 1` or some other number of processes to `pigz` (causing threading errors).

**Comment by muschellij2** [comment]
Seems as though https://github.com/rordenlab/dcm2niix/blob/7ce33ca5fa3bb2dd4e5410bd97bcf515c9e462d9/console/nii_dicom_batch.cpp
could add in an options here:
```
sprintf(newstr, "\"%s -n -f -%d \"", blockSize, opts.gzLevel);
```
I guess the problem is really with `pigz`, but have been running into this on our new cluster setup.

**Comment by neurolabusc** [comment]
If you do not want parallel compression, you should select the `-z i` option which uses the internal serial compressor. Assuming you have compiled dcm2niix using the CloudFlare zlib this will be about twice as fast as running pigz using only a single thread. If you have compiled with traditional zlib or miniz, the internal compressor provides just slightly better performance than running single threaded pigz. Therefore, there is no option for running pigz in single threaded mode as it provides no benefit over the internal compressor.

As an aside, for Unix systems (MacOS and Linux) running a modern version of pigz (2.3.4 or later) and where parallel compression is viable, you should select `-z o` for 'optimal' compression performance. This will run pigz using piped-memory mode, which is typically far faster on clusters where disk I/O is slow. Launching pigz with `-z y` will first save the uncompressed data to disk, next pigz is launched to read the uncompressed file and generate a compressed file. In contrast, `-z o` writes the compressed data directly.

**Comment by neurolabusc** [comment]
1. This issue is related to notes regarding parallel compression using [Dcm2Bids](https://github.com/cbedetti/Dcm2Bids/issues/61).

2. I do not have a computer that has experienced this, but users of large clusters should be aware that pigz has an open issue with some [Linux distributions](https://github.com/madler/pigz/issues/68). The linked issues describe developmental versions of pigz as well as glibc updates to mitigate this issue.

**Comment by muschellij2** [comment]
Thanks - I ended up switching to the internal zipping for now, but I
figured I'd bring it to your attention.
Best,
John

**Comment by neurolabusc** [comment]
@muschellij2 - since your cluster exhibited issues with pigz, I would be grateful if you could test this accelerated version of [pigz](https://github.com/neurolabusc/pigz). This uses the [CloudFlare](https://github.com/cloudflare/zlib) lib that improves the performance of pigz by about 40%. 

```
git clone https://github.com/neurolabusc/pigz.git
cd pigz
mkdir build && cd build
```

I suspect your issue is that you were using a version of pigz that was compiled with an [old version of glibc](https://github.com/madler/pigz/issues/68). Therefore, I would suggest upgrading the glibc on your cluster before building a custom version of pigz using the updated library. It may still be polite to restrict the number of cores used by dcm2niix (e.g. use `-z i` to use a single thread rather than `-z o` to use piped parallel pigz) on a cluster, but it would be useful to know that the threading issue has been addressed (with the added bonus of having an extra fast version of pigz).
