### ISSUE TITLE
Renaming Feature: Disable postfix

### ISSUE THREAD

**Issue by halfSpinDoctor** [rordenlab/dcm2niix#344]
Can a flag be added to disable the post-fix added to multi-echo (e.g. _e2, _e3) or phase (_ph) images, when using the DICOM rename feature (-r y)?

I have multi-echo data where each echo gets it's own instance number (%r), and thus the suffix is not needed to prevent collisions. I currently need extra bash scripting in my workflow so that all of the images end up with a *.dcm suffix, which is required by the subsequent software I am using.

Thanks in advance!

**Comment by neurolabusc** [comment]
@halfSpinDoctor can you test the latest developmental version. It includes a new option `--terse` that will omit most naming post-fixes. It is also enabled automatically if the user includes `%o` (mediaObjectInstanceUID, 0002,0003) in the output filename. 

This feature can unleash **widespread opportunities for unintended consequences**. Most users think that an instance number (`%r` 0020,0013) is unique for a given series (0020,0011) and acquisition (0020,0012). However, this is not required by the DICOM standard. An excellent example of this is the Siemens field maps which use the same instance number for each echo. In my experience, this is the [leading cause of image loss](https://neurostars.org/t/field-mapping-siemens-scanners-dcm2niix-output-2-bids/2075/8) for Siemens users who are not on the XA platform. Many archival tools assume instance numbers are unique, leading to overwriting images. I provide an [example](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Unusual_MRI) field map from a Siemens Prisma running E11C that exhibits this feature (and it has been around since at least the B series). Therefore, running  `dcm2niix -r y -f %t/%s_%p/%4r.dcm --terse  ~/DICOM` will overwrite half of these images. For Siemens users, one should avoid terse output or include `%o` in the filename `./dcm2niix -r y -f %t/%s_%p/%4r_%o.dcm ~/DICOM`

**Comment by halfSpinDoctor** [comment]
Thank you for adding this, I appreciate it. I do understand why it is dangerous to have this option. (I also understand that DICOM renaming is *not* intended as primary functionality for the project).

I have also observed some instances where phase (_ph) is flagged for images that are actually magnitude (for example, fat/water series with InPhase and OutPhase images), so I think the usefulness of the feature outweighs the potential for unintended consequences.
