### ISSUE TITLE
Documentation clarification: handling of series with missing slices

### ISSUE THREAD

**Issue by fedorov** [rordenlab/dcm2niix#349]
https://github.com/rordenlab/dcm2niix/blob/master/FILENAMING.md#file-name-post-fixes-image-disambiguation says that "_Eq is specific to CT scans".

It appears that reconstructions with the `_Eq_<number>` suffix are generated whenever there are missing slices in the series - I am getting those while converting MR data.

Would it make sense to amend the documentation clause above to clarify this?

**Comment by neurolabusc** [comment]
I have updated the documentation. As you note, when an _Eq is generated for a MR sequence it often denotes that slices have been lost. In my experience, the most common problem is Siemens multi-echo sequences (e.g. [fieldmaps](https://neurostars.org/t/field-mapping-siemens-scanners-dcm2niix-output-2-bids/2075/7)) where all the echos share the same instance number. Many archiving and PACS tools assume that instance number is unique for a series, but the DICOM standard does not require this. Therefore, while the Siemens scans are technically valid DICOM images, many tools randomly discard half the slices from a 2 echo sequence thinking that they are identical images. This yields two partial volumes rather than two complete volumes. 

For teams wanting to check their archiving and PACS tools, the [dcm_qa_me](https://github.com/neurolabusc/dcm_qa_me) repository includes samples of these troublesome DICOMs. I have lobbied my research collaboration manager for years to address this common source of data loss. I urge other users to do the same so that this problem can be fixed at the source.

**Comment by fedorov** [comment]
@neurolabusc thank you for the update!

>  In my experience, the most common problem is Siemens multi-echo sequences 

In my case, I am 99.999% confident this has nothing to do with the scanner. The data has to pass multiple stages (and hands!) before it gets to me for pre-processing, and most likely some slices were simply lost somewhere. 

Without going into details - it's not just that DICOM is not perfect, and implementations of DICOM are not perfect, but there are many other software tools involved in the process, and humans are not perfect either .... :-\

**Comment by neurolabusc** [comment]
Agreed. The emergence of enhanced DICOM where an entire series is saved as a single file should minimize these issues in the future.
