### ISSUE TITLE
mistake in treating multi-echo data

### ISSUE THREAD

**Issue by lcnature** [rordenlab/dcm2niix#350]
Hello, I am using the version v1.0.20181125 of dcm2niix_afni. But I think my colleague using dm2niix found the same issue. Basically for multi-echo data, the program almost always create one nifti for images at one echo time without the _e? suffix in name. If I look into the json, this file also does not 'EchoNumber' parameter. It is as if the program treats the image with that TE as a separate run. But the nifti for all other echo times are good (file names end with the right suffix and they do have the 'EchoNumber' parameter.) The echo time which has this mistake seems quite random across runs. Single-band reference images seem to not have this problem.
The data are generated by Siemens scanner.

**Comment by neurolabusc** [comment]
Can I suggest you get the latest [release](https://github.com/rordenlab/dcm2niix/releases) (v1.0.20190902). I think you will find it provides consistent naming - labeling all echoes except the first one. The first echo is implicitly assumed unless reported otherwise. You can find validation datasets (also from a Siemens scanner) [here](https://github.com/neurolabusc/dcm_qa_me).

The file naming is described [here](https://github.com/rordenlab/dcm2niix/blob/master/FILENAMING.md), the post-fix '_e' will be reported if the echo number tag (from 0018,0086) is greater than 1. Therefore, with most sequences that have a single echo you file have 'filename.nii', while for a sequence with two echoes you will have 'filename.nii' and 'filename_e2.nii'. Likewise, the echo number in the BIDS file is assumed to be one unless explicitly reported. If you want to make the first echo explicit, just add a `%e` to file filename tag, e.g. `-f %s_%p_%e` will generate a filename like `2_mprage_1`.
