### ISSUE TITLE
Which slides were used to reconstruct a volume?

### ISSUE THREAD

**Issue by jbschiratti** [rordenlab/dcm2niix#351]
I am using `dcm2niix` to convert a series of `.dcm` files in a given folder. My script just does:

```dcm2niix -o /tmp/subj/ ~/data/subj/```

and the output of `dcm2niix` is: 

```Chris Rorden's dcm2niiX version v1.0.20190902 (JP2:OpenJPEG) (JP-LS:CharLS) GCC5.4.0 (64-bit Linux)\nFound 437 DICOM file(s)\nConvert 436 DICOM as /tmp/subj/subj_TAP_3TPS_SURESTART_SOUST_IOD_MAP_20190607000000_7d (512x512x436x1)\nConvert 1 DICOM as /tmp/subj/subj_TAP_3TPS_SURESTART_SOUST_IOD_MAP_20190607000000_7e (832x832x1x1)\nWarning: Check that 2D images are not mirrored.\nConversion required 1.128395 seconds (1.117060 for core code)```

Clearly, there was a problem with one slice which contains data with shape 832 x 832 whereas all the other slices contain data with shape 512 x 512. My question is the following one: how can I obtain a list of the slices which were used to reconstruct the 512 x 512 x 436 x 1 volume?

**Comment by neurolabusc** [comment]
The easiest thing would be to sort your DICOMs by file size. The one with more pixels will be a lot larger.

DICOM files often have file names that make it hard to infer their order. I would suggest renaming (`-r y`) all of your DICOMs is such a way that you can dissociate the different properties. Personally, I like naming based on Study Time/Date (%t), series number (%s), protocol name (%p) and instance number (%r) is useful. Since DICOM does not require that instance number is unique, it might be wise to add the unique mediaObjectInstanceUID (%o) to prevent file name clashes...
 `dcm2niix -r y -f %t/%s_%p/%4r_%o.dcm  ~/data/subj/`

Finally, you could always run dcm2niix in logorrheic mode (`-v 2`) - while this will provide you with the information you need, the tremendous amount of output provided is over kill for your purposes and parsing the output will be a challenge.
