### ISSUE TITLE
Warning: Some images had bval>0 but bvec=0

### ISSUE THREAD

**Issue by PichardRarker** [rordenlab/dcm2niix#356]
dcm2niix version: v1.0.20190902  GCC5.4.0 (64-bit Linux)
Scanner make/model: GE DISCOVERY_MR750
Sequence: Single-shell dMRI, 32 directions (b=1000), 1 bzero

Hi Chris,

dcm2niix is giving me the following when I try to convert my DICOM series:

> Warning: Some images had bval>0 but bvec=0 (either Trace or b=0, see issue 245)

I've had a look through the DICOM tags, and the above doesn't seem to be the case. By ordering the dicoms by InstanceNumber, you can see that there's one bzero at the start of the sequence with zeros for all bvec values, whereas all other slices have bvecs with at least one non-zero component. I've attached a spreadsheet of ordered DICOM info, in case it's useful. 

Any idea what could be causing this discrepency? I'm using tags (0019; 10BB), (0019; 10BC) and (0019; 10BD) for the bvecs, and tag (0043; 1039) for the bvalue. My data also includes bvalue-related tag (0043;1030), but it seems to convey the same information as tag (0043; 1039).

Best,

Rich 

[GE_DWI_DCM.txt](https://github.com/rordenlab/dcm2niix/files/3847257/GE_DWI_DCM.txt)

**Comment by neurolabusc** [comment]
Curious. If you can send me a sample dataset (email box, dropbox or googleDrive link to the email listed in my avatar) I can provide feedback.

**Comment by PichardRarker** [comment]
Alas, I cannot. It's clinical trial data, and I'm not allowed to share it. 

Given that I can in fact see bvals and bvecs that look sensible, I suppose there's nothing stopping me just creating my own .bval and .bvec files directly from the DICOMs? Is there any other processing I would need to apply to the bvecs to make them fully compliant with the typical dcm2niix output for GE data?

Best,

Rich

**Comment by neurolabusc** [comment]
See the [GE](https://github.com/rordenlab/dcm2niix/tree/master/GE) page for details. Be aware that  GE gradients are in “MR physics” logical coordinate, i.e Freq (X), Phase (Y), Slice (Z). In contrast, FSL expects this in image space, with some unusual caveats described [here](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FDT/FAQ#What_conventions_do_the_bvecs_use.3F) and [here](http://justinblaber.org/brief-introduction-to-dwmri/). Therefore, the transform is not obvious, in particular if images are not acquired orthogonal to the scanner bore. Since you can not share your data, you might want to fork dcm2niix to handle your images and then commit a pull request if you want to share your improvements. If you have Matlab, you might also want to see if [dicm2nii](https://github.com/xiangruili/dicm2nii) handles your images.
