### ISSUE TITLE
Feature Request: Override automatic appending of `_e%e`for single-file mode

### ISSUE THREAD

**Issue by jbteves** [rordenlab/dcm2niix#358]
When converting only one volume at one echo, multi-echo data is still tagged with an echo number at the end.

**Comment by neurolabusc** [comment]
Does the [`--terse`](https://github.com/rordenlab/dcm2niix/blob/development/FILENAMING.md) argument provided in the developmental branch address this?

**Comment by jbteves** [comment]
Yes, that works! Will this ever be merged into `master`?

**Comment by neurolabusc** [comment]
Yes, the development branch is for beta testing the next stable release. Stable releases are generally twice per year, but since the BSD license is used you can always distribute the development branch with your software. All development builds are tested against the dcm_qa datasets for regressions, but there is always an opportunity for unintended consequences.
