### ISSUE TITLE
DTI output 3D NifTi

### ISSUE THREAD

**Issue by rachel-sunrui** [rordenlab/dcm2niix#379]
Hi Chris, 

I am working with Siemens Verio DTI data, and I am having trouble correctly convert the DICOM files to NifiTi.

I have 1000 dicom files. At the beginning, I used dcm2niix mydicomfolder/ and I could get the .bvals files with 33 values in it. However, when I checked the .nii file, I noticed it is a 3D image of dimension 128*128*1000. I lost the (0019,xxxx) and (0029, xxxx) header in the anonymization process and I suspected that could be the reason. So I asked my clinical collaborators to send me a version with the private headers intact. 

This time, with the new files, I could not get the .bval file, and the output .nii is still a 3D image. Here is the output message:
**********
Chris Rorden's dcm2niiX version v1.0.20171215 (OpenJPEG build) GCC7.3.0 (64-bit Linux)
Found 49 DICOM image(s)
slices stacked despite varying acquisition numbers (if this is not desired please recompile)
Dims 128 128 49 1 1
Warning: Interslice distance varies in this volume (incompatible with NIfTI format).
 Distance from first slice:
dx=[0 5.2 10.4 15.6 20.8 26 31.2 36.4 41.6 46.8 52 57.2 62.4 67.6 72.8 78 83.2 88.4 93.6 98.8 104 109.2 114.4 119.6 124.8 130 135.2 140.4 145.6 150.8 5.2 10.4 15.6 20.8 26 31.2 36.4 46.8 57.2 67.6 78 88.4 98.8 109.2 119.6 130 140.4 145.6 150.8]
Convert 49 DICOM as test_write_header/test_write_header_DIFFUSION_DTI_20180617141649_14a (128x128x49x1)
Conversion required 0.465110 seconds (0.208618 for core code).
**********

I later noticed that the VR of the (0019, xxxx) and (0029, xxxx) tags were UN. So I changed the tags' VR using 'pydicom', rewrote the DICOM files and double checked the datatypes of the tags are corresponding to their VR, but the outcome of dcm2niix remained the same as above.

Have you seen similar issues? Could you please give me some suggestion regarding where the problem could be? I would really appreciated it. Thank you.

Best regards,
Rachel

**Comment by neurolabusc** [comment]
First step if you encounter issues would be to upgrade to the [latest release (v1.0.20190902)](  https://github.com/rordenlab/dcm2niix/releases). For Linux you can download the latest version with the command:

```
  curl -fLO https://github.com/rordenlab/dcm2niix/releases/latest/download/dcm2niix_lnx.zip
```

Second, I would see if you can get the data from the console, before it has been modified by the anonymization script. I suspect your DICOMs have been mangled.

You say that you have 1000 files, yet dcm2niix only identifies 49 images. So one wonders if all the images are in the folder you are converting or if some of the images have been damaged. You can always use the verbose modes (`-v 1` and `-v 2`) to git insight into the files dcm2niix is reading. If it is excluding files, you may want to [verify them](https://www.dclunie.com/dicom3tools/dciodvfy.html) or use [dcmdump](https://support.dcmtk.org/docs/dcmdump.html) or [gdcmdump](http://gdcm.sourceforge.net/html/gdcmdump.html). Different vendors use DTI tags [differently](https://www.na-mic.org/wiki/NAMIC_Wiki:DTI:DICOM_for_DWI_and_DTI) so I would make sure your anonymization process has not stripped out the vendor details. Since you mention your data is from Siemens, it is crucial that the anonymization did not remove the [CSA header](https://github.com/rordenlab/dcm2niix/issues/348). Without this your data will lack vital properties inclding:

```
SliceNormalVector
DiffusionGradientDirection
SliceMeasurementDuration
BandwidthPerPixelPhaseEncode
NumberOfImagesInMosaic
PhaseEncodingDirectionPositive
SliceTiming

```

**Comment by rachel-sunrui** [comment]
Hi Chris,

Thank you for your prompt response. Unfortunately, I do not have access of the raw files. What I am trying to do is figure out what went wrong in the anonymization process so that I can suggest my clinical collaborators the correct way to anonymization. I checked I have all the private tags, including (0x0019,xxxx), (0x0029, xxxx), (0x0051, xxxx) in the DICOM

Thank you for your previous suggestions on checking on corrupted files, now the output is

Chris Rorden's dcm2niiX version v1.0.20190902  (JP2:OpenJPEG) (JP-LS:CharLS) GCC5.5.0 (64-bit Linux)
Found 1000 DICOM file(s)
Slice positions repeated, but number of slices (1000) not divisible by number of repeats (33): missing images?
Warning: Interslice distance varies in this volume (incompatible with NIfTI format).
Unable to equalize slice distances: slice order not consistently ascending.
First spatial position repeated 33 times
Error:  Recompiling with '-DmyInstanceNumberOrderIsNotSpatial' might help.

And I counted Distance from first slice output by dcm2niix, they are like this:

num of slices shared the same value---------Distance from first slice 
33--------0
34--------5.20000000000000
33--------10.4000000000000
34--------15.6000000000000
33--------20.8000000000000
34--------26
33--------31.2000000000000
34--------36.4000000000000
33--------41.6000000000000
34--------46.8000000000000
33--------52
34--------57.2000000000000
33--------62.4000000000000
34--------67.6000000000000
33--------72.8000000000000
34--------78
33--------83.2000000000000
34--------88.4000000000000
33--------93.6000000000000
34--------98.8000000000000
33--------104
33--------109.200000000000
33--------114.400000000000
33--------119.600000000000
33--------124.800000000000
33--------130
33--------135.200000000000
33--------140.400000000000
33--------145.600000000000
33--------150.800000000000 

I checked with my collaborators, and they said the 1000 DICOM files are what the PACS system gave them. My questions are:
1) Will *Recompiling with '-DmyInstanceNumberOrderIsNotSpatial'* work in this case? What does that mean?
2) Does this indicate something go wrong when exporting from PACS?
2) Is there anyway to work around this? For instance, deleting the some files to make the total DICOM files to be 33*30?

Do you have any other ideas regarding what might go wrong? Thank you.

Best regards,
Rui

**Comment by neurolabusc** [comment]
Rui-

It looks like some images were not converted. Assuming 34 slices with 30 slices per volume, there should be 1020 images, yet you only have 1000 slices. I think the number 1000 is suspicious, as I recall several GE systems limit folders to have a maximum of 1000 DICOM images, and therefore a DICOM series with 1020 slices would be saved to multiple folders, e.g. '~/DCM/A', '~/DCM/B'. If this were the case, you could convert all your data by providing the root/parent folder (`dcm2niix ~/DCM`).

This is a limitation of your images, not my software. If you provide an incomplete set, there is not going to be a great solution. Even if you can exclude the last few volumes, you may not have even sampling of your gradient directions and amplitudes. As a desperate attempt to salvage something from this data you could attempt to rename the DICOMs based on instance number:

```
dcm2niix_stable -f %t/%s_%p/%4r.dcm -r y ~/Neuro/issuex/
```

This will create a copy of your DICOM images with the name based on the instance number, since you hope to have 33 intact volumes each with 30 slices (=990 2D images), you may be able to discard the images excess volumes. For example, if the renaming created 0001.dcm...1000.dcm, you would discard slices 0991.dcm..1000.dcm and convert the remaining volumes. While instance numbers are typically useful, be aware that the DICOM standard does not require them to be sequential or even unique, so this may not work.

For future acquisitions, I would strongly suggest selecting the "Mosaic" checkbox on the MRI console's "Diffusion" tab for this sequence. This will store all slices from a volume in a single file, resulting in 30 times fewer files. Since DICOM headers are large, this will save disk space, will be faster and will avoid overwhelming the number of files in a folder. I would encourage using mosaics for all EPI scans (DWI, fMRI, resting state) for all Siemens VA-VE generation scanners (Verio, Trio, Prisma, etc). The only exception is the XA generation (Vida), which create enhanced DICOMs - one should [never](https://github.com/rordenlab/dcm2niix/issues/236) use mosaic mode on a Vida.

**Comment by rachel-sunrui** [comment]
I see. I will double check again if I can get the remaining files. Thank you for your help.
