### ISSUE TITLE
unable to read DICOM data with Transfer Syntax UID 1.2.840.10008.1.2.4.90 even after compiling with OpenJPEG

### ISSUE THREAD

**Issue by sandeepganji** [rordenlab/dcm2niix#399]
Hi,
I have a DICOM data that has Transfer Syntax UID=1.2.840.10008.1.2.4.90. The data is on a Windows Server 2016, and can't be taken out of it due to IT policie. The pre-compiled dcm2niix (v1.0.20200331) is unable to read it. Then I followed the steps in https://github.com/rordenlab/dcm2niix/blob/master/COMPILE.md.
-Obtained the dcm2niix source code
-Cmake software
-configured on the cmake and generated the VStudio solutions
-Solutions built's properly with VStudio 2019 (both debug and release).

However when I tried them on to convert the DICOM it works properly for the Transfer Syntax UID = 
1.2.840.10008.1.2.4.80 but it still doesn't work for 1.2.840.10008.1.2.4.90.

![01](https://user-images.githubusercontent.com/12124746/81509266-f2a46600-92ce-11ea-9c70-9331031326c2.JPG)

Any suggestions? Or Chris can you compile a version that can support Transfer Syntax UID 1.2.840.10008.1.2.4.90?

Thanks

**Comment by neurolabusc** [comment]
Without seeing a sample image, it is hard to diagnose (feel free to send a DropBox/Google drive link to the email in my avatar if you have an image that is suitably anonymized). The text 'JP2:OpenJPEG' suggests you have compiled to the [OpenJPEG library](https://en.wikipedia.org/wiki/OpenJPEG) that should support this JPEG-2000 transfer syntax used by the .90 transfer syntax. On the other hand, in order to support JPEG-LS, the executable should report `JP-LS:CharLS` which would suggest that it would use [CharLS](https://github.com/team-charls/charls) to support the .80 transfer syntax. So I would have expected this executable to handle .90 but report it needs a recompile to handle .80. I am also puzzled as why you created a 32-bit executable. The 64-bit version will leverage the additional CPU registers.

Can you try downloading [MRIcroGL](https://www.nitrc.org/projects/mricrogl) for Windows. That includes dcm2niix. If you choose the Import/ConvertDICOMtoNIfTI you will find it includes the latest stable release (1.0.20200331) compiled with both JPEG-2000 and JPEG-LS support built with MSC1900.

Here are my thoughts:

 1. Be aware that the DICOM standard only requires support for the uncompressed transfer syntaxes. Therefore, while an image using 1.2.840.10008.1.2.4.90 might be a valid DICOM, it may be incompatible with many DICOM tools. For this reason, I would always save DICOMs as uncompressed raw and if disk space is limited consider more general forms of compression (blosc+zstd, zstd, zip, gz, full drive compression). None of the lossless compressed formats used by DICOM are particularly efficient with regards to speed or file size (which probably explains why they were not widely adopted outside the field). 
 2. The DICOM JPEG compression methods JPEG Lossless (.57/.70), JPEG-LS Lossless (.80) and JPEG2000 Lossless (.90) are all completely unrelated to each other and also unrelated to the widely popular lossy JPEG (.50). Each needs their own compression/decompression library. None of the lossless JPEG methods became very popular outside of medical imaging. While promising, JPEG2000 did not gain much traction between the original classic lossy JPEG and [more modern formats](https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format). Only two open source JPEG2000 libraries were developed: OpenJPEG and Jasper. Jasper is known to have [issues](https://www.mccauslandcenter.sc.edu/crnl/tools/jpeg-formats) with 16-bit data used in medical imaging.

Therefore, I would suggest a simple solution of using [gdcmconv.html](http://gdcm.sourceforge.net/html/gdcmconv.html) to convert your images to uncompressed raw data (`gdcmconv -r`). If you have any issues, it would suggest a problem that is not specific to dcm2niix. The resulting images should be compatible with dcm2niix and other tools. I would check the provenance of your images - no vendor saves in this format. If you can avoid the step that created this transfer syntax you can ensure compatibility with a wide range of tools.

**Comment by sandeepganji** [comment]
Hi Chris,

Thanks for the information. I used the GDCM and was able to convert the DICOM from 1.2.840.10008.1.2.4.90 to 1.2.840.10008.1.2.4.80, after which I was able to use dcm2niix to convert DICOM to nifti.

As for the MRIcroGL, even with the latest [v1.0.20200331  (JP2:OpenJPEG) (JP-LS:CharLS) MSC1900 (64-bit Windows)] the conversion still crashes. I'm running my processing pipeline on Windows Server 2016, so can't use the MRIcroGL GUI, instead I used the command like [ C:\\Softwares\\MRIcroGL\\Resources\\dcm2niix.exe  -f "temp"  -z y   -o  dist_dir source_dir].
When I try to open the GUI I get the "unable to load opengl 3.3 core", but I think that is how my server is hosted on a VMware esxi server.

I have requested my radiologists to transfer data using a more standard methods (but that's easier said then done!)

Thanks again for the insight
-SG

**Comment by neurolabusc** [comment]
@sandeepganji I am glad this resolves your. issue. However, I remain puzzled that gdcmconv converts your source images while dcm2niix does not. Both use OpenJPEG to decompress this format. Further, on my Windows machine, dcm2niix happily converts transfer syntax 1.2.840.10008.1.2.4.90 - specifically [these examples](https://github.com/neurolabusc/dcm_qa/tree/master/In/Orientation/axmb/AxInt36mb). Can you test whether your can convert these two images on your system?

If possible, can you ask the radiologists if they have a phantom image (e.g. water bottle used to periodically test performance of magnet) that could be shared? I really have no insight into why dcm2niix fails in your system. By the way, you can also run dcm2niix with `-v 2` which produces very verbose output that sometimes helps identify issues. Alternatively, running gdcmdump and sharing the output after redacting private information (participant name, date of birth, etc.) might be helpful.

**Comment by tashrifbillah** [comment]
Hi @neurolabusc , I take it that you did not get the data to work on it further?

**Comment by neurolabusc** [comment]
@tashrifbillah never received an exemplar dataset. Unable to replicate. Feel free to send an exemplar to me, or provide a pull request that resolves the issue.

**Comment by tashrifbillah** [comment]
`gdcmconv` from https://github.com/rordenlab/dcm2niix/issues/399#issuecomment-626655714 solved the problem for our RAs. So I shall hold off on sending you any data for now.
