### ISSUE TITLE
Include EchoTime1 and EchoTime2 in .json file for Siemens fieldmap phase difference images 

### ISSUE THREAD

**Issue by evaalonsoortiz** [rordenlab/dcm2niix#400]
I would like to re-open issues #139 and #166. It seems that TE1 and TE2 can be found in the CSA header with the private DICOM tag (0029,1020). This is done here: [src/matlab/parse_siemens_shadow.m](url). Perhaps this can help for including the echo times in the .json file generated by dcm2niix for a phase difference image?

**Comment by neurolabusc** [comment]
Can you test the latest commit to the developmental branch (v1.0.20200521). I tested it using a single dataset from [dcm_qa_me](https://github.com/neurolabusc/dcm_qa_me). The BIDS fields [`EchoTime1` and `EchoTime2`](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html) are populated for Siemens Phase maps where the ASCII portion of the proprietary [CSA header](https://nipy.org/nibabel/dicom/siemens_csa.html) report alTE[0] and alTE[1] (as suggested by @mharms). These tags are only generated for phase images, not magnitude, real or imaginary images.

Caveats:
 1. As far as I can tell, there is no way of determine if a Siemens Phase map is from a single echo or a difference between two echos. Therefore, these tags will be generated both for phase difference images (desired) as well as multi-echo sequences where each phase image is saved.
 2. This information only exists in the ASCII portion of the CSA header, which is not only proprietary and generally undocumented, but has seen changes over the years. I do try to pull out the specific tags, but I do not know when they were introduced.

**Comment by evaalonsoortiz** [comment]
I tested it out with one of my phase difference datasets and obtained "EchoTime1" and "EchoTime2" fields. Thank you so much! Just a note: the nifti file has the suffix "_e2_ph". Is there a particular reason for keeping the "e2"?

**Comment by neurolabusc** [comment]
The _e2 reflects that [0018,0086](https://github.com/rordenlab/dcm2niix/blob/master/FILENAMING.md) reports this is the 2nd echo. Since we have no way of detecting that this is a difference image rather than a standard phase image, omitting the _e2 would have consequences for conventional multi-echo sequences where a user saved phase data. In brief, the _e2 reflects a property of the DICOM images. 

If you do not want post-fixes, run dcm2niix in the terse mode (`--terse`). In this mode, most post-fixes will be omitted. Beware that this mode can have name clashes, and different images from a series may over write each other.

**Comment by evaalonsoortiz** [comment]
Got it. Thanks again!
