### ISSUE TITLE
PET 4D data

### ISSUE THREAD

**Issue by andersenthomas** [rordenlab/dcm2niix#407]
Hi,

I'm working with a 4D PET dataset which have a variable frame length that I need to convert from the original DICOM files to either Nifti or nrrd (both should be fine). In the dcm2niix conversion to .nii dcm2niix gives a warning that "Seconds between volumes varies" which maybe is alright (I don't know if this kind of data structure is supported in the Nifti format?). Anyways, the conversion to nrrd gives the same warning but my understanding is that nrrd supports variable frame lengths? Is there no support for such a dataset?

**Comment by neurolabusc** [comment]
Hello, as you note the NIfTI standard provides a single value for pixdim[4], in other words there is a constant time between each 3D volume (XYZ) in a 4D time series (XYZT). This is typical in MRI, where changing the time between volumes (TR) would change the image contract (overall signal, T1 and T2 are all impacted by TR). I am really not sure what the convention is to store variable volume timing in the [NRRD format](http://teem.sourceforge.net/nrrd/format.html#basic). Situations like physiologically triggered images (e.g. to phase lock images with cardiac or respiratory cycle) certainly do have variable timing between volumes, and some [Slicer3D examples](https://www.slicer.org/wiki/Documentation/4.4/Modules/MultiVolumeExplorer) use the convention `MultiVolume.FrameLabels:=0.0,4270.0,8541.0,...` but I am not sure this is supported. In brief, since I have never seen images with variable timing, and since I do not know the NRRD convention, I am not sure how to proceed.

@fedorov as a world expert in NRRD and DICOM, do you know of tools that will preserve variable volume timing? What is the convention for storing this information?

**Comment by andersenthomas** [comment]
Thanks for the response @neurolabusc. I guess another approach would be to store such information regarding variable frame length would be in a BIDS sidecar which is already supported in dcm2niix. BIDS both have support for a "FrameTimesStart" and "FrameDuration" which contains lists with said information. Could that be viable, i.e. keeping the 4D nifti as-is but storing the information in the .json sidecar?

**Comment by fedorov** [comment]
> some Slicer3D examples use the convention `MultiVolume.FrameLabels:=0.0,4270.0,8541.0,...`

This convention is Slicer-specific. This is just using the ability of NRRD header to include arbitrary key-value pairs, which are interpreted by the custom Slicer plugins. I would be quite surprised if this convention made its way to any other tool.

I am by no means a world expert in NRRD, or DICOM, for that matter - I just happen to know some corner topics a bit more than others. From what I know, legacy enhanced multi-frame PET DICOM has provisions to have non-regular 4th dimension via per-frame functional groups. DICOM has no requirement that the 4th dimension should be sampled regularly, but there are very few tools at the moment that can generate such legacy enhanced multi-frame PET object, and I don't know if there are tools to load and properly present to the user such object.

@andersenthomas if your dataset is publicly available, we could take a look at it sometime later, as we are working on tools to support encoding of legacy enhanced multi-frame MR/CT/PET objects.

**Comment by neurolabusc** [comment]
@andersenthomas as @fedorov noted, it would be great to have a public sample available (either a phantom or de-identified human). If you do not want to make it public, but are willing to send the file to me, you share it with me via DropBox or GoogleDrive (my email is in my avatar). Another option would be for you to create a fork of dcm2niix and extend it to support your data. Once you are happy with your solution, you can generate a pull request if you wish to contribute your enhancements with the root repository.

**Comment by andersenthomas** [comment]
For now a wrote a small script which creates a BIDS sidecar with metadata and then continue to use dcm2niix for the image data itself. Not the prettiest solution but it should work for now.
I have an anonymized dataset which should fit the bill if you're willing to do a bit of work on this. I will make a shared link and send it to @neurolabusc. The files are .img but are full compliant DICOM exported directly from the scanner. Please note that the files are from a GE Signa PET/MRI. As far as I know there is not consensus between PET scanner manufacturers on which tag to use for frame length. GE uses ('0018,1242'), i.e. FrameTime, in the DICOM header but I think Siemens and Philips are using another. If you're interested I can provide a Siemens mMR dataset also which may be of use.

**Comment by neurolabusc** [comment]
Closing issue. Current developmental release supports [BEP009](https://docs.google.com/document/d/1mqMLnxVdLwZjDd4ZiWFqjEAmOmfcModA_R535v3eQs0/edit#heading=h.qdzsf8lh4for) to the full extent possible given my knowledge and exemplar DICOMs. Can reopen if anyone can suggest [limitations or improvements](https://github.com/bids-standard/bids-specification/issues/149) to my current efforts.
