### ISSUE TITLE
PhaseEncodingDirection to BIDS convention

### ISSUE THREAD

**Issue by dlevitas** [rordenlab/dcm2niix#412]
The `PhaseEncodingDirection` field in the spin echo field maps sidecar generated by dcm2niix can be either `i, j, k, i-, j-, k-`; however, in BIDS these directions would ideally need to be specified as `AP, PA, RL, LR, IS, SI`. I wanted to clarify if this is the correct conversion:

```
i == LR
i- == RL
j == PA
j- == AP
k == SI
k- == IS
```

Thanks,

Dan

**Comment by pvelasco** [comment]
`i`, `j` and `k` are the first, second and third indices of the image (i.e., dimension of the image). `LR`, `AP` and `IS` refer to the subject's anatomy. Depending on how you store the image in disk a given direction (e.g. `LR`) can correspond to any of the indices in the image.
The correspondence between them is given by the `qform` (or `sform`).
So there is no direct correspondence of the type `i` = `LR`, etc. It will always depend on the specific image.

**Comment by dlevitas** [comment]
Thanks @pvelasco I'll look into the header's `qform` then to determine that information.

**Comment by pvelasco** [comment]
In case it helps, in the past I have used `fslhd` like this:
If the phase encoding (PE) direction is `i`, do:
```
fslhd myImage.nii | grep sform_xorient
```
If the PE direction is `j` (or `k`), replace `sform_xorient` with `sform_yorient` (or `sform_zorient`). If the PE is negative, flip the direction.

**Comment by neurolabusc** [comment]
As @pvelasco notes, the BIDS [PhaseEncodingDirection](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#in-plane-spatial-encoding) refers to image space, not anatomical convention. This was chosen to match the expectations of the FSL tools. For axial scans, I,J refer to LR, AP; for coronal I,J are LR,SI and for sagittal scans I,J is AP,SI. As @pvelasco hints, the disk storage can also impact this. By default, DICOM images are stored with the first row at the top of the screen with higher rows further down (like an Excel spreadsheet). The NIfTI convention is for the first row to be at the bottom of the screen, with higher rows higher up (just like the way we draw the Y axis on a cartesian graph). 

Even more importantly, many users prefer to acquire oblique slices of the brain when acquiring "axial" fMRI and DTI scans, in order to improve coverage of the cerebellum with a limited number of slices. In these cases, the anatomical terms are not particularly accurate and can be misleading.

**Comment by pvelasco** [comment]
> however, in BIDS these directions would ideally need to be specified as `AP, PA, RL, LR, IS, SI`

The BIDS specification states (https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#in-plane-spatial-encoding):

> PhaseEncodingDirection: RECOMMENDED. Possible values: i, j, k, i-, j-, k-. The letters i, j, k correspond to the first, second and third axis of the data in the NIFTI file.

So, I'm not sure where @dlevitas got this information...

**Comment by dlevitas** [comment]
@pvelasco I'd been going off of [this portion of the BIDS spec](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#case-4-multiple-phase-encoded-directions-pepolar); however, I guess the `dir` label can be arbitrary.

**Comment by dlevitas** [comment]
Also related to the ReproIn protocol naming convention (https://github.com/nipy/heudiconv/blob/master/heudiconv/heuristics/reproin.py) for fmap `_dir-` labelling

**Comment by pvelasco** [comment]
> Also related to the ReproIn protocol naming convention (https://github.com/nipy/heudiconv/blob/master/heudiconv/heuristics/reproin.py) for fmap `_dir-` labelling

But that is their convention for the _Sequence naming on the scanner console_.
