### ISSUE TITLE
[Code 19] TOTAL_READOUT_TIME_MUST_DEFINE

### ISSUE THREAD

**Issue by theogeneserich** [rordenlab/dcm2niix#417]
Dear Chris,

I'm new to BIDS format and currently trying to prepare my data so that I can run fmriprep on them.
both dcm2bids and fmriprep were successfully installed and I successfully ran both with Dan (Levitas) [tutorial data](https://andysbrainbook.readthedocs.io/en/latest/OpenScience/OS/BIDS_Overview.html).

When it comes to my own data (recorded at a 3T Siemens Trio) I'm struggling with an error while converting to BIDS. I ran the Code
```
dcm2bids -d /home/BIDS_raw/sourcedata -p 573 -c /home/BIDS_raw/BIDS_config.json -o /home/BIDS_raw --forceDcm2niix
rm -r /home/BIDS_raw/tmp_dcm2bids
```
I then checked my data using the [bids validator](https://bids-standard.github.io/bids-validator/), but get the error [Code 19] TOTAL_READOUT_TIME_MUST_DEFINE, which points to my fieldmap image files. If I run fmriprep I get an error that it cannot find any subjects,, which I assume is due to incorrect BIDS format.

Any advice would be much apreciated!
Best,
Martin

**Comment by neurolabusc** [comment]
@theogeneserich sounds like a Gradient Echo field map was acquired (e.g. for FSL FUGUE), rather than a pair of spin-echo EPI images with opposite phase-encoding polarity (PEpolar) (e.g. for FSL TOPUP). You will want to make sure the file name describes your data correctly [e.g. _fieldmap/_magnitude vs _dir*](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#case-4-multiple-phase-encoded-directions-pepolar). TotalReadoutTime is a property of EPI scans (such as the spin-echo images used with TOPUP). On the other hand, [you cannot use EPI-based fieldmaps](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FUGUE). FUGUE explicitly expects the field map to not have the EPI spatial distortion, as that is what it is trying to correct. 

As an aside, the TOPUP spin-echo EPI sequences are not actually field maps. The idea here is that the two images have spatial distortion of equal magnitude but opposite direction. Spin Echo is used so the signal is (mostly) moved in space, where the signal is lost with EPI-based Gradient Echo sequences.

Therefore, this is not a limitation of dcm2niix. TotalReadoutTime is property of EPI scans. If your scan is not EPI, this field must not be populated.

**Comment by theogeneserich** [comment]
@neurolabusc thanks so much for the quick response. I had indeed not correctly specified my field map image. Adjusting this error solved the issue. Thanks!

**Comment by theogeneserich** [comment]
@neurolabusc thanks so much for the quick response. I had indeed not correctly specified my field map image. Adjusting this error solved the issue. Thanks!

**Comment by theogeneserich** [comment]
@neurolabusc thanks so much for the quick response. I had indeed not correctly specified my field map image. Adjusting this error solved the issue. Thanks!

**Comment by theogeneserich** [comment]
@neurolabusc thanks so much for the quick response. I had indeed not correctly specified my field map image. Adjusting this error solved the issue. Thanks!
