### ISSUE TITLE
Create a output without t stamp name.

### ISSUE THREAD

**Issue by sandeepganji** [rordenlab/dcm2niix#418]
When converting multiple dynamics ASL (PCASL) data, with  ```-f "ASL4D" -m y```  the output file name is  ```ASL4D_t254298```. It would be nice to force it to not have the suffix of 't******'.

**Comment by neurolabusc** [comment]
What version of dcm2niix are you using? What is the manufacturer of your scanner? I suspect your data is from a Philips scanner, and you are experiencing issue [408](https://github.com/rordenlab/dcm2niix/issues/408). If this is the case, you may want to test if the latest developmental release (v1.0.20200808) resolves your issue. I would also lobby your research collaboration manager to have this issue fixed. 

As noted in the [file naming notes](https://github.com/rordenlab/dcm2niix/blob/master/FILENAMING.md) you can attempt to suppress post-fixes being added by using the `--terse` option, but be aware that this can create name clashes and overwriting. In general, I would be very cautious whenever you are forced to use the `-m y` option. That option has the potential to cause a lot of unintended consequences, and should be used as a last resort. I would try to resolve the issue with the images themselves, if you have to use this, it suggests that your DICOMs are not of archival quality. Specifically, if data is being reported with different cardiac trigger times, it should not be treated as a single 4D dataset.

**Comment by neurolabusc** [comment]
The [-t post-fix](https://github.com/rordenlab/dcm2niix/blob/master/FILENAMING.md) suggests that the DICOM images claim to have a trigger delay time (0020,9153) or trigger time (0018,1060). If you have not used cardiac gating, your images are in violation of the DICOM standard. This is a limitation of your images, not the dcm2niix software. While dcm2niix contains some kludges to handle popular errors in DICOM headers, in general it [assumes that DICOM images are truthful](https://en.wikipedia.org/wiki/Quis_custodiet_ipsos_custodes%3F). Your DICOM images are explicitly claiming to have a trigger time. My latest developmental release has a kludge to try to handle Philips scans that incorrectly report [trigger times](https://github.com/rordenlab/dcm2niix/issues/408). However, this does not change the errors that are inherent to your images. 

1. I would suggest you purge the erroneous tags from the DICOMs. You could do this with [gdcmanon](http://gdcm.sourceforge.net/html/gdcmanon.html), e.g. `gdcmanon --dumb --remove 20,9153 --remove 18,1060 in.dcm out.dcm`. Even if the kludge in the developmental release of dcm2niix converts the images correctly, the problem you are having would impact any tool that handles these DICOMs. If the tags are in error, they should be removed.
2. If you work at a Philips research site, your center will have a Philips Research Collaboration Manager assigned to work with you to resolve issues. It is their job to help scientists resolve issue with equipment and ensure that errors can fixed in future software updates. The center where I work does not have Philips equipment, so I do not have this relationship. Again, this point rests on my assumption that your equipment is Philips and you are experiencing issue 408.

**Comment by neurolabusc** [comment]
I am closing this now, as I do not have examples of multi-PLD Philips data. I would rather have the user suffer the minor inconvenience of having _t tags appended to the name rather than having some images from a series overwrite others. Without further guidance o examples from Philips users, there is nothing else to do.
