### ISSUE TITLE
EstimatedEffectiveEchoSpacing for Philips wrong?

### ISSUE THREAD

**Issue by cni-md** [rordenlab/dcm2niix#431]
The EstimatedEffectiveEchoSpacing estimated by v1.0.20200427 seems to be wrong on Philips data or the Philips docs
Philips wrote:
To calculate the echo spacing, you need two pieces of information from the scan protocol: the "EPI train length" and the "Act. WFS / BW (Hz)" in pixels.
You also need to know the water-fat shift in Hz at your magnet's field strength. Hints: if you use gamma = 42.57 MHz/T, B0 in Tesla, and the water-fat shift as 3.4ppm, you can just multiply them together and the answer will be in Hz. Eg: at 3.0T, the wfs is 42.57 x 3 x 3.4 = 434.214Hz

ES = 1000 * WFS(pixel) /(wfs * (ETL + 1))

Using my 12.5 pixel WFS at 3T and a ETL of 39 I calculated a
"EffectiveEchoSpacing": 0.00071972
but dcm2niix 
"EstimatedEffectiveEchoSpacing": 0.000355246
Just a factor of 2 which is my sense factor.

**Comment by cni-md** [comment]
Forgot to mention
EstimatedTotalReadoutTime": 0.0280644
divided by ETL = 0.0007196
So the readouttime is correct.

**Comment by neurolabusc** [comment]
See [issue 377](https://github.com/rordenlab/dcm2niix/issues/377). Note that BIDS specifies that the EffectiveEchoSpacing and TotalReadoutTime follow the [FSL definition](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#in-plane-spatial-encoding). In other words, an image acquired with partial-Fourier has the same spatial distortion as an image without pF, so these have the same values. On the other hand, SENSE reduces the spatial distortion so has lower values. The sample datasets acquired did not show plausible results. Though it might be that a phantom, rather than a human was used so the shims may have an impact.

We do not have Philips hardware at my site, but if anyone wants to acquire a validation dataset (e.g. like @mharms did for [Siemens](https://github.com/neurolabusc/dcm_qa/tree/master/In/TotalReadoutTime)) we can revisit this.

I believe FSL's [topup](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/topup/TopupUsersGuide) is the only tool to use this value, and you can typically insert a dummy value:

_If your readout time is identical for all acquisitions you don't neccessarily have to specify a valid value in this column (you can e.g. just set it to 1), but if you do specify correct values the estimated field will be correctly scaled in Hz, which may be a useful sanity check. Also note that this value corresponds to the time you would have had had you collected all k-space lines. I.e. let us say you collect a 96x96 matrix with 1ms dwell-time (time between centres of consecutive echoes) and let us further say that you have opted for partial k-space (in order to reduce the echo time), collecting only 64 echoes. In this case the level of distortion will be identical to what it would have been had you collected all 96 echoes, and you should put 0.095 in the fourth column_

**Comment by mharms** [comment]
In case this helps someone else that ends up here:
The formula for `ES` cited in the intial post (https://github.com/rordenlab/dcm2niix/issues/431#issue-711139996) is incorrect, and doesn't account for the in-plane acceleration (SENSE factor), which is the very difference that @cni-md was asking about.

See comment I just added at https://github.com/rordenlab/dcm2niix/issues/377#issuecomment-1328530596.

**Comment by cni-md** [comment]
The SENSE factor is hidden in the ETL. If you accelerate the acquisision, you reduce the WFS and the ETL by the same factor. At the end the Sense factor is canceled out.

**Comment by mharms** [comment]
Right, that's why the formula that you initially provided, and which you can find online at many locations, isn't the correct one for computing the *effective* echo spacing.
