### ISSUE TITLE
Orientation inconsistency between versions 'v1.0.20190902' and 'v1.0.20200331'

### ISSUE THREAD

**Issue by pvelasco** [rordenlab/dcm2niix#438]
Hi,
I have found that for some images (specifically, T2w high-resolution anatomicals), the latest release ('v1.0.20200331') changes the orientation of the resulting NIfTI files. The images are labeled correctly, but they come out in a different orientation compared to previous versions, and the handiness of the q/sform is flipped.
T1w images collected with the same slice orientation are not affected (they still have the same orientation in the latest release as in the previous one; the same as for the T2w converted with the previous release).
This is problematic because 1) it changes behavior depending on the release version and 2) it treats differently images with the same slice orientation (T1w vs. T2w).
If this behavior is actually intended (and not a bug), is there any option to output the images in the old orientation?

#### Conversion Code: ####

I have two different Docker images in which I have installed 'v1.0.20190902' and 'v1.0.20200331'. They are called 'v3.2' and 'v3.5', respectively (for unrelated reasons).

In 'v3.2':
```bash
$ dcm2niix -b y -z y -x n -t n -m n -f T1_v3.2 -o /out/T1w_T2w/v3.2/ -s n -v n /in/T1w_T2w/07+t1_mprage_sag_p2_iso/
Chris Rorden's dcm2niiX version v1.0.20190902  GCC8.3.0 (64-bit Linux)
Found 192 DICOM file(s)
Convert 192 DICOM as /out/T1w_T2w/v3.2/T1_v3.2 (256x256x192x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/out/T1w_T2w/v3.2/T1_v3.2.nii"
Conversion required 12.356269 seconds (0.642290 for core code).
$ dcm2niix -b y -z y -x n -t n -m n -f T2_v3.2 -o /out/T1w_T2w/v3.2/ -s n -v n /in/T1w_T2w/08+T2w_p2_s2_.9mm/
Chris Rorden's dcm2niiX version v1.0.20190902  GCC8.3.0 (64-bit Linux)
Found 240 DICOM file(s)
Warning: ParallelReductionFactorInPlane reported in DICOM [0051,1011] (4) does not match CSA series value 2
Convert 240 DICOM as /out/T1w_T2w/v3.2/T2_v3.2 (256x256x240x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/out/T1w_T2w/v3.2/T2_v3.2.nii"
Conversion required 13.895481 seconds (0.792166 for core code).
```
In 'v3.5':
```bash
$ dcm2niix -b y -z y -x n -t n -m n -f T1_v3.5 -o /out/T1w_T2w/v3.5/ -s n -v n /in/T1w_T2w/07+t1_mprage_sag_p2_iso/
Chris Rorden's dcm2niiX version v1.0.20200331  GCC8.3.0 (64-bit Linux)
Found 192 DICOM file(s)
Convert 192 DICOM as /out/T1w_T2w/v3.5/T1_v3.5 (256x256x192x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/out/T1w_T2w/v3.5/T1_v3.5.nii"
Conversion required 2.591923 seconds (0.518581 for core code).
$ dcm2niix -b y -z y -x n -t n -m n -f T2_v3.5 -o /out/T1w_T2w/v3.5/ -s n -v n /in/T1w_T2w/08+T2w_p2_s2_.9mm/
Chris Rorden's dcm2niiX version v1.0.20200331  GCC8.3.0 (64-bit Linux)
Found 240 DICOM file(s)
Warning: ParallelReductionFactorInPlane reported in DICOM [0051,1011] (4) does not match CSA series value 2
Convert 240 DICOM as /out/T1w_T2w/v3.5/T2_v3.5 (256x256x240x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/out/T1w_T2w/v3.5/T2_v3.5.nii"
Conversion required 1.994576 seconds (0.372787 for core code).
```

#### Output Images Orientation: ####

```bash
$ cd /out/T1w_T2w/
$ fslhd v3.2/T1_v3.2.nii.gz | grep -A 25 qform
qform_name	Scanner Anat
qform_code	1
qto_xyz:1	0.898705 0.046449 0.012829 -92.019470 
qto_xyz:2	-0.048050 0.883704 0.154776 -110.061707 
qto_xyz:3	-0.004625 -0.155238 0.884912 -110.941795 
qto_xyz:4	0.000000 0.000000 0.000000 1.000000 
qform_xorient	Left-to-Right
qform_yorient	Posterior-to-Anterior
qform_zorient	Inferior-to-Superior
[...]  # (sform is the same)

$ fslhd v3.2/T2_v3.2.nii.gz | grep -A 25 qform
qform_name	Scanner Anat
qform_code	1
qto_xyz:1	0.898704 0.046449 0.012829 -113.588379 
qto_xyz:2	-0.048050 0.883704 0.154776 -108.908508 
qto_xyz:3	-0.004625 -0.155238 0.884912 -110.830803 
qto_xyz:4	0.000000 0.000000 0.000000 1.000000 
qform_xorient	Left-to-Right
qform_yorient	Posterior-to-Anterior
qform_zorient	Inferior-to-Superior
[...]  # (sform is the same)

$ fslhd v3.5/T1_v3.5.nii.gz | grep -A 25 qform
qform_name	Scanner Anat
qform_code	1
qto_xyz:1	0.898705 0.046449 0.012829 -92.019470 
qto_xyz:2	-0.048050 0.883704 0.154776 -110.061707 
qto_xyz:3	-0.004625 -0.155238 0.884912 -110.941795 
qto_xyz:4	0.000000 0.000000 0.000000 1.000000 
qform_xorient	Left-to-Right
qform_yorient	Posterior-to-Anterior
qform_zorient	Inferior-to-Superior
[...]  # (sform is the same)

$ fslhd v3.5/T2_v3.5.nii.gz | grep -A 25 qform
qform_name	Scanner Anat
qform_code	1
qto_xyz:1	-0.046449 0.012829 0.898704 -101.743881 
qto_xyz:2	-0.883704 0.154776 -0.048050 116.436134 
qto_xyz:3	0.155238 0.884912 -0.004625 -150.416443 
qto_xyz:4	0.000000 0.000000 0.000000 1.000000 
qform_xorient	Anterior-to-Posterior
qform_yorient	Inferior-to-Superior
qform_zorient	Left-to-Right
[...]  # (sform is the same)

Note how the 'orient' part (and the rotation part of the 'qform') is different for the last image.

**Comment by neurolabusc** [comment]
By default, dcm2niix will losslessly rotate 3D acquisitions so they will match the NIfTI identity matrix. In other words, the rows, columns and slices are permuted to generate a image aligned to RAS. Since most 2D acquisitions (like EPI-based fMRI and DWI) are acquired axially (so natively in RAS slicing), this harmonizes the data storage for 3D T1 and T2 sequences (which often have a sagittal disk storage). Since the residual origin is always saved in the sform/qform, this is a simple convenience, and will not impact any tool that uses the spatial transforms stored in those fields. Therefore, both solutions are correct.

However, there have been several adjustments in the 3D detection, which may change which images are rotated. Specifically, we do not want to rotate 3D EPI sequences, as undistortion and timing tools assume slices on disk correspond to acquisition slices. On the other hand, we have slowly become better at understanding how vendors populate their DICOMs. Further, across software releases vendors are changing their interpretation of the standard. Finally, the standard itself is evolving (e.g. enhanced DICOM). I suspect if you try the latest developmental branch of dcm2niix you will see it will discriminate your scans as 3D non-EPI data. Unfortunately, to support this standard, the tools must evolve, so inconsistencies are inevitable. Lossless inconsistencies like this one seem the least worrying.

If this behavior really bugs you, you can use the `-x i` argument to force the software to save the data as acquired.

**Comment by kavandeloo97** [comment]
Hi there, so sorry to open this closed issue! I had a similar warning and wanted to ensure that this was still a 'lostless' warning: 

Warning: ParallelReductionFactorInPlane reported in DICOM [0051,1011] (4) does not match CSA series value 2

This is when attempting to convert T1w/T2w images. Thanks!

**Comment by neurolabusc** [comment]
This shoudl not impact the processing of T1 and T2 images - the parallel reduction factor impacts the effective readout time for EPI data. I am not sure why there is a discrepancy, but the Siemens Research Collaboration Manager affiliated with your center can provide insight.
