### ISSUE TITLE
Error converting new Philips fMRI

### ISSUE THREAD

**Issue by perronea** [rordenlab/dcm2niix#446]
It seems something has changed about the Philips fMRI DICOMs within the last year or so. I've been downloading ABCD DICOMs from the NDA and the dcm2niix command that used to work with the year 1 data no longer works with the year 2 data. Basically, all of the DICOMs in the new Philips data are being concatenated together along dim3 so that the output of fslinfo looks like this:

ERROR: Illegal NIfTI file - 1401_sub-NDARINVXXXXXX_rsfMRI_3_XXXXXXXXXXX
       Zero determinant stored in sform and/or qform that is marked as valid
data_type      INT16
dim1           96
dim2           96
dim3           22979
dim4           1
datatype       4
pixdim1        2.250000
pixdim2        2.250000
pixdim3        2.400000
pixdim4        0.800000
cal_max        0.0000
cal_min        0.0000
file_type      NIFTI-1+

I tried using three different versions of dcm2niix including the most recent "development" branch but I get roughly the same error every time. From what I've read on previous forums you've responded to the problem is with non-imaging data being stored in .dcm format that is being confused as imaging data. For example, (0002,0002) is "RawDataStorage" in the first dcm of the new Philips scans where as it's all "MRImageStorage" in the old Philips datasets.

If you need examples I'm happy to give you instructions on how to download this data from the NDA, alternatively I could probably share a couple datasets via box if that's more convenient.

Please let me know if there's any other information I can provide to help you resolve this issue. Thank you.

**Comment by neurolabusc** [comment]
Sure, please put some problematic scans on Box and send a link to the email shown in my avatar. I have a ABCD account and agree with their license.

**Comment by perronea** [comment]
Sent. Let me know if you did not receive the invite.

**Comment by neurolabusc** [comment]
@perronea this is a limitation of the ABCD dataset, not dcm2niix. Please contact them to have them resolve the issue (or just exclude the first volume, as I describe below). 

The DICOM images from 2017 (rsfMRI_4_2017062...) contain a full resting state series, with 22980 images (60 slices each with 383 volumes). The instance numbers of the images span 1..22980. dcm2niix converts this correctly.

The DICOM images from 2019 (rsfMRI_run-201908...) contain only 22979 images (with instance numbers 2..22980). The DICOM file with instance number 1 is not an image. Rather it is a RawDataStorage file (Philips equipment will tend to give these the XX prefix). These files store sequence parameters, and play the same role as the proprietary CSA headers that are embedded in Siemens DICOMs. dcm2niix correctly warns you

```
Skipping non-image DICOM: ABCD-rsfMRI_run-201908...dicom000001.dcm
```

You can see that the file size is different, and using a tool like dcmdump or gdcmdump to inspect the DICOM reveals it is not an image:
```
(0002,0002) UI =RawDataStorage    #  26, 1 MediaStorageSOPClassUID
```
Whereas, all the DICOM images reveal report:
```
(0002,0002) UI =MRImageStorage.   #  26, 1 MediaStorageSOPClassUID
```
Presumably the ABCD script that packaged these DICOMs just looked at the instance numbers and did not notice that the first instance was not an image. 

To convert the dataset you either need to get the final image in the series `...022981.dcm`, or alternatively you can remove the slices from the first partial volume (all files `...000001.dcm`...`...000060.dcm`. With either of these changes, dcm2niix will work correctly. It

**Comment by neurolabusc** [comment]
I am closing this, as it is an ABCD issue, not an issue with dcm2niix. A common mistake is to assume that InstanceNumber (0020,0013) is unique, but this is not required. Historically, this was an issue Siemens field maps, which used the same instance number for phase and magnitude images. PACS, anonymization, and archiving tools would often assume the these were duplicate images, resulting in some phase images overwriting magnitude images and vice versa, resulting in one volume with mixed image type rather than two unique volumes. I can fully understand Philips' desire to store some sequence data in a DICOM file, but re-using an existing instance number can lead to unintended consequences.

@drmclem is there any chance we can develop a collaboration with the engineers at Philips to refine a few features of the files created? While the Philips files are legal, small changes could prevent unintended consequences and could also provide meta-data that would be a huge benefit for users. My recent collaboration with Siemens on the upcoming XA30 DICOMs as well as my collaboration with [GE engineers regarding R29](https://github.com/neurolabusc/dcm_qa_ge) demonstrate the potential for these. collaborations. It does seem that Philips are at a competitive disadvantage when it comes to providing meta information (readout time, phase encoding polarity, slice times, partial Fourier fraction, ASL details, etc). We do not have Philips equipment at my site, so I do not have access to a Philips Research Collaboration Manager. However, I do think tiny changes could have a profound benefit for users.

**Comment by perronea** [comment]
Thank you @neurolabusc removing all slices from that first volume worked!
