### ISSUE TITLE
GE DTI bvecs bvals conversion

### ISSUE THREAD

**Issue by willi3by** [rordenlab/dcm2niix#456]
Hi,

I am using the development branch of dcm2niix to convert GE DTI files from a custom DBSI sequence that we are using for a study. The sequence consists of 26 bvecs, each with a unique bval up to 1500. I know that there is already a known issue with the resulting bvecs and bvals from dcm2niix but I noticed on the documentation that you would like the results posted as an issue. The sequence is collected in the COL orientation, but the output is still incorrect. The bvals all come out as the max (1500) and the vectors scaled accordingly. Are there any new developments for this conversion? I am happy to test any developments or help with this anyway that is needed.

Thanks for your time

**Comment by neurolabusc** [comment]
This may reflect a limitation of your custom sequence rather than my software. You can use tools like dcmdump or gdcmdump to look at the DICOM headers, specifically [0043,1039](https://www.na-mic.org/wiki/NAMIC_Wiki:DTI:DICOM_for_DWI_and_DTI#Private_vendor:_GE). dcm2niix simply transcribes the value reported by this tag. Feel free to send me a sample dataset via DropBox or GoogleDrive (my email is embedded in my avatar). However, if the DICOM images do not correctly report the b-value, the issue must be fixed in the DICOMs or salvaged post-conversion.

**Comment by willi3by** [comment]
Got it. That makes sense. I checked the dicom headers and they indeed report the incorrect value. I will fix it on the scanner side to reconstruct with the correct value and put it in the header. Thanks very much for your time!
