### ISSUE TITLE
GE derived 3D sequence converted into 4d

### ISSUE THREAD

**Issue by dagra** [rordenlab/dcm2niix#459]
I have a 3D sequence (512x512x256) which is converted into a 4D (512x512x128x2) in the latest release and I noticed that this is happening since [v1.0.20190902](https://github.com/rordenlab/dcm2niix/releases/tag/v1.0.20190902), but in the release [v1.0.20190410](https://github.com/rordenlab/dcm2niix/releases/tag/v1.0.20190410) it was converted successfully.

I think that the following DICOM tags of the dataset are not correct, but since it was working in the release *v1.0.20190410* and the other sequences of the study (the corresponding coronal and sagittal) are converted successufully, I wonder if it can be fixed:

```
(0020,1002) IS [184]                                    #   4, 1 ImagesInAcquisition
(0021,104f) SS 92                                       #   2, 1 LocationsInAcquisition
```

I sent you the problematic sequence in the email.

Thanks

**Comment by neurolabusc** [comment]
This image does not make sense to me. The ImagesInAcquisition and LocationsInAcquisition values suggest [zip2 interpolation](https://github.com/rordenlab/dcm2niix/issues/373), but I can not explain why 256 images are stored to disk. The latest commit forces the total number of slices to be divisible by the ImagesInAcquisition, otherwise that value is ignored (though a warning message is generated). This kludge should resolve your issue, but I still have no insight into the root cause.

**Comment by neurolabusc** [comment]
@mr-jaemin noted this is `DERIVED` not `ORIGINAL` data. Presumably, the reformatting modified this image. Wherever possible, I would discourage interpolation for DICOM data, as it is not compatible with [some toolls](https://mrtrix.readthedocs.io/en/latest/reference/commands/mrdegibbs.html).

`(0008,0008) CS [DERIVED\SECONDARY\REFORMATTED\AVERAGE]  #  38, 4 ImageType`

**Comment by dagra** [comment]
> @mr-jaemin noted this is DERIVED not ORIGINAL data. Presumably, the reformatting modified this image.

Yes, my suspicion was that after the reformatting not all DICOM tags were updated properly.

Thank you for the research.

I tested the development branch and it resolves the issue. Thanks!
