### ISSUE TITLE
Manufacturer tag not found, but appears in DICOM

### ISSUE THREAD

**Issue by lidialuq** [rordenlab/dcm2niix#487]
When the manufacturer tag (0008, 0070) is set to "GE MEDICAL SYSTEMS" or "SIEMENS", dcm2niix cannot find the manufacturer, and I get the warning "Unable to determine manufacturer (0008,0070), so conversion is not tuned for vendor". In the json files though, the Manufacturers Model Name tag is filled ("Avanto", for example). On the other hand, everything works fine when manufacturer tag is "Philips Medival Systems" (no warning, relevant tags in json are filled). 
The dicom files I'm using come straight from PACS, and in principle should not have been changed in any way since they were created in the MRI machine. They are not anonymized in any way. 

The command I run is `dcm2niix -ba y -z y path/to/data`. I use version v1.0.20201102 (64-bit Windows).

**Comment by neurolabusc** [comment]
Avanto reflects the Manufacturer's Model Name (0008,1090) not the Manufacturer (0008,0070). My sense is that the Manufacturer tag has been mangled by your PACS system. Since each manufacturer interprets the complex DICOM standard differently and employs their own private tags, it is important to correctly identify the manufacturer that created the image. I suspect a DICOM anonymization stage or a [PACS](https://github.com/neurolabusc/dcm_qa_agfa) has mangled your data. If this is the case, this will impact any tool that attempts to decipher your data. Have you looked at the DICOM header with a tool like dcmdump or gdcmdump (alternatively, put a single DICOM file from your troublesome series in its own folder and convert with `dcm2niix -b i -v 2 /path/to/DICOM/`)? This will show the value stored in the Manufacturer tag. Alternatively, send a DropBox/GoogleDrive link to an example dataset to my personal email (shown in my avatar).

**Comment by lidialuq** [comment]
The Manufacturer tag is indeed empty in the dicom header as shown by running `dcm2niix -b i -v 2 /path/to/DICOM/`, but it is present in the original dicom header (see attached files, * are values that I have removed, but that are present in the original files). Is the reading of the Manufacturer tag by dcm2niix dependent on any other tags being present? 

The images are not anonymized at all (they include patient name, for instance), but it might well be that PACS is messing up the header when storing the image (I know that agfa is one of the PACS systems used in the hospital network, though there are many others). Still, as long as the Manufacturer tag is present, it should in theory work..?

[dcm2niix_header.txt](https://github.com/rordenlab/dcm2niix/files/6084281/dcm2niix_header.txt)
[dicom_header.txt](https://github.com/rordenlab/dcm2niix/files/6084282/dicom_header.txt)

**Comment by neurolabusc** [comment]
Looks like some tool inserted new sequence with a different Manufacturer (0008,0070) name. Your file `dicom_header.txt` only reports the highest level of the hierarchy.

```
(0018,A001) Contributing Equipment Sequence                 <Sequence of data>
```

**Comment by neurolabusc** [comment]
You may want to try the latest commit (v1.0.20210304) which is available as a compiled Windows application from [AppVeyor](https://ci.appveyor.com/project/neurolabusc/dcm2niix/build/artifacts). This gives precedence to the first Manufacturer tag that it recognizes (Siemens, Philips, GE, UIH, Toshiba, Canon, Bruker).

**Comment by lidialuq** [comment]
Neat, this fixed the issue. Thank you! 

As a side note: It was apparently sectra inserting a new manufacturer in the Contributing Equipement Sequence tag (see image). The weird thing is that this tag is exaclty the same in all dicom files coming from this PACS. For some reason, dcm2niix still managed to figure out the manufacturer when it was philips, but not when it was siemens or GE. 
[contributing_equipement_sequence](https://user-images.githubusercontent.com/72806975/110003213-758f2500-7d16-11eb-863a-648812109a30.PNG)
