### ISSUE TITLE
Are PhaseEncodingDirection and PhaseEncodingAxis identical?

### ISSUE THREAD

**Issue by dlevitas** [rordenlab/dcm2niix#508]
I typically see the dicom header `PhaseEncodingDirection` with Siemens data; however, I've noticed the dicom header `PhaseEncodingAxis` with GE data and was wondering if these values are identical and are simply labelled different due to their respective scanner, or if they represent different values? I ask because I use the `PhaseEncodingDirection` value to determine the BIDS `_dir-` label (i.e. if `PhaseEncodingDirection == j` and `orientation == LAS`, then `dir = PA`). I was wondering if this logic also applies to `PhaseEncodingAxis` values? My hunch is that `PhaseEncodingAxis` doesn't specify the polarity, but want to double check.

Thanks

**Comment by neurolabusc** [comment]
The BIDS tag [PhaseEncodingDirection](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html) is explicitly defined by the BIDS standard, and reveals both the axis of the phase encoding axis (e.g. RL, AP, SI) as well as the polarity (e.g. R->L vs L->R). 

Unfortunately, with some DICOM images one can determine the axis (e.g. RL, AP, SI) but not the polarity. In this case, dcm2niix generates the tag `PhaseEncodingAxis` which is **not** defined in the BIDS standard. In order to convert `PhaseEncodingAxis` into `PhaseEncodingDirection`, the user will need to provide information regarding the polarity.

1. I believe that recent versions of dcm2niix are able to determine `PhaseEncodingDirection` for both Siemens as well as [GE](https://github.com/neurolabusc/dcm_qa_ge/blob/master/Ref/epiRT_IntAsc_GD3s_2.json). If your data is from GE, you may want to see if upgrading dcm2niix resolves this issue. Only recent versions of dcm2niix decode the proprietary GE DICOM tag [Define Data GE (0043,102A)](https://github.com/rordenlab/dcm2niix/tree/master/GE) which is required to infer polarity.
2. dcm2niix is unable to determine phase encoding polarity for Philips data. This reflects a limitation in Philips DICOM data, not dcm2niix.

**Comment by dlevitas** [comment]
Perfect, thanks for the clarification
