### ISSUE TITLE
DICOMs with incomplete data

### ISSUE THREAD

**Issue by baxpr** [rordenlab/dcm2niix#515]
**Describe the bug**

We occasionally get a DICOM with incomplete data. This typically happens when an fMRI scan on Philips is stopped early - the scanner just reconstructs what it can. The enhanced DICOM produced by the scanner typically ends up with N complete volumes, plus some but not all of the frames/slices of the final volume.

dcm2niix will create a nifti file from these, but it gets confused about the dimensionality and puts time and slice both into the third dimension, so the nifti is not usable.

**Expected behavior**

Convenient would be if dcm2niix could create a valid 4D nifti with all the complete volumes that are present. I've done some digging and I'm not sure how possible/practical it is to figure out the correct dimensions from the info in the DICOM though.

**Version**

All versions I've tried, which is a lot. Including the most recent stable v1.0.20210317, and the most recent development branch at commit 1cfbd7a685.

**Comment by neurolabusc** [comment]
This is a duplicate of [issue 357](https://github.com/rordenlab/dcm2niix/issues/357). I suggest you look at the suggestion by @drmclem. Alternatively, you could try the [fix_dcm_incompletevols.py script](https://github.com/VisionandCognition/NHP-Process-MRI/blob/master/python/fix_dcm_incompletevols.py) from @pcklink. 

I have committed a kludge to dcm2niix that **might** convert your images. However, since Philips enhanced DICOMs seem to have at least different methods for saving EPI data (ZT, TZ or jumbled order coming from parallel reconstruction system) I am really not sure my kludge will work universally. The kludge will attempt to save the dataset, but generates a text warning and also returns a non-zero exit code. I would treat these datasets with extreme caution. Perhaps for the next stable release I should remove this kludge and simply provide a text output that directs users to the solutions described for issue 357.

**Comment by baxpr** [comment]
Thanks! I had missed issue 357 - we'll dig in to that.
