### ISSUE TITLE
Reporting of major changes within Releases

### ISSUE THREAD

**Issue by mharms** [rordenlab/dcm2niix#523]
Just wondering if there is any sort of convention in terms of the "major" changes reported on the Releases page.  As an example, I was comparing the output of the `20210317` and `20201102` versions, and was surprised to find that the values for `EffectiveEchoSpacing` and `TotalReadoutTime` changed.   Upon explicitly comparing the two versions, I see that this change was introduced with #480.  Just wondering why some PRs get mentioned in the Release notes, while others do not.  Is it just a matter of which PRs and changes are deemed worthy of highlighting?

**Comment by neurolabusc** [comment]
Stable versions of dcm2niix are released twice per year (Spring, Fall). Each release should address all issues raised since the prior release. Since that is a huge number, I try to only list the `major` changes in each new release, though the definition is arbitrary. From my perspective, issue 480 was pretty minor: the FSL definition of `TotalReadoutTime` is unusual, and there is no corresponding manufacturer value. Therefore, the formula is unintuitive: consider the [solution](https://github.com/rordenlab/dcm2niix/blob/e973e0ff5ba5ddde73bb2b95088a9fadc2f4997b/console/nii_dicom_batch.cpp#L1577) from issue 480 which is specific to GE. Also, while FSL's TOPUP requires the user to specify the TotalReadoutTime, it only impacts the warp fields if this values differ between the phase-reversed pair (which is extremely rare). The only other impact would be the calibrated FieldMap (in Hz) if the `--fout` option is used. These calibrated FieldMaps might be useful for quality assurance, but do not impact subsequent analyses. Therefore, I see this change as minor, though power users (like you) may disagree.

One suggestion I would have, is why not make a custom version of [dcm_qa](https://github.com/neurolabusc/dcm_qa) that uses DICOM images specific to your studies? Simply place the DICOM images in the `In` folder, and the results from your favorite version of dcm2niix in the `Ref` (reference) folder. As new versions of dcm2niix are released, you simply run the `batch.sh` script and it will report any differences between the reference conversion and the new conversion.

**Comment by mharms** [comment]
Yeah, I appreciate that it is a challenge sometimes to decide which changes are "major" enough to mention directly in the Release Notes.  I haven't used `dcm_qa` but it sounds like a very useful tool to automate these sorts of checks!  Thx.
