### ISSUE TITLE
Unable to generate bval/bvec files 

### ISSUE THREAD

**Issue by bhavika-g** [rordenlab/dcm2niix#525]
Hi. 
I'm trying to convert DICOM files to NIFTI but the conversion only yields the .nii file and the .json file, and not the .bval or .bvec file. 
I've tried MRIcron, MRIcroGL and MRIConvert with no success. 
I also tried to read the contents of the file through pydicom but did not find the row that should have the b-value information. 
The images were acquired through Bruker BioSpec and the software used was Paravision 6.0.1. 
Please provide solutions to this. 
Thank you so much.

**Comment by neurolabusc** [comment]
This is a limitation of the DICOM images created by [Bruker](https://github.com/rordenlab/dcm2niix/issues/265) not dcm2niix. Since these issues were first reported years ago, I would hope that they can be resolved by [upgrading your software](https://www.accela.eu/discover/paravision-7-software). I suggest you contact Bruker to resolve this issue, dcm2niix is limited to the information provided by the DICOM images it is provided.
