### ISSUE TITLE
dcm2niix in win64 run error

### ISSUE THREAD

**Issue by ranabanik** [rordenlab/dcm2niix#528]
I have installed the dcm2niix in my windows station in `carotid36` py3.6 env using gitbash terminal. 
`(carotid36)
ranab@banikr MINGW64 /
$ conda install -c conda-forge dcm2niix  `

Then following the instructions, I ran the following from the gitbash terminal. 

```
(carotid36)
ranab@banikr MINGW64 /
$ dcm2niix.exe E:\Elucid_data\CAP Exam Data\OrganizedOutput\dicoms\1.2.840.113845.13.4353.3528386102.230081008712
```
I got the following error message. 
```
Error: Input folder invalid: DataOrganizedOutputdicoms1.2.840.113845.13.4353.3528386102.230081008712
Chris Rorden's dcm2niiX version v1.0.20210317  MSC1916  (64-bit Windows)
Warning: only processing last of 3 input files (recompile with 'myEnableMultipleInputs' to recursively process multiple files)
```
I manually check the physical location in the directory and the .dicom files exist(in slices). 
![image](https://user-images.githubusercontent.com/47092529/125177547-5ad82b80-e1a2-11eb-95bb-a4ca443f3c18.png)

What's wrong here?

**Comment by neurolabusc** [comment]
Make sure to use quotes if your file path has spaces in it. Otherwise, command line tools will assume you are passing two arguments, not a single space-delimited argument, e.g. 

```
dcm2niix.exe "E:\Elucid_data\CAP Exam Data\OrganizedOutput\dicoms\1.2.840.113845.13.4353.3528386102.230081008712"
```

You may also want to try out [MRIcroGL](https://www.nitrc.org/plugins/mwiki/index.php/mricrogl:MainPage) the Import/ConvertDICOMtoNIfTI window provides a graphical interface for dragging and dropping folders. As a bonus, it reports the command line it used for a conversion, helping you determine how to use dcm2niix from the terminal.
