### ISSUE TITLE
Option to overwrite existing files instead 

### ISSUE THREAD

**Issue by ghisvail** [rordenlab/dcm2niix#535]
In the context of the Clinica project, we have been struck with a [bug](https://github.com/aramis-lab/clinica/issues/396) where the expected stem of the target files (specified by `-f`) is modified by `dcm2niix` to avoid name collisions if a file with the very same stem already exists in the output folder (specified by `-o`).

For instance, say we are doing BIDS conversion for a T1w scan, `dcm2niix` will generate a `_T1wa` if a scan with a `_T1w` suffix already exists. This behavior is rather unintuitive for newcomers, since users may end up with a file with a different suffix than instructed with `-f`. I am sure there are reasonable rationales for it, I am just giving my honest opinion here.

We were wondering whether it would be possible to alter this behavior (say with a `--overwrite` option) so that `dcm2niix` overwrites existing files matching the stem instead of computing a different suffix? The default behavior of avoiding name collisions would be kept, whilst allowing overwrites for those of us (like Clinica) who wish so.

**Comment by ghisvail** [comment]
My bad I did not see the `-w` flag 🤦

**Comment by neurolabusc** [comment]
As you note, the `-w` option allows you to skip or overwrite duplicates. Likewise, the `--terse` option [will omit image disambiguation post-fixes](https://github.com/rordenlab/dcm2niix/blob/master/FILENAMING.md). These options are available for advanced users. Just be aware that some series will generate different images that can not be saved as a single NIfTI image, and the intention of dcm2niix is to preserve this variation. For example, a localizer scan may contain a coronal, axial and sagittal acquisition in a single series, whereas all slices in a NIfTI volume must have the same slice angulation. 

I would consider you consider fixing this problem upstream. Rather than overwriting or skipping data, you may want to work out why you have redundant DICOM datasets. This would help curate your source data and allow file naming disambiguation when required. Personally, I use the dcm2niix renaming function (`-r y`) to rename the source DICOM images to a meaningful structure. This avoids storing duplicate DICOMs and aids if an audit is ever required. Something like:

```
 dcm2niix -f %t/%s_%p/%4r_%o.dcm -o /renamed/DICOMS /original/DICOMS
```

As long as your DICOM images are truly unique, dcm2niix should typically only add the `a`, `b`, [etc](https://github.com/rordenlab/dcm2niix/blob/master/FILENAMING.md) post-fix if it is required to preserve variability in the data.

There is indeed a rationale why dcm2niix has to avoid name clashing, and if you disable this feature you may experience unintended consequences.
