### ISSUE TITLE
Unable to equalize slice distances: slice order not consistently ascending

### ISSUE THREAD

**Issue by dlevitas** [rordenlab/dcm2niix#539]
I'm converting an ADNI subject and noticed this message:

```
Unable to equalize slice distances: slice order not consistently ascending:
dx=[0 0 1.2 2.4 3.60001 4.8 6 7.2 8.4 9.60001 10.8 12 13.1998 14.3998 15.5998 16.7998 17.9998 19.1998 20.3998 21.5998 22.7998 23.9998 25.1998 26.3998 27.5998 28.7997 31.1997 32.3997 33.5997 34.7997 35.9997 37.1997 38.3997 39.5997 40.7997 41.9997 43.1997 44.3997 45.5997 46.7997 47.9997 49.1997 50.3997 51.5997 52.7997 53.9997 55.1997 56.3997 57.5997 58.7997 59.9997 61.1997 62.3997 63.5997 64.7997 65.9997 67.1997 68.3997 69.5997 70.7997 71.9997 73.1997 74.3997 75.5997 76.7997 77.9997 79.1997 80.3997 81.5997 82.7997 83.9997 85.1997 86.3997 87.5997 88.7997 89.9997 91.1997 92.3997 93.5997 94.7997 95.9997 97.1997 98.3997 99.5997 100.8 102 103.2 104.4 105.6 106.8 108 109.2 110.4 111.6 112.8 114 115.2 116.4 117.6 118.8 120 121.2 122.4 123.6 124.8 126 127.2 128.4 129.6 130.8 132 133.2 134.4 135.6 136.8 138 139.2 140.4 141.6 142.8 144 145.2 146.4 147.6 148.8 150 151.2 152.4 153.6 154.8 156 157.2 158.4 159.6 160.8 162 163.2 164.4 165.6 166.8 168 169.2 170.4 171.6 172.8 174 175.2 176.4 177.6 178.8 180 181.2 182.4 183.6 184.8 186 187.2 188.4 189.6 190.8 192 193.2 194.4 195.6 196.8 198 199.2 200.4 201.6 202.8 204 205.2 206.4 207.6 208.8 210 211.2 212.4 213.6 214.8 216 2.95029e-39 3.42362e+09 3.82554e-43 0 0 0 -3.47944e-13 3.08286e-41 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 -1.09857e-17 4.57216e-41 -nan 0 6.40969e-10 4.14153e-29 7.34684e-40 6.40941e-10 -3.48192e-13 3.08286e-41 -nan -nan 6.40969e-10 4.22042e-29 -nan -nan 0 0 2.60642e-43 4.25986e-29 3.94722e-40 0 -nan 3.94722e-40 0 4.2993e-29 3.94722e-40 0 -1.09694e-17 4.57216e-41 2.19163e-42 6.40969e-10 0 0 0 0 0 0 6.40941e-10 6.40969e-10 2.92871e-43 0 -1.09838e-17 4.57216e-41 -1.09838e-17]
 Recompiling with '-DmyInstanceNumberOrderIsNotSpatial' might help.
```

dcm2niix still generates the NIfTI and corresponding json files; however, I'm unsure how serious this message is. 

Using ```Chris Rorden's dcm2niiX version v1.0.20210317  (JP2:OpenJPEG) GCC7.3.0 x86-64 (64-bit Linux)```

When I isolate the specific DICOMS (shared on google drive), I get an additional error message:

```
Found 360 DICOM file(s)
180 images have identical time, series, acquisition and instance values. DUPLICATES REMOVED.
DICOM images may be missing, expected 182 spatial locations per volume, but found 180 slices.
Warning: Interslice distance varies in this volume (incompatible with NIfTI format).
Error: Missing images. Found 180 images, expected 182 slices per volume and instance number (0020,0013) ranges from 2 to 182
```
Based on the error, this seems to simply be a case of missing DICOM data. If so, am I correct to assume that using this acquisition is unuseable?

Thanks

**Comment by neurolabusc** [comment]
Instance number 27 is missing from this series. The error message was confusing, as dcm2niix attempts to rotate 3D volumes before attempting to correct for variable slice instances. I have submitted a kludge to the development branch which should handle this.

The ADNI dataset is a treasure trove, but it is poorly curated, as documented [here](https://github.com/aramis-lab/clinica/issues/394) and [here](https://github.com/rordenlab/dcm2niix/issues/416). 

Therefore, I would suggest using a tool like [clinica](https://github.com/aramis-lab/clinica) which includes kludges to handle some of these anomalies.

**Comment by dlevitas** [comment]
Ah okay, thanks for this! The context for this question comes from[this post](https://github.com/brainlife/ezbids/issues/29), where we've been trying to reverse engineer the same error. This clarifies things nicely.

**Comment by captainnova** [comment]
Hello @dlevitas , you probably already saw this on the ezbids forum, but it is worth posting on the forums of other software that is commonly used to convert ADNI data:

ADNI related questions are welcome at http://adni.loni.usc.edu/support/experts-knowledge-base/ask-experts/ , where questions are forwarded to the appropriate experts according to their category. In particular, we would like to be notified of any data related problems that can be resolved for future users, and may be causing problems for processing and analysis software. All ADNI images are manually inspected for quality control, but a few substandard scans or incomplete series have escaped quarantine over the years, for miscellaneous reasons.

If you have a question or comment concerning specific data, please provide, to the best of your ability,

    the subject ID (DICOM tag (0010, 0020))
    the scan date, (DICOM tag (0008, 0020))
    the LONI image ID
    the series number (DICOM tag (0020, 0011))
    the series description (DICOM tag (0008, 103e))

(ADNI includes more than just imaging, so the Ask the Experts page will not prompt you for these.)

Since in this case it sounds like there may be missing slices, it might also be worth checking if LONI has all the slices, and if so, downloading again.

Thank you,

Rob Reid, on behalf of ADNI
