### ISSUE TITLE
Acceptable EchoTime measurement error

### ISSUE THREAD

**Issue by dlevitas** [rordenlab/dcm2niix#543]
This is more of a conceptual question and doesn't directly pertain to dcm2niix, so apologizes if this is an inappropriately placed post. 

I was examining the metadata of three ADNI subjects, and noticed a slight difference in the EchoTime of one of them. The values are:

```
"EchoTime": 0.03,
"EchoTime": 0.03,
"EchoTime": 0.030001,
```

These acquisitions (`Axial fcMRI (EYES OPEN`) comes from 3 separate subjects scanned at the same institution, on the same scanner. I was wondering whether this measurement difference is negligible or would cause a notable signal difference? Given how precise scanners are, is there an acceptable range of variation in different measurements (e.g. EchoTime, RepetitionTime, etc) of the same dataset?

**Comment by neurolabusc** [comment]
Short Answer:

I do think the tiny effects you see are negligible. I am not sure your example means that the echo times were really slightly different (e.g. due to different slice angulation) or this reflects a rounding error. I would ignore this, and if you have scripts looking at data consistency, consider adding a tolerance 

Long Answer:

As [Kernighan and Plauger](https://www.amazon.com/Elements-Programming-Style-Brian-Kernighan/dp/0070341990) note Floating point numbers are like piles of sand; every time you move one you lose a little sand and pick up a little dirt. I also suggest this [page](https://introcs.cs.princeton.edu/java/91float/) and [this one](http://www.freshsources.com/page1/page7/files/Sand-1.pdf).

Indeed, MRI manufacturers have been plagued by the handling of floating point rounding errors. If you watch most experience MRI physicists setting up a protocol, you will notice that they tend to round up most values from the absolute minimum on the console's sequence design user interface to avoid conversion conflicts. Many sequences show tiny variations depending on individual applications of a sequence, e.g. adjusting the angulation of an image will change some of the factors.

A single x86-64 computer can give slightly different answers to the formula `y = x * scl_slope + scl_intercept` for 32-bit floating point depending on if it uses the FPU (80-bit internal precision), SSE (64-bit) or AVX (64-bit but FMA reduces one rounding). The problems are compounded across architecture (e.g. ARM64, NVIdia CUDA, etc). 

Strangely, even within a single sequence I have seen the same value (e.g. echo time) vary from one DICOM to another.  I noticed this originally with data from GE systems, so you will see that dcm2niix is littered with the function`isSameFloatGE` that allows for a little variation the report of a measurement.

When the BIDS format was first formulated, I was very opposed to the JSON format because it requires floating point numbers to be converted from binary to ASCII (and back). There is a lot of variability in this operation across compilers, programming languages, architectures, etc. All modern computers agree on a IEEE 754 binary representation (even if they differ on internal precision for calculations). However, in hindsight I think this reflects my OCD nature.

**Comment by dlevitas** [comment]
Makes sense, thanks for the detailed explanation.

**Comment by dlevitas** [comment]
I was looking through https://github.com/rordenlab/dcm2niix/blob/master/console/nii_dicom_batch.cpp at the `isSameFloatGE` function, but couldn't find where this function is defined. I'm curious what tolerance dcm2niix allows for certain measurements?
