### ISSUE TITLE
Philips fMRI discrepancy between TR and other temporal measures

### ISSUE THREAD

**Issue by neurolabusc** [rordenlab/dcm2niix#560]
@drmclem and @sandeepganji can either of you explain this discrepancy between RepetitionTime (0018,0080) versus both TriggerTime (0018,1060) and AcquisitionTime (0008,0032). RepetitionTime reports 3000ms for all slices, which seems plausible for a 48-slice resting state sequence acquired on a 3T MRI (acquired before the advent of multi-band). However, the TriggerTime and AcquisitionTime both reliably describe 6000ms between the start of one volume and the beginning of the next. In my experience, the latter measures are more reliable on Philips equipment as they account for delays due to `prospect. motion corr.`. However, these effects are typically on the order of ~17ms per volume. Any clue for what might cause such a discrepancy.

First slice, first volume (1):

```
(0008,0032) TM [161415.17]  #  10 AcquisitionTime
(0008,0033) TM [161415.17]  #  10 ContentTime
(0018,0080) DS [3000]       #   4 RepetitionTime
(0018,0081) DS [30.001]     #   6 EchoTime
(0018,0087) DS [3]          #   2 MagneticFieldStrength
(0018,1020) LO [3.2.1\3.2.1.1] #  14 SoftwareVersions
(0018,1060) DS [0]          #   2 TriggerTime
(0008,1090) LO [Intera]     #   6 ManufacturerModelName
(0020,0013) IS [1]          #   2 InstanceNumber
(0020,0100) IS [1]          #   2 TemporalPositionIdentifier
(2001,100a) IS [1]          #   2 SliceNumberMrPhilips
```

First slice, final volume (140):

```
(0008,0032) TM [162812.17]  #  10 AcquisitionTime
(0008,0033) TM [162812.17]  #  10 ContentTime
(0018,0080) DS [3000]       #   4 RepetitionTime
(0018,0081) DS [30.001]     #   6 EchoTime
(0018,0087) DS [3]          #   2 MagneticFieldStrength
(0018,1020) LO [3.2.1\3.2.1.1] #  14 SoftwareVersions
(0018,1060) DS [837000]     #   6 TriggerTime
(0008,1090) LO [Intera]     #   6 ManufacturerModelName
(0020,0013) IS [140]        #   4 InstanceNumber
(0020,0100) IS [140]        #   4 TemporalPositionIdentifier
(2001,100a) IS [1]          #   2 SliceNumberMrPhilips
```

**Comment by drmclem** [comment]
Hi

Without seeing the full protocol it's a bit tricky -

It could be acquired as a 2 package scan - in which case the Magnetic TR will be as requested but there are more slices than will fit in that TR - so the scan will be split odds then evens and run in two packages (concatenations in other vendors?) - given that it is twice the TR - this could be the case.

but I can also imagine also a scenario where this would be the case if the scan were cardiac triggered to remove physiological fluid motion.

The TR is always the "magnetic TR" - which for single shot slices is a bit ill defined, but for example if a scan were performed in packages or for slice interleaving etc. the magnetic TR will determine the time taken for the slices to be acquired (and in normal TR scans collected over multiple TR's will be the time between successive excitations.

However - if the scan is triggered - then the actual time between acquisitions will be governed  by the heart rate not the TR - dead time is added at the end of the scan while waiting for the next heart-beat.

Given these numbers seem a bit exact for real heart beats - it may also be that the protocol is using a heart rate simulator in the software.

All of this assumes the scan is actually triggered - so without seeing the Examcard that goes with this (and its quite an old release of software R3) this is a bit speculation.

Matthew



From: Chris Rorden ***@***.***>
Sent: Monday, November 15, 2021 4:21 PM
To: rordenlab/dcm2niix ***@***.***>
Cc: Clemence, Matthew ***@***.***>; Mention ***@***.***>
Subject: [rordenlab/dcm2niix] Philips fMRI discrepancy between TR and other temporal measures (Issue #560)

Caution: This e-mail originated from outside of Philips, be careful for phishing.


@drmclem<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdrmclem&data=04%7C01%7C%7C42c90040eba3421c0c6a08d9a853efe4%7C1a407a2d76754d178692b3ac285306e4%7C0%7C0%7C637725900722264340%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=5r5JtM7Xl%2FMcAN2Uo1ShQGmqsBZnNbwQv3iy%2FsAGUBQ%3D&reserved=0> and @sandeepganji<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsandeepganji&data=04%7C01%7C%7C42c90040eba3421c0c6a08d9a853efe4%7C1a407a2d76754d178692b3ac285306e4%7C0%7C0%7C637725900722274285%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=P896BN%2BURBa7cZO1K51EM07GIcuwOTyfhF%2Fx9QHjSng%3D&reserved=0> can either of you explain this discrepancy between RepetitionTime (0018,0080) versus both TriggerTime (0018,1060) and AcquisitionTime (0008,0032). RepetitionTime reports 3000ms for all slices, which seems plausible for a 48-slice resting state sequence acquired on a 3T MRI (acquired before the advent of multi-band). However, the TriggerTime and AcquisitionTime both reliably describe 6000ms between the start of one volume and the beginning of the next. In my experience, the latter measures are more reliable on Philips equipment as they account for delays due to prospect. motion corr.. However, these effects are typically on the order of ~17ms per volume. Any clue for what might cause such a discrepancy.

First slice, first volume (1):

(0008,0032) TM [161415.17]  #  10 AcquisitionTime

(0008,0033) TM [161415.17]  #  10 ContentTime

(0018,0080) DS [3000]       #   4 RepetitionTime

(0018,0081) DS [30.001]     #   6 EchoTime

(0018,0087) DS [3]          #   2 MagneticFieldStrength

(0018,1020) LO [3.2.1\3.2.1.1] #  14 SoftwareVersions

(0018,1060) DS [0]          #   2 TriggerTime

(0008,1090) LO [Intera]     #   6 ManufacturerModelName

(0020,0013) IS [1]          #   2 InstanceNumber

(0020,0100) IS [1]          #   2 TemporalPositionIdentifier

(2001,100a) IS [1]          #   2 SliceNumberMrPhilips

First slice, final volume (140):

(0008,0032) TM [162812.17]  #  10 AcquisitionTime

(0008,0033) TM [162812.17]  #  10 ContentTime

(0018,0080) DS [3000]       #   4 RepetitionTime

(0018,0081) DS [30.001]     #   6 EchoTime

(0018,0087) DS [3]          #   2 MagneticFieldStrength

(0018,1020) LO [3.2.1\3.2.1.1] #  14 SoftwareVersions

(0018,1060) DS [837000]     #   6 TriggerTime

(0008,1090) LO [Intera]     #   6 ManufacturerModelName

(0020,0013) IS [140]        #   4 InstanceNumber

(0020,0100) IS [140]        #   4 TemporalPositionIdentifier

(2001,100a) IS [1]          #   2 SliceNumberMrPhilips

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frordenlab%2Fdcm2niix%2Fissues%2F560&data=04%7C01%7C%7C42c90040eba3421c0c6a08d9a853efe4%7C1a407a2d76754d178692b3ac285306e4%7C0%7C0%7C637725900722284242%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2B6U2k2zb30%2ByAq3UcY7Tw79ERbpjuQCcdrieP0%2Fk%2Fc8%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIRGATY6BSJQ5ASFO4HISCLUMEXPLANCNFSM5ICC7GEQ&data=04%7C01%7C%7C42c90040eba3421c0c6a08d9a853efe4%7C1a407a2d76754d178692b3ac285306e4%7C0%7C0%7C637725900722289217%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cmbdwIgvpxUEqyJYWL3BmwdXvMCrTC4pibaEXpj%2BerA%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C42c90040eba3421c0c6a08d9a853efe4%7C1a407a2d76754d178692b3ac285306e4%7C0%7C0%7C637725900722299175%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Dl4LOfxPu%2Bx7ym8MrN2iuuPgkLa2tF50gHu1rYxAcWI%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C42c90040eba3421c0c6a08d9a853efe4%7C1a407a2d76754d178692b3ac285306e4%7C0%7C0%7C637725900722304153%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BUoawWeZjffjDE7RzhQ%2BGhOFdbu0XRAkNfsdjz4Hff4%3D&reserved=0>.

________________________________
The information contained in this message may be confidential and legally protected under applicable law. The message is intended solely for the addressee(s). If you are not the intended recipient, you are hereby notified that any use, forwarding, dissemination, or reproduction of this message is strictly prohibited and may be unlawful. If you are not the intended recipient, please contact the sender by return e-mail and destroy all copies of the original message.

**Comment by sandeepganji** [comment]
Adding to Mathew's point, here are the details for each of the tags

(0008,0032)	The time the acquisition of data that resulted in a particular image
(0008,0080)	The period of time between the beginning of a pulse sequence and the beginning of the succeeding (essentially identical) pulse sequence. For mixed sequences, this element is image dependent and differs for SE and IR images.
(0018,1060)	It is the Trigger Delay Time Time between the peak of the R-wave and the peak of the echo produced. In case of segmented k-space, the TEeff is the time between the peak of the echo that is used to cover the center of k-space.

-Sandeep

**Comment by neurolabusc** [comment]
Thanks both for your rapid response. I have updated dcm2niix to generate a warning when there is a discrepancy between the RepetitionTime and AcquisitionTime reported in the DICOMs. I am going to close this issue as there seems to be no clear way to reconcile these discrepancies. 

@xiangruili I note that dcm2niix gives precedence to AcquisitionTime over RepetitionTime, whereas dicm2nii only considers RepetitionTime. I have seen examples (e.g. Philips `prospect. motion corr.`) where these values are different and AcquisitionTime is correct. It might be worth testing the AcquisitionTime difference between the first and last values to detect discrepancies.
