### ISSUE TITLE
Can DWI b-values be determined from metadata?

### ISSUE THREAD

**Issue by dlevitas** [rordenlab/dcm2niix#561]
I have some multi-shell DWI data where I'm attempting to generate an image for each shell. I've been told that the data contains two shells (not including b=0 volumes): 1000, 2500. However, the bvals contains a bit of variation:

`5 995 2495 995 2505 1000 2490 995 2505 990 2500 995 2490 1000 2485 1000 5 2505 995 2495 1000 2500 1000 2505 995 2485 1005 2495 1000 2500 995 2505 5 1005 2500 995 2485 995 2495 1005 2500 1000 2485 995 2500 1000 2500 990 5 2505 1000 2490 1005 2495 1000 2485 990 2495 1000 2500 1000 2485 995 2490 5 1005 2505 1000 2500 1005 2510 1000 2505 995 2495 995 2500 1000 2500 995`

I'm curious whether the desired bvals can be found in the DICOM metadata or if I need to simply rely on the values in the .bval file?  I see that there are several tags pertaining to bvals:

```
(0018,9087) Diffusion b-value
(0018,9602) Diffusion b-value XX 
(0018,9603) Diffusion b-value XY 
(0018,9604) Diffusion b-value XZ 
(0018,9605) Diffusion b-value YY
(0018,9606) Diffusion b-value YZ
(0018,9607) Diffusion b-value ZZ
```

But I assume these are private tags, as I'm unable to access them in my DICOMs. Nothing in the dcm2niix json files seems to provide any information relating to these fields either.

**Comment by neurolabusc** [comment]
1. [dcm2niix reports the gradients as applied, not requested](https://www.nitrc.org/forum/forum.php?thread_id=6220&forum_id=4703). Due to the physical configuration of your gradients, the applied gradients are not always precisely what was requested. The values reported by dcm2niix are a more accurate representation of the data and are the values that should be used for subsequent analyses.

2. A [simple example](https://github.com/rordenlab/dcm2niix/issues/265) demonstrates that the B_matrix is underspecified to store the polarity of the B_vector. Consider the B_vector [1, 0,0] and its polar opposite [-1,0,0]: both create the B_matrix [1,0,0; 0, 0,0; 0,0,0]. Therefore, given only this B_matrix it is impossible to determine the polarity. While an opposite polarity will fit an identical tensor, the polarity is leveraged by Eddy to remove artifacts. 
3. 
4. 3. B-value specification [depends on manufacturer](https://www.na-mic.org/wiki/NAMIC_Wiki:DTI:DICOM_for_DWI_and_DTI#Private_vendor:_Siemens). dcm2niix keeps vendor specific notes for [Canon/Toshiba](https://github.com/rordenlab/dcm2niix/tree/master/Canon), [Philips](https://github.com/rordenlab/dcm2niix/tree/master/Philips), [Siemens](https://github.com/rordenlab/dcm2niix/tree/master/Siemens), and [UIH](https://github.com/rordenlab/dcm2niix/tree/master/UIH).

**Comment by dlevitas** [comment]
Understand, thanks!
