### ISSUE TITLE
GE "TotalReadoutTime" set to inf resulting in JSONDecodeError

### ISSUE THREAD

**Issue by Arshitha** [rordenlab/dcm2niix#566]
Hi - I'm using dcm2niix v1.0.20211006 with the following "-ba y" option. Some of the sidecars have `"TotalReadoutTime": inf,` which results in a JSONDecodeError. I'm mostly involved in curation of the dataset so I'm not sure why the field is 'inf' but my understanding from the BIDS spec is that it's expecting a number with units as seconds. I was wondering how if y'all had any recommendations on how to deal with it? 

```
{
	"Modality": "MR",
	"MagneticFieldStrength": 3,
	"ImagingFrequency": 127.697,
	"Manufacturer": "GE",
	"InternalPulseSequenceName": "EPI2",
	"ManufacturersModelName": "DISCOVERY MR750",
	"BodyPartExamined": "BRAIN",
	"PatientPosition": "HFS",
	"ProcedureStepDescription": "MRI Brain",
	"SoftwareVersions": "27\\LX\\MR Software release:DV26.0_R01_1725.a",
	"MRAcquisitionType": "2D",
	"SeriesDescription": "Trace",
	"ProtocolName": "ADNI3 FMRIF Enhanced Pro",
	"ScanningSequence": "EP\\SE",
	"SequenceVariant": "NONE",
	"ScanOptions": "SAT_GEMS\\EPI_GEMS\\FILTERED_GEMS\\ACC_GEMS\\PFF\\FS",
	"ImageType": ["DERIVED", "SECONDARY", "PROCESSED"],
	"RawImage": false,
	"SeriesNumber": 750,
	"AcquisitionNumber": 1,
	"SliceThickness": 2,
	"SAR": 0.470471,
	"EchoTime": 0.0618,
	"RepetitionTime": 7.8,
	"FlipAngle": 90,
	"CoilString": "32Ch Head",
	"PercentPhaseFOV": 100,
	"PercentSampling": 100,
	"AcquisitionMatrixPE": 116,
	"ReconMatrixPE": 128,
	"TotalReadoutTime": inf,
	"PixelBandwidth": 3906.25,
	"PhaseEncodingAxis": "j",
	"ImageOrientationPatientDICOM": [
		1,
		0,
		0,
		0,
		1,
		0	],
	"InPlanePhaseEncodingDirectionDICOM": "COL",
	"ConversionSoftware": "dcm2niix",
	"ConversionSoftwareVersion": "v1.0.20211006"
}
```

_Originally posted by @Arshitha in https://github.com/rordenlab/dcm2niix/issues/531#issuecomment-991974679_

**Comment by Arshitha** [comment]
@neurolabusc - Thanks for your response! I have access to the dicom files but I'm not sure if it's okay to share them via DropBox/GDrive but I've messaged our team lead about it so once I hear back from him, I'll update the issue. And apologies for the cross posting.

**Comment by neurolabusc** [comment]
Are these images generated by GE, or are they DICOMs generated by the ADNI group that simulate GE DICOM images? If the latter, you should follow @captainnova's  [advice](https://neurostars.org/t/please-contact-adnis-ask-the-experts-page-if-you-find-a-flaw-with-adni-data/20315) and use the ADNI [ask-experts](http://adni.loni.usc.edu/support/experts-knowledge-base/ask-experts/) page.

I believe that a lot of ADNI data acquired on GE scanners pre-dated the availability of GE's HyperBand. Therefore, the ADNI team acquired data using research sequences and built their own DICOMs. These simulated GE DICOMs lack much of the meta data of real GE data. This is a limitation of ADNI images, not dcm2niix.

-----
If you can not share the files, there are a couple things you could try. 

1. Has your issue been resolved with the current development release? You can build a copy locally to test. 

```
git clone --branch development https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console
make
```

When you run this development version it will report being version `v1.0.20211010`.

2. You could look at the verbose output of dcm2niix and determine the parameters that are causing the incorrect TotalReadoutTime using the [GE formula](https://github.com/rordenlab/dcm2niix/tree/master/GE). Since the verbose output is so extensive, I would suggest isolating a single file from the problematic sequence. This can be done in two steps:

- Run the command `dcm2niix -r y /path/to/DICOMs` - this will rename the DICOM files based on their series number, protocol name, etc. This allows you to identify a single DICOM file from the series that is causing you issue (ADNI3 FMRIF Enhanced Pro).
- Run the command `dcm2niix -v 2 -b I /path/to/single/DICOM`. This will generate a huge amount of meta data to the command line, revealing what dcm2niix sees.

**Comment by captainnova** [comment]
Hi,

ADNI questions are indeed welcome on the ADNI ask the experts page, but I
am not aware of any simulated hyperband data made by ADNI. Maybe it was
some other study?

We have been getting ready to use hyperband for ADNI 4, but I didn't
simulate anything, and was not expecting the test data to get mixed in with
normal data. If that happened, please provide details so we can correct it.

Thanks,

Rob

**Comment by neurolabusc** [comment]
mea culpa. @captainnova you are correct. I was thinking of the [ABCD](https://neurostars.org/t/abcd-ge-data-and-phase-encoding/4972/3) datasets.

 Regardless, the JSON suggests this is from ADNI3, so perhaps some anonymization stage tripped this up. Presumably, if we can get the ADNI3 participant details we can resolve this.

**Comment by captainnova** [comment]
Phew! That's a relief.

But I notice the series is a derived TRACE, which is an average of the diffusion weighted volumes. @neurolabusc's missing value hypothesis likely still applies if "simulated" is replaced with "derived". I guess the TotalReadoutTime of a Trace should match its source dMRI, but it would not surprise me at all if the Trace DICOM does not include that info. Derived images are often "missing" info in their DICOM headers, which I think is more or less OK since they are not actual scans. In any case we have to live with it, since the high priority metadata for derived series is not necessarily the same as it is for the source images.

If this is the problem then I suggest that either dcm2niix or downstream BIDS software adapt to behave more robustly when given input which just does not have the relevant DICOM tags needed for certain BIDS fields. I don't know what the appropriate "nonsense" value for TotalReadoutTime should be, though. Inf is a valid number.

@Arshitha , if it is an ADNI subject I can easily examine the DICOM if given the participant ID and scan date without any need to potentially post PHI. It might not be an ADNI participant, though - many studies copy and adapt the ADNI protocol for their scans.

**Comment by neurolabusc** [comment]
@Arshitha can you test the latest commit to the development branch and confirm that it will no longer generate `inf` values for `TotalReadoutTime`.

As @captainnova noted, these are derived TRACE images and probably do not belong in a dataset. One can typically generate far better derived trace images after offline processing (de-Gibbs, de-noise, TOPUP, eddy). In general, I usually use dcm2niix with th `-i y` option to ignore derived images.

**Comment by Arshitha** [comment]
Hi @neurolabusc - sorry for the delay in my response. I couldn't get back to testing your suggestions until today but I'm going to test the latest commit and get back to you with an update by tonight.

And as @captainnova mentioned, there are few "DERIVED_SECONDARY_PROCESSED" scans with series descriptions, "Trace", "AvDc", "Fa", etc, and have the `TotalReadoutTime` as inf. In the interest sharing as much data as possible in BIDS format, we currently include these scans within `sourcedata/unspecified/derived` director. 

Thank you for mentioning the `-i y` option! I haven't tried it before but it'd definitely make my life easier.

**Comment by Arshitha** [comment]
Hi @neurolabusc - I tested the commit https://github.com/rordenlab/dcm2niix/commit/e16904ec3d070dee997e417356979586cebf657d and I can confirm that I no longer see `inf` values in the json sidecars for the derived images. Thanks a ton for helping understand what was causing this issue better. It was helpful to refer to the [GE formula](https://github.com/rordenlab/dcm2niix/tree/master/GE) in this document about how TotalReadoutTime is calculated.
