### ISSUE TITLE
bval and bvec files not generated from GE DWI dicoms

### ISSUE THREAD

**Issue by dlevitas** [rordenlab/dcm2niix#574]
I received some DICOMS that I'm told are DWI with 64 directions, 4 B0 volumes, 30 with b=1000, 30 with b=2000. Using the most recent dcm2niix version however does not generate the corresponding bval and bvec files. I also do not see "DIFFUSION" in the `ImageType` metadata field, but that may not matter. My hunch is that the dicoms are somehow impoverished, but wanted to check. I've shared the dicoms through Google Drive.

cc'ing @giulia-berto

**Comment by mr-jaemin** [comment]
For GE, raw images will be always generated for DTI. To generate a FA/ADC maps, one needs to add "Post-Processing" (inline) task (either console or protocol) as shown below. Then, **"separate"** series will be generated besides the raw images series.

DICOM private tag (0x0043,0x1030) (Vas collapse flag [SS]) should be 14 or 16 for raw images:
T2 (i.e b0 specified by "# of T2" in the console) = 14
DTI (dwi) = 16
FA=18
Trace(T2W)=19

Also, for derived maps, the Image Type (0008,0008) should report [DERIVED\SECONDARY\PROCESSED] 

![Screen Shot 2022-01-20 at 10 50 36 AM](https://user-images.githubusercontent.com/72111485/150373312-39095ba7-966a-4d41-bca8-5b6aa7051c52.png)
![Screen Shot 2022-01-20 at 10 38 01 AM](https://user-images.githubusercontent.com/72111485/150373132-d5986ec4-e217-4dce-84ee-fee21093678c.png)
![Screen Shot 2022-01-20 at 10 38 20 AM](https://user-images.githubusercontent.com/72111485/150373143-0b4b3ecc-2103-438f-8485-cb5b3e378d1a.png)
![Screen Shot 2022-01-20 at 10 38 34 AM](https://user-images.githubusercontent.com/72111485/150373154-78d4bf3a-6ad0-4373-9fd0-d961353706dc.png)

![Screen Shot 2022-01-20 at 10 55 54 AM](https://user-images.githubusercontent.com/72111485/150374325-407488c9-fca0-4af8-bc6e-e1dc6ef840a0.png)

**Comment by neurolabusc** [comment]
Thanks @mr-jaemin. The sample dataset I was provided lacks all private tags, so I am unable to report 0043,1030. Perhaps these were removed by an anonymization step. The Image Type does report Primary, so perhaps these derived images were created by some other tool. @dlevitas I suggest the provenance of these images is established.  

As an aside, I notice that these images were touched by dcm4che. Be aware that dcm4che can [obfuscate the private tags of every DICOM image it touches](https://github.com/neurolabusc/dcm_qa_agfa). On one hand, your images are immune to these consequences, as they have stripped out all private tags. On the other hand, tools like dcm2niix [require private tags](https://github.com/rordenlab/dcm2niix/tree/master/GE) to identify many sequence settings, including those related to diffusion. You may want to evaluate using [dcmtk](https://github.com/DCMTK/dcmtk) instead of dcm4che. The downside of dcmtk is that while it is free as in dollars, it is not free as in freedom. However, the optional professional extensions have allowed the developers to create an outstanding tool.

**Comment by dlevitas** [comment]
Thanks @neurolabusc and @mr-jaemin. Since these images appear to be derived and anonymized to some degree, this addresses my original question. @giulia-berto and I will look into their provenances.

**Comment by giulia-berto** [comment]
Thank you all for the help! Unfortunately I didn't acquire the data, thus I'd need to figure it out.
