### ISSUE TITLE
CMAKE Syntax error:  SuperBuild/SuperBuild.cmake:32

### ISSUE THREAD

**Issue by toomanycats** [rordenlab/dcm2niix#601]
Syntax error in  `SuperBuild/SuperBuild.cmake` line 32.
GIT Tag: v1.0.20211006
cmake version 2.8.12.2

Cloned the release, stepped inside the directory, created `build` and stepped into that. Ran `cmake ..` and got the error below for line 32 of `SuperBuild/SuperBuild.cmake`.

Was able to fix it by removing line continuations `\` and made the message one long string.

```
CMake Error at SuperBuild/SuperBuild.cmake:32 (message):
  Syntax error in cmake code at

    /home/vhasfccuneod/dcm2niix/SuperBuild/SuperBuild.cmake:33

  when parsing string

    \"USE_STATIC_RUNTIME\" set to ON but \"libstdc++.a\" not found! Set it to OFF or \
                   \"yum install libstdc++-static\" to resolve the error.

  syntax error, unexpected cal_SYMBOL, expecting $end (101)
Call Stack (most recent call first):
  CMakeLists.txt:9 (include
```)

**Comment by neurolabusc** [comment]
I will let @ningfei respond. I note you are building from the stable branch, and Github rules have changed. I suspect building from the development branch will succeed.

**Comment by neurolabusc** [comment]
This reflects changes made by Github since the last stable release. You can either wait for the next stable release (currently being tested), use the development release, or use `make` to compile the last stable release. Unlike `cmake`, the `make` only uses source code provided. The downside is that it does not support a few transfer syntaxes (JPEG2000, JPEG-LS), but these are very rare (and indeed support for these is not required by DICOM conformant tools).

```
curl -fLO https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20211006.zip
unzip v1.0.20211006.zip
cd ./dcm2niix-1.0.20211006/console
make
```
