### ISSUE TITLE
seg fault when trying to convert a large number of files

### ISSUE THREAD

**Issue by david-wb** [rordenlab/dcm2niix#604]
Hi, thanks for this tool! 

I'm trying to convert around 500 chest CT scans from `.dcm` to `nii.gz`. Unfortunately, I'm getting a seg fault like this:

```bash
$ dcm2niix -e y -o niis/ -z y ./dicoms/
Chris Rorden's dcm2niiX version v1.0.20211006  GCC9.4.0 x86-64 (64-bit Linux)
Found 109894 DICOM file(s)
Segmentation fault
```

Any help would be much appreciated.

**Comment by hanayik** [comment]
Hi, could you try again and use the `-v 2` flag to see if more info can be captured?

**Comment by david-wb** [comment]
I tried and unfortunately the process showed no output for so long I had to kill it. This tool seems to have some difficulty when processing a large number of dcm series.

I ended up using the `dicom2nifti` python package and wrote a script to convert each dcm series one at a time, so I am unblocked. Feel free to close this issue.

**Comment by neurolabusc** [comment]
I am glad you found a solution. Would it be possible for you to zip all the DICOMs into a single file and share via Google drive (you can send a link to my [institutional email](https://sc.edu/study/colleges_schools/artsandsciences/psychology/our_people/directory/rorden_chris.php). It would be nice to understand what is happening.

**Comment by david-wb** [comment]
Unfortunately, that zip file would be over 1TB so it's a bit difficult for me to move the data around like that.

**Comment by neurolabusc** [comment]
Any tool will be much slower to sort through huge folders with multiple datasets than data that is sorted into smaller, coherent groups I would always suggest processing data from one session at a time. One trick you might try is `dcm2niix -r y /path/to/DICOMS` - this will simply rename rather than convert the data. It sorts each session into a separate folder, which makes subsequent conversion much easier.
