### ISSUE TITLE
Adding more info to the BIDS sidecar

### ISSUE THREAD

**Issue by dangom** [rordenlab/dcm2niix#61]
Is there a possibility of adding (or configuring) what information is added to the BIDS sidecar?

The reason I am asking this question is because I have multiple field maps, and I want to be able to distinguish them without depending on their filenames or on the DICOMs from which they came.

Ideally I'd add the acquisition time or date, and then convert that information with another tool into the proper BIDS "IntendedFor" field.

**Comment by chrisfilo** [comment]
There is some preliminary work on this:
https://github.com/rordenlab/dcm2niix/blob/f3eb44230fcb665c19cb6a4ae9d2e5f2d9bbee91/console/nii_dicom_batch.cpp#L371

It's currently missing a conversion step that would represent dates and times in the ISO8601 date-time format (and that's why it's commented out). I would also suggest combining date and time into one field AcqusitionDateTime.

Maybe you could help us getting this finished and submit a PR? It would be a great help.

**Comment by dangom** [comment]
Not the greatest C programmer here, but got the AcquisitionDateTime to work with help from [SO](http://stackoverflow.com/questions/40620806/converting-date-to-iso8601-from-char-array).
