### ISSUE TITLE
Difference between `dcm2niix` and `SimpleITK`

### ISSUE THREAD

**Issue by ramonemiliani93** [rordenlab/dcm2niix#615]
Hi! I am having a bit of confusion dealing with orientations. I have a DICOM series which I converted to Nifti using `dcm2niix` and did the same process using `SimpleITK`. Using `dcm2niix` was straightforward and the script for `SimpleITK` is something similar to this:
```python
import SimpleITK as sitk

reader = sitk.ImageSeriesReader()
file_names = reader.GetGDCMSeriesFileNames(in_folder)
reader.SetFileNames(file_names)
sitk_image = reader.Execute()

sitk.WriteImage(sitk_image, out_file)  # `out_file` with `.nii.gz` extension.
``` 
I was expecting that when I read the images with `Nibabel` both resulting Nifti files would have the same affine but for my surprise this didn't happen. The sample image I tried is [here](https://data.idoimaging.com/dicom/1010_brain_mr/1010_brain_mr_04_lee.zip). Wouldn't the process of converting the DICOM series to Nifti have only one way of doing it?

 I was going through the resources linked on the library, [The First Step for Neuroimaging Data Analysis: DICOM to NIfTI conversion](https://discovery.ucl.ac.uk/id/eprint/1495621/1/Li%20et%20al%20The%20first%20step%20for%20neuroimaging%20data%20analysis%20-%20DICOM%20to%20NIfTI%20conversion.pdf) and it seems that flipping the first two rows of the affine would suffice. I would very much appreciate if you could point me to a couple of resources on what is happening under the hood and why the differences on the outputs.
 
 Thanks!

**Comment by neurolabusc** [comment]
There are 48 ways to losslessly [transpose](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html) and [flip](https://numpy.org/doc/stable/reference/generated/numpy.flip.html) the rows, columns and slice of a 3D array. Here is an example of the same NIfTI image stored [in all 48 permutations](https://github.com/rordenlab/NIfTIspace). Note that in each of these cases the affine stores the spatial frame of reference. 

Since the 48 permutations are lossless, a converts choice between them is arbitrary and can explain differences between different converters. The dcm2niix method for converting DICOMs to NIfTI is to flip the order of the rows. This is because DICOM images have the first row at the top of the screen with subsequent rows below (the way we write English) while the NIfTI assumption is that the first row is at bottom of the screen with higher rows above it (the way we draw the y axes of a Cartesian graph). The dcm2niix manual describes the different [coordinate systems](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Spatial_Coordinates), with NIfTI using [RAS](https://brainder.org/2012/09/23/the-nifti-file-format/). Note that dcm2niix will also losslessly rotate 3D acquisitions to roughly match the NIfTI RAS identity matrix. However, 2D acquisitions are not flipped this way as the BIDS standard requires slice timing to correspond with how the 3rd dimension is stored on disk.

**Comment by neurolabusc** [comment]
In contrast SimpleITK [GetGDCMSeriesFileNames](https://discourse.itk.org/t/getgdcmseriesfilenames-ordering-of-the-returned-files/4369/4) slices are sorted by Image Position (Patient) along the slice normal.

**Comment by fepegar** [comment]
[Just sharing a working link for [The first step for neuroimaging data analysis: DICOM to NIfTI conversion](https://pubmed.ncbi.nlm.nih.gov/26945974/)]
