### ISSUE TITLE
GE multi-echo fMRI data converted to run-01, run-02 instead of run-01_echo-01, run-01_echo-02, etc.

### ISSUE THREAD

**Issue by weberam2** [rordenlab/dcm2niix#621]
**Describe the bug**

I have acquired some multi-echo fMRI data on a 3T GE Discovery 750
When I go to convert this to nifit and bids, the echoes are interpreted as separate runs, instead of the same run with separate echoes

**To reproduce**

My BIDSconfig file is:

```
{
  "dcm2niixOptions": "-b y -ba y -z y -f '%3s_%f_%d_%r'",
  "descriptions": [
    {
      "dataType": "anat",
      "modalityLabel": "T1w",
      "criteria": {
        "SidecarFilename": "003*"
      }
    },
    {
      "dataType": "anat",
      "modalityLabel": "T2w",
      "criteria": {
        "SidecarFilename": "004*"
      }
    },
    {
      "dataType": "func",
      "modalityLabel": "bold",
      "customLabels": "dir-AP_task-rest",
      "criteria": {
        "SidecarFilename": "005*"
      },
      "TaskName": "rest"
    },
    {
      "dataType": "func",
      "modalityLabel": "bold",
      "customLabels": "dir-AP_task-rest",
      "criteria": {
        "SidecarFilename": "009*"
      },
      "TaskName": "rest"
    },
    {
      "dataType": "fmap",
      "modalityLabel": "epi",
      "customLabels": "dir-AP",
      "criteria": {
        "SidecarFilename": "100*"
      },
      "IntendedFor": [
        2,
        3
      ],
      "B0FieldIdentifier": "pepolar_fmap0"
    },
    {
      "dataType": "fmap",
      "modalityLabel": "epi",
      "customLabels": "dir-PA",
      "criteria": {
        "SidecarFilename": "008*"
      },
      "IntendedFor": [
        2,
        3
      ],
      "B0FieldIdentifier": "pepolar_fmap0"
    }
  ]
}
```
I then run

dcm2bids with the above config file and it seems dcm2niix thinks the echoes are separate runs...

**Expected behavior**

Instead of separate runs, I'd like it to be interpreted as one run, but separate echoes "run-01_echo-01" "run-01_echo-02" etc.

**Version**

Please report the complete version string:

`Chris Rorden's dcm2niiX version v1.0.20211006  (JP2:OpenJPEG) (JP-LS:CharLS) GCC7.5.0 x86-64 (64-bit Linux)
v1.0.20211006`

**Comment by neurolabusc** [comment]
Your issue appears to be with the [Dcm2Bids](https://github.com/UNFmontreal/Dcm2Bids) wrapper, not dcm2niix. Therefore, this needs to be fixed in that repository.

Reference conventional GE [B0 fieldmaps are here](https://github.com/neurolabusc/dcm_qa_fmap), while examples of using GE scanners to acquire phase polarity reversed images [are here](https://github.com/neurolabusc/dcm_qa_polar). Be aware that the latter research kludges create unusual DICOM images. While dcm2niix includes a kludge to attempt to handle these images, one needs to exercise extreme caution when the core DICOM images are not strictly truthful.

**Comment by weberam2** [comment]
I'll post my issue there
Thank you Crhis!
