### ISSUE TITLE
Some questions about United Imaging

### ISSUE THREAD

**Issue by githubcooperation** [rordenlab/dcm2niix#625]
Dear all,
I am wondering if dcm2niix is compatible for the DICOM files from United Imaging MRI scanners.

**Comment by neurolabusc** [comment]
Yes, see [here](https://github.com/rordenlab/dcm2niix/tree/master/UIH) for details, and see the [validation dataset](https://github.com/neurolabusc/dcm_qa_uih). As I do not have access to this hardware, and because it may be evolving, I would suggest users to validate their own datasets carefully and report any issues.
