### ISSUE TITLE
Chris Rorden's dcm2niiX version v1.0.20220720  GCC10.4.0 x86-64 (64-bit Linux) Found 48 DICOM file(s) Warning: Unsupported transfer syntax '1.2.840.10008.1.2.4.90'

### ISSUE THREAD

**Issue by chke097** [rordenlab/dcm2niix#630]
Hello, while using DCM2NIIX to convert images, a Warning appears: Unsupported transfer syntax '1.2.840.10008.1.2.4.90,.
  I guess the version of DCM2NIIX is not compiled, but I don't know how to install the compiled version of DCM2NIIX on Linux server. 
  Could you please tell me the complete operation order? Thank you！

**Comment by neurolabusc** [comment]
You need to run a version of dcm2niix compiled to support [JPEG2000](https://www.dicomlibrary.com/dicom/transfer-syntax/), this will appear as `JP2:OpenJPEG` in the first line of output when dcm2niix is executed.

To get a pre-compiled version with JP2 support:

```
$ curl -fLO https://github.com/rordenlab/dcm2niix/releases/latest/download/dcm2niix_lnx.zip
$ unzip dcm2niix_lnx.zip 
$ ./dcm2niix
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) (JP-LS:CharLS) GCC5.5.0 x86-64 (64-bit Linux)
```

To compile with JP2 support:

```
$ git clone https://github.com/rordenlab/dcm2niix.git
$ cd dcm2niix
$ mkdir build && cd build
$ cmake -DZLIB_IMPLEMENTATION=Cloudflare -DUSE_JPEGLS=ON -DUSE_OPENJPEG=ON ..
$ make
$ ./bin/dcm2niix
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) (JP-LS:CharLS) GCC9.4.0 x86-64 (64-bit Linux)
```

**Comment by IWamelink** [comment]
Hi neurolabusc, is there a way to also install it as a python package?

I'm receiving the same Warning: Unsupported transfer syntax '1.2.840.10008.1.2.4.90'.
I'm running this version: Chris Rorden's dcm2niiX version v1.0.20201102  GCC7.5.0 x86-64 (64-bit Linux). A search on Google also told me that it needs to say OpenJPEG to be able to handle the syntax as described above (or apparently JP2:OpenJPEG).
However, I have been unable to install the right dcm2niix package in my conda environment.

Could you possibly point me in the right direction?

**Comment by neurolabusc** [comment]
@IWamelink you are correct that the [conda idcm2niix install](https://anaconda.org/conda-forge/dcm2niix) does not include JPEG2000 support

```
$ conda install -c conda-forge dcm2niix
$ which dcm2niix
/home/chris/miniconda3/bin/dcm2niix
$ dcm2niix -v
Chris Rorden's dcm2niiX version v1.0.20220720  GCC10.4.0 x86-64 (64-bit Linux)
```

This is outside my expertise. Perhaps @hanayik or @ningfei can help. You may want to create an issue or pull request with the [feedstock](https://github.com/conda-forge/dcm2niix-feedstock.

If possible, you may want to check the provenance of your images and see if you can store the raw DICOMs instead of using JPEG2000. You need to be aware that the DICOM standard does not require any tool to support compressed images, so using compression can cause issues.The  [OpenJPEG library](https://crnl.readthedocs.io/jpeg_formats/index.html) lossless JPEG 2000 is exceptionally slow and has poor compression performance. For archival quality DICOM, I would use disk based compression instead.

The OpenJPEG library also has some quirks, and to handle this gdcm depends on its own hacked version but does not differentiate the installation name, so if you install gdcm (which is terrific) it can disrupt other tools that dynamically link to the OpenJPEG library. For this reason, it is probably a good idea to statically link to that library.
