### ISSUE TITLE
Are b-vectors wrong unless row order is preserved?

### ISSUE THREAD

**Issue by samcoveney** [rordenlab/dcm2niix#643]
When converting a DWI series, the default behaviour of dcm2niix is to flip the row order (so that the second dimension is stored in reverse). This can be prevented using the option "-y n".

I believe that the bvec files are not orientated correctly in the default case where row flipping is applied. The bvec files are stored in image coordinates, but in order to have the tensors orientated correctly when plotted requires that the bvecs y-dimensions be flipped (multiplied by -1). This is not the case if "-y n" is used.

If the bvecs are in the image coordinate system, surely flipping the y-ordering of the data saved to disk should also result in flipping the y-dimension of the bvecs?

Chris Rorden's dcm2niiX version v1.0.20181125  (JP2:OpenJPEG) GCC9.3.0 (64-bit Linux)

**Comment by neurolabusc** [comment]
In future, please follow the dcm2niix issue template:

```
Please try the following steps to resolve your issue:

 - Is this the [latest stable release](https://github.com/rordenlab/dcm2niix/releases)? If not, does the latest stable release resolve your issue?
 ```

You are using the Fall 2018 stable release, rather than a [current release](https://github.com/rordenlab/dcm2niix/releases) from 2022. Prior to this, the undcoumented argument `-y n` would flip the row polarity in the bvec files if the row order was flipped, but it would not flip the column polarity. The current release incorporates a [commit](https://github.com/rordenlab/dcm2niix/commit/6e513689716380652e0584fb3ad2806c380a464d) such that flipping image row order flips both the row and vector polarity of the unintuitive requirement of the FSL bvec format to flip bvec column order if the image space has a positive determinant described [here](http://justinblaber.org/brief-introduction-to-dwmri/) and [here](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FDT/FAQ#What_conventions_do_the_bvecs_use.3F). 

You can demonstrate this works by [processing sample datasets for any manufacturer linked in the dcm2niix wiki](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Diffusion_Tensor_Imaging) using FSL. The wiki includes a `dedicated document` that describes bvec validation.

I think what is confusing you is that dcm2niix bvecs are stored in FSL [NIfTI image space](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Spatial_Coordinates) format, as required by BIDS. Remember that NIfTI images store images with the first row at the bottom of the screen and tiger values higher on the screen, the way we draw a cartesian graph. In contrast, for DICOM the first row is at the top of the screen, with subsequent rows below it, the way we write English.

**Comment by samcoveney** [comment]
Thanks very much for these comments and links, they have been very useful. Using the new version, I appear to be getting the correct results. However, the tensors appear to have the z-axis flipped the wrong way if I plot a data slice (using tensors) in a right-hand 3D plotting tool. Is this because the radiological convention, while RAS, is still a left-handed system, such that it is then the users responsibility to handle this during plotting?

**Comment by neurolabusc** [comment]
Your tensor fitting or visualization tools do not seem compatible with the FSL format. Be aware that different tools have different [conventions](https://community.mrtrix.org/t/vector-orientation-mismatch-between-fsl-mrtrix/1084/7). dcm2niix creates FSL compliant vectors, which was adopted by BIDS.

```
git clone https://github.com/neurolabusc/dcm_qa_philips
cd dcm_qa_philips/ref
dtifit  --save_tensor --data=dti_1101.nii --mask=dti_1101.nii --out=new --bvecs=dti_1101.bvec --bvals=dti_1101.bval
```

![fsleyesx](https://user-images.githubusercontent.com/8930807/198055628-fe7e650e-656f-4edb-a585-dd3435a9e99c.png)

**Comment by samcoveney** [comment]
I think you are probably correct. Thanks again for all your help
