### ISSUE TITLE
Warnings in Ubuntu 16.04

### ISSUE THREAD

**Issue by ericbarnhill** [rordenlab/dcm2niix#65]
Hi I am getting some warnings during make, some appear to be for use of printf, not sure about the others. I compiled with batch_mode turned on which was not the default. One example:

    /home/ericbarnhill/Documents/code/dcm2niix/console/nii_dicom.cpp: In function ‘TJPEG* 
    decode_JPEG_SOF_0XC3_stack(const char*, int, bool, int, bool)’:
    /home/ericbarnhill/Documents/code/dcm2niix/console/nii_dicom.cpp:2301:37: warning: ignoring return
    value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result     

Target was built. Do I need to worry about this?

**Comment by neurolabusc** [comment]
This is your compiler being overly pedantic. The compilers on my MacOS computer do not generate any warnings (Apple LLVM version 7.3.0 / clang-703.0.31; gcc version 6.1.0). If you want to post the whole list of warnings, I can go through the list and update the code so it does not generate any warnings. 

I have just updated the code so it should reduce a few of these warnings, but since I do not have a complete list I am sure I have missed a few.
