### ISSUE TITLE
catastrophic error with large par/rec file including phase data

### ISSUE THREAD

**Issue by gjheij** [rordenlab/dcm2niix#659]
**Describe the bug**

`dcm2niix` throws a `catastrophic error` when dealing with large par/rec files that has both the magnitude & phase data. Interestingly, the same sequence does convert when there's less volumes in the acquisition. For instance, a run with 124 volumes does convert, while an acquisition with 230 volumes doesn't. 

**To reproduce**

1. run `dcm2niix` with: `dcm2niix -b y -f %n_%p -z o -d 0 -o ${pathOutput} -v 1 ${pathInput}`
2. *catastrophic error* (see below)

**Expected behavior**

Conversion to nifti as usual

**Output log**
```
Error: Catastrophic error: found 22540 but expected 45080 slices. ${pathInput}/su_22112022_1520187_18_1_run-1_acq-3depi_boldV4.par
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) (JP-LS:CharLS) GCC9.4.0 x86-64 (64-bit Linux)
Found 1 DICOM file(s)
Warning: dcm2niix PAR is not actively supported (hint: use dicm2nii)
  slices*grad*bval*cardiac*echo*dynamic*mix*labels = 98*1*1*1*1*230*1*1
Warning: PAR/REC intensity scaling varies between slices (please validate output).
Warning: Reported TR=44ms, measured TR=1320ms (prospect. motion corr.?)
Warning: Intensity slope/intercept varies between slices! [check resulting images]
Done reading PAR header version 4.2, with 45080 slices
```

**Version**

Please report the complete version string:
`Chris Rorden's dcm2niiX version v1.0.20190902  (JP2:OpenJPEG) GCC4.8.2 (64-bit Linux)
v1.0.20190902`
-`Chris Rorden's dcm2niiX version v1.0.20201102  (JP2:OpenJPEG) (JP-LS:CharLS) GCC5.5.0 x86-64 (64-bit Linux)
v1.0.20201102`
-`Chris Rorden's dcm2niiX version v1.0.20211006  (JP2:OpenJPEG) (JP-LS:CharLS) GCC7.5.0 x86-64 (64-bit Linux)
v1.0.20211006`
-`Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) (JP-LS:CharLS) GCC9.4.0 x86-64 (64-bit Linux)
v1.0.20220720`

**Troubleshooting**

Please try the following steps to resolve your issue:

 - Is this the [latest stable release](https://github.com/rordenlab/dcm2niix/releases)? If not, does the latest stable release resolve your issue? **No**
 - If the latest stable version fails, and you are using Windows. Does the latest commit on the development branch resolve your issue? You can get a pre-compiled version from [AppVeyor](https://ci.appveyor.com/project/neurolabusc/dcm2niix) (click on the Artifacts button). **-**
 - If the latest stable version fails, and you are using macOS or Linux. Does the latest commit on the development branch resolve your issue? You can build this using the recipe below: **No**

```
git clone --branch development https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console
g++  -I.  main_console.cpp nii_foreign.cpp nii_dicom.cpp jpg_0XC3.cpp ujpeg.cpp nifti1_io_core.cpp nii_ortho.cpp nii_dicom_batch.cpp  -o dcm2niix -DmyDisableOpenJPEG
./dcm2niix ....
```
troubleshooting as outlined above yields negative results. Additionally, to test if it was a memory issue that we could get around with, I tried submitting the `dcm2niix` to our SGE with large amounts of memory, but this also resulted in the same error.

**Comment by neurolabusc** [comment]
I do not have access to Philips data. Feel free to either generate a pull request to resolve this issue or to share a sample with my [institutional email](https://sc.edu/study/colleges_schools/artsandsciences/psychology/our_people/directory/rorden_chris.php). Where possible, I would try to export data as DICOM rather than Philips proprietary PAR/REC format. I would heed the warning of a Philips Clinical Scientist that this format is from [simpler times](https://github.com/rordenlab/dcm2niix/issues/255).

**Comment by neurolabusc** [comment]
Closing. no sample datasets to replicate issue.

**Comment by neurolabusc** [comment]
The latest commit addresses this by increasing the [kMaxSlice2D value](https://github.com/rordenlab/dcm2niix/blob/bb3a6c35d2bbac6ed95acb2cd0df65f35e79b5fb/console/nii_dicom.h#L57). While Philips limits datasets to 65535 2D slices, it is worth noting that each slice can be saved in a variety of types (magnitude, phase, real, imaginary). Unfortunately, the image type is not listed in the initial portion of the PAR header, so for a one-pass reader one must make worst case assumptions when reading this format. I have increased kMaxSlice2D to 131070, but I think the theoretical Philips limit due to the header design is 262140. The latest commit does three things: it doubles the [stack size to 16mb](https://github.com/rordenlab/dcm2niix/blob/bb3a6c35d2bbac6ed95acb2cd0df65f35e79b5fb/console/CMakeLists.txt#L50), increases the kMaxSlice2D to 131070, and it accurately reports how to resolve the issue if kMaxSlice2D is exceeded. On Windows, the default stack size is 1mb and on Unix it is 8mb, so extending this to 16mb for modern computers does not seem much of a stretch, but @ningfei may have thoughts on this.

**Comment by gjheij** [comment]
This fix works lovely on my Mac (compiled with Clang), but I'm getting a segmentation fault on Linux (compiled with gcc). What could the reason for that be?

**Comment by neurolabusc** [comment]
While we can increase the stack size using the linker for Windows and macOS, we must do it programmatically with setrlimit for Linux. I have added a new commit so the Linux version will now report when the stack size is exceeded and refer to this issue. At some stage, I may move the large arrays to the heap, but for the moment you will want to use Windows or macOS to convert these images. As described in previous issues, the par/rec format is from simpler times and neither the structure nor the implementation are ideal.

**Comment by gjheij** [comment]
Understood, thank you very much for your efforts. Much appreciated! We'll keep this in mind and give the dicom-export another go.
