### ISSUE TITLE
Errors when using dcm2niix

### ISSUE THREAD

**Issue by bmol239** [rordenlab/dcm2niix#661]
I am having a problem when converting dicom to nii. I have very new to this and have little training to understand the problem.
Dicom data is exported from our 3T Vida-Fit scanner XA50 in Enhanced dicom format.

When converting my diffusion MRI data I get the following:

"Slice timing appears corrputed (range 0..7947.5 TR=8.6ms)"

What does this mean? Is it bad?

Some diffusion files also do not have bvec or bval outputs . is that related?

I would not have expected to see any errors
See image below for current string dcm2niix
![image](https://user-images.githubusercontent.com/121001376/208348996-4850a61c-2041-4331-a4c9-e5a8215b4e72.png)

**Comment by neurolabusc** [comment]
My best guess from your description is that the data was exported off of the scanner using the [Siemens XA online anonymization](https://github.com/rordenlab/dcm2niix/issues/236). The anonymization strips out both personally identifiable information as well as sequence details such as diffusion gradient direction. This is a limitation of your impoverished DICOM images, not dcm2niix. The solution is to export your data off of the scanner in enhanced, non-anonymized mode. Assuming your data comes from a research institution (rather than a clinical setting) your center will have a Siemens Research Collaboration Manager who can help you tune your instrument and the data. I encourage you to take develop a relationship with this expert. It is their role to guide you through issues like these (and hopefully they will lobby the engineers to limit the consequences of anonymization to personally identifiable information).

The only other explanation I can think of is that the diffusion sequence was set up only to export the derived data (e.g. FA, ADC, TRACE) and not the raw data, hence the lack of sequence details and b-vectors.

**Comment by neurolabusc** [comment]
No additional information for troubleshooting. Please work with the vendor to resolve.
