### ISSUE TITLE
NITRC wiki links to neurolabusc and rordenlab

### ISSUE THREAD

**Issue by asmacdo** [rordenlab/dcm2niix#673]
In [the dcm2niix wiki Download section](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Download) it points to [this repo for releases](https://github.com/rordenlab/dcm2niix/releases) but also [this repo for building from source](https://github.com/neurolabusc/dcm2niix) 

Same issue in [dcm2niix wiki building from source section](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Building_from_source)

Is this deliberate? If not, let me know what it should be and I'll update the wiki :)

**Comment by neurolabusc** [comment]
This is intentional.

The wiki  `Download a recent release from Github` goes to the [releases](https://github.com/rordenlab/dcm2niix/releases) web page includes both source code and compiled examples.

The wiki `Build from the source code` links to the  [dcm2niix Github web page](https://github.com/rordenlab/dcm2niix) which always defaults to the `master` branch which is the latest stable release (with the `development` branch having the beta version of the next stable release). 

They are both the same latest stable release, but one link provides easy access to compiled executables while the other includes source code and compilation instructions.

Is there some way we could make this clearer for new users? I wrote the page, so it makes sense to me, but maybe it is not clear to others.

**Comment by asmacdo** [comment]
Releases vs source makes sense but I'm not quite understanding the relationship between neurolabusc and rordenlab.

It sounds like neurolabusc is "upstream" code development and rordenlab is "downstream" for releases?

**Comment by neurolabusc** [comment]
@asmacdo thanks, I now see the issue. dcm2niix was moved from a Github user account (neurolabusc) to a github organization (rordenlab) to improve collaboration across Github users. I edited the Wiki. Can you review my changes and close this issue if it resolves your issue.
