### ISSUE TITLE
Suggestion for install - why not just unzip dcm2niix and add the directory to $PATH?

### ISSUE THREAD

**Issue by dorkylever** [rordenlab/dcm2niix#683]
Something like this below:

wget  https://github.com/rordenlab/dcm2niix/releases/download/v${APP_VERSION}/dcm2niix_lnx.zip

 unzip dcm2niix_lnx.zip -d ${DATA_LIB_PATH}/dcm2niix/

export PATH=$PATH:${DATA_LIB_PATH}/${APP_NAME}

**Comment by neurolabusc** [comment]
I agree, the method listed on the [home page](https://github.com/rordenlab/dcm2niix) is the easiest for many Linux installations to install for all users:

```bash
curl -fLO https://github.com/rordenlab/dcm2niix/releases/latest/download/dcm2niix_lnx.zip
unzip dcm2niix_lnx.zip 
sudo cp dcm2niix /usr/local/bin/dcm2niix
```

or copy the executable to `$HOME/bin` for only a single user. However, some users are familiar with different package managers, so they may prefer to install dcm2niix with `pip`, or `apt`, or [as a dependency of one of the wrappers and tools the include dcm2niix](https://github.com/rordenlab/dcm2niix#links).


With regards to the `curl` command, the `latest` will always select the most recent stable release. Since the manufacturers and BIDS formats are evolving, I would always recommend the `latest` version for most users (though users of the cutting edge MRI software such as Siemens XA users may need to risk using the development branch as we reverse-engineer the latest features).

**Comment by dorkylever** [comment]
Sorry I confused the Linux instructions with the build from source but thanks Chris!
