### ISSUE TITLE
bvec values modified ?

### ISSUE THREAD

**Issue by Brainarea** [rordenlab/dcm2niix#686]
**Describe the bug**

We acquired some Multi-shell 99 DIR DTI data on a SIEMENS Prisma and used dcm2niix on it.
It seems that values in bvec files have been transformed so that :

-  all vectors have unity length
- (0,0,0) vector has been changed because b0 value is actually 5 (Siemens report value closer to "reality").

Is this accurate? Is there a way to access to unchanged data ?
I could not find any information about this. Sorry if I missed something in the documentation

**Comment by neurolabusc** [comment]
This is not a bug. The behavior is as intended. dcm2niix creates bvec/bval files in the FSL format **required** by BIDS.

Please see the [Siemens Diffusion Tensor Notes](https://github.com/rordenlab/dcm2niix/tree/master/Siemens#diffusion-tensor-notes). Gradient vectors are reported with respect to the scanner bore, and dcm2niix will attempt to re-orient these to [FSL format](http://justinblaber.org/brief-introduction-to-dwmri/) [bvec files](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FDT/FAQ#What_conventions_do_the_bvecs_use.3F). As you note, the b-values are those [acquired rather than requested](https://www.nitrc.org/forum/forum.php?thread_id=6220&forum_id=4703).

Assuming your Prisma runs E11 and you are using custom gradients, you can get the requested gradients from the .dvs files in your CustomerSeq/DiffusionVectorSets folder (though remember, the frame of reference is in scanner space, not rotated to image space). On Siemens, you always want to create your own gradient tables, as the default ones are always sampled on a half-sphere. While this reduces Eddy Current direciton, it also means [these distortions are harder to model and correct](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/eddy). See [here](https://crnl.readthedocs.io/dti/index.html) for more details.

You could also modify dcm2niix to extract the non-rotated vectors, or use a tool like [dicm2nii](https://github.com/xiangruili/dicm2nii).
