### ISSUE TITLE
"Slices not stacked" warning when converting multiecho images using dcm2niix

### ISSUE THREAD

**Issue by rvarrier** [rordenlab/dcm2niix#692]
**Describe the bug**
_Getting the warning message "Slices not stacked: echo varies (TE 14.2, 54.64; echo 1, 3). Use 'merge 2D slices' option to force stacking" when converting multi-echo DICOM images to NIFTI._

**To reproduce**
_1. Sample DICOM files from a phantom uploaded here: https://drive.google.com/drive/folders/11CHH6OOOFRzA3DYnV5sjvHpOBcdKSM_m?usp=sharing
2. Run the command 'dcm2niix -o nii/ -f %f_%d -b y output_loc input_loc' (output_loc and input_loc replaced by actual locations)_ 

**Expected behavior**
_This still generates the nifti images seemingly correctly, but also prints the aforementioned warning._

**Output log**
> Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) (JP-LS:CharLS) GCC5.5.0 x86-64 (64-bit Linux)
> Found 228 DICOM file(s)
> Slices not stacked: echo varies (TE 14.2, 54.64; echo 1, 3). Use 'merge 2D slices' option to force stacking
> Convert 76 DICOM as ./nii/dcm_func_task-animationrating_run-01_e1 (80x80x52x76)
> Convert 76 DICOM as ./nii/dcm_func_task-animationrating_run-01_e3 (80x80x52x76)
> Convert 76 DICOM as ./nii/dcm_func_task-animationrating_run-01_e2 (80x80x52x76)
> Conversion required 3.770795 seconds (1.100000 for core code).

**Version**
> Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) (JP-LS:CharLS) GCC5.5.0 x86-64 (64-bit Linux)

**Troubleshooting**
 - Is this the [latest stable release](https://github.com/rordenlab/dcm2niix/releases)? If not, does the latest stable release resolve your issue?
     -  _Yes. I had previously tried an earlier version (v202205.) on an actual brain dataset and gotten the same warning_
     
 - If the latest stable version fails, and you are using Windows. Does the latest commit on the development branch resolve your issue? You can get a pre-compiled version from [AppVeyor](https://ci.appveyor.com/project/neurolabusc/dcm2niix) (click on the Artifacts button).
     - _I am using a Mac PC._
     
 - If the latest stable version fails, and you are using macOS or Linux. Does the latest commit on the development branch resolve your issue? You can build this using the recipe below:

```
git clone --branch development https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console
g++  -I.  main_console.cpp nii_foreign.cpp nii_dicom.cpp jpg_0XC3.cpp ujpeg.cpp nifti1_io_core.cpp nii_ortho.cpp nii_dicom_batch.cpp  -o dcm2niix -DmyDisableOpenJPEG
./dcm2niix ....
```

_dcm2niix crashed unexpectedly on the Mac when I ran the command  `./dcm2niix -o output_loc -f %f_%d -b y input_loc` (input_loc and output_loc being drive locations). The Terminal output was:_ 
> 
> Compression will be faster with 'pigz' installed http://macappstore.org/pigz/
> Chris Rorden's dcm2niiX version v1.0.20230315  Clang12.0.0 x86-64 (64-bit MacOS)
> Found 228 DICOM file(s)
> zsh: segmentation fault  ./dcm2niix -o /Users/f0053cz/Documents/Psyanim_fmri_study/sample_dcm/nii/ -f 
> 

_My main question/concern is why this warning appears and if this should be a serious concern. I have collected some multi-echo scans, and such warnings show up across runs - the warning may mention echoes 1 and 3 (as above), 2 and 3 etc. in various runs. This warning also showed up when converting our data to BIDS format using @yarikoptic's code._

_Thanks in advance, 
Rekha__

**Comment by neurolabusc** [comment]
This is the expected behavior. dcm2niix is generating a warning (not an error) to tell you that a single DICOM series has been stored as multiple NIfTI files. For most fMRI and DTI data, dcm2niix will convert an entire series into a single file. However, dcm2niix will segment a series into multiple files denoted by [file naming post fixes](https://github.com/rordenlab/dcm2niix/blob/master/FILENAMING.md#file-name-post-fixes-image-disambiguation) if your sequence has variability in properties like echo time. Indeed, for your multi-echo [task imaging data the BIDS structure **requires**](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#task-including-resting-state-imaging-data) that each echo be saved as a different file using the [echo entity](https://bids-specification.readthedocs.io/en/stable/appendices/entities.html#echo). There are many ways a user might want to parse multi-echo data, and dcm2niix is simply informing you that it has chosen the BIDS-style.

As for the crash you experienced when compiling the development version, you will want to specify the correct entitlements when compiling for MacOS, the easiest way is to just call `make`:

```
git clone --branch development https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console
make
./dcm2niix ....
```

**Comment by rvarrier** [comment]
Okay this is all great to know, thank you so much!

**Comment by rvarrier** [comment]
Also `make` fixed the crash issue, and still generates the same warnings (as is to be expected based on your response above). Thanks again!
