### ISSUE TITLE
Proposal: set `SliceEncodingDirection` from `dcmmeta_slice_dim`

### ISSUE THREAD

**Issue by matthew-brett** [rordenlab/dcm2niix#771]
While working on [Xibabel](https://github.com/matthew-brett/xibabel), we noticed that there were `dcm2niix` output files where `dcmmeta_slice_dim` was set, but `SliceEncodingDirection` was not:

https://github.com/OpenNeuroDatasets/ds003466/blob/3c30031311907606163c911b3bfd379f06dc410d/sub-004/ses-01/func/sub-004_ses-01_task-motor_run-01_bold.json#L115

Would it be reasonable to use `dcmmeta_slice_dim` to fill in `SliceEncodingDirection`?

Cc @effigies (we discussed this over email).

**Comment by neurolabusc** [comment]
@matthew-brett the images created by dcm2niix are **always** [SliceEncodingDirection](https://bids-specification.readthedocs.io/en/stable/glossary.html#sliceencodingdirection-metadata) `k`:  the first index of the `SliceTiming` always refers to the first slice (not row or column) stored to disk. So I guess your suggestion is that dcm2niix should always generate the `SliceEncodingDirection` field when it populates the `SliceTiming` field. 
 ```
	"SliceEncodingDirection": "k",
```
The field `dcmmeta_slice_dim` was added by dcmstack and not dcm2niix.

**Comment by matthew-brett** [comment]
Hi - yes - I guess that is my proposal - surely better to be explicit?

**Comment by neurolabusc** [comment]
I will let @effigies decide if we should modify this. It is worth noting that the [SliceEncodingDirection field is recommended, not required](https://bids-specification.readthedocs.io/en/stable/modality-specific-files/magnetic-resonance-imaging-data.html#timing-parameters). The [specification](https://osf.io/zwmxg/download) notes that `When absent, the entries in SliceTiming must be in the order of increasing slice index as defined by the NIfTI header`. Therefore, from inception dcm2niix has supported the specification. Since the situation has not changed, my sense is that dcm2niix is accurate and I am reluctant to make changes for the sake of changes. In particular, rhis will require the automatic validations as well as the validations done by clinical teams that can not share their data to be updated.
