### ISSUE TITLE
Slice timing missing in the json file

### ISSUE THREAD

**Issue by xileniu** [rordenlab/dcm2niix#793]
**Describe the bug**
When employing the latest version of dcm2niix to convert DICOM to NIfTI format, I observed that the resulting JSON file lacked slice timing information.

**To reproduce**
1. Run the command 'dcm2niix  -o output dicomFolder'
2. See error: 
Warning: Series 17 includes partial volume (issue 742): 1 slices acquired but ICE dims (0021,118e) specifies 72
Warning: Siemens XA exported as classic not enhanced DICOM (issue 236)

I talked to people in the scanning center, they couldn't export the DICOM files in enhanced mode for these several subjects.
So, is there any chance to fix this on my end?
I attacted the json file, and the dicom files were shared in  [dropbox](https://www.dropbox.com/scl/fi/4jjdncxgjhb4sge0mqhm5/017Prototype_1.zip?rlkey=nbqqkoet1uz7gii82vbr6o6f8&dl=0) 
[.json](https://github.com/rordenlab/dcm2niix/files/14317337/017Prototype_1_Prototype_1_20221031125703_1017.json)
Thanks!

**Version**
Please report the complete version string:
Chris Rorden's dcm2niiX version v1.0.20240202  (JP2:OpenJPEG) (JP-LS:CharLS) GCC8.4.0 x86-64 (64-bit Linux)

**Comment by neurolabusc** [comment]
This is a limitation of your images, not dcm2niix.

dcm2niix assumes that the DICOM files are truthful. However, the first volume of this multiband sequence reports the single band slice timing in the private slice timing tag (0021,1104). Therefore, the reported slice times do not occur within a single TR. This issue is similar to an issue with [early versions of the CMRR multiband sequences](https://github.com/CMRR-C2P/MB/issues/29) from many years ago. I suggest you contact the team that created this sequence and have them create accurate DICOMs.

If you need the slice times, you can simply remove all the DICOM images from the first volume (you can use `dcm2niix -r y /path/to/dicoms` to rename images with the file name commencing with the instance number that can help you identify the first volume. Once the first volume is deleted, dcm2niix will create a JSON with the multi-band slice timing:

```
	"SliceTiming": [
		1.485,
		0,
		0.99,
		0.0825,
		1.0725,
		0.165,
		1.155,
		0.2475,
		1.2375,
		0.33,
		1.32,
		0.4125,
		1.4025,
		0.5775,
		1.5675,
		0.66,
		1.65,
		0.7425,
		1.7325,
		0.825,
		1.815,
		0.9075,
		1.8975,
		0.495,
		1.485,
		0,
		0.99,
		0.0825,
		1.0725,
		0.165,
		1.155,
		0.2475,
		1.2375,
		0.33,
		1.32,
		0.4125,
		1.4025,
		0.5775,
		1.5675,
		0.66,
		1.65,
		0.7425,
		1.7325,
		0.825,
		1.815,
		0.9075,
		1.8975,
		0.495,
		1.485,
		0,
		0.99,
		0.0825,
		1.0725,
		0.165,
		1.155,
		0.2475,
		1.2375,
		0.33,
		1.32,
		0.4125,
		1.4025,
		0.5775,
		1.5675,
		0.66,
		1.65,
		0.7425,
		1.7325,
		0.825,
		1.815,
		0.9075,
		1.8975,
		0.495	],
```
You could either copy this timing information to the JSON for the full series, or use just analyze the data without the first volume (if this is a task-based fMRI data, adjust event times by one TR).

**Comment by xileniu** [comment]
Thank you so much. Works for me
