### ISSUE TITLE
error dcm2niix using dcm2bids

### ISSUE THREAD

**Issue by dbg0899** [rordenlab/dcm2niix#801]
**Describe the bug**

I'm facing some problems with the conversion dcm2niix when I run dcm2bids, for other subjects, i did not have problem. Data is from Phillips scanner and version dcm2niix: april-2023. This is the error:

`Error: maxNumberOfMixes>1. Please update this software to support these images.`
`Error: Catrastophic error: found 280 but expected 420 slices (and mention the path to PARREC data)`
`Error: Unkown type 7: not magnitude [0], real [1], imaginary[2] or phase [3]`
`Error: Bizarre b-vectors 'path to parrec and B0.rec'`
and so on with some unexpected slices...
**To reproduce**

**Expected behavior**

The weird thing is that I executed some other subjects within the same version dcm2niix and everything, and it worked! 
**Output log**

At the end says: `subprocess.CalledProcessError: Command ['dcm2niix'. '-b', 'y'..., posixPath ('data path')] returned non-zero exit status 8`
**Version**

 - dcm2niix version  v1.0.20230411  (64-bit Linux)` 

Thank you so much for your help!

**Comment by neurolabusc** [comment]
@dbg0899 if you want help using the Dcm2Bids wrapper you should post an issue with that [tool](https://github.com/UNFmontreal/Dcm2Bids). If you want to post a dcm2niix issue, please follow the issue template. Specifically,  determine if the [latest stable release](https://github.com/rordenlab/dcm2niix/releases) resolves your issue.

In general, I would encourage Philips users to export data as DICOM rather than PAR/REC format unless required (e.g. Philips DICOMs have limits on maximum number of frames). The PAR/REC format is spartan and the resulting BIDS files will be necessarily underspecified. You might also want to check if this series was prematurely terminated or only partially transferred. Finally, you might find that [dicm2nii](https://github.com/xiangruili/dicm2nii) can convert PAR/REC images that dcm2niix does not support.
