### ISSUE TITLE
Inquiry on DICOM to NIfTi

### ISSUE THREAD

**Issue by mikaelhaji** [rordenlab/dcm2niix#803]
**The Bug**

I am working on a project that involves converting personal CT data to .nii. However, I came across a couple of challenges that I was hoping to get help on!

**Situation Overview**

1. I am converting DICOM files obtained from CT scans into NIfTI format. These files are stored in a directory named "Wes' CT Data" on Windows 10 system.
2. The conversion process is initiated with the following command: dcm2niix.exe -f "%f_%p_%t_%s" -p y -z n -o "C:\Users\mikae\Desktop\converted-nifti" "C:\Users\mikae\Desktop\Wes' CT Data"

**Expected behavior**

1. **Slice Thickness Determination**: The tool reports being "Unable to determine slice thickness: please check voxel size." This raises concerns about the accuracy of the spatial information in the converted NIfTI files.
2. **Image Decompression Warning**: A warning indicating "Image Decompression is new: please validate conversions" appears, suggesting potential issues with the integrity of the decompressed images.

Despite these warnings, the tool successfully converts the DICOM files, producing NIfTI files with varying dimensions, however, the files are all of different sizes and seem to have gone down in resolution and squishified into itself when visualizing in Matlab (screenshot provided).

**Output log**

![2](https://github.com/rordenlab/dcm2niix/assets/68840767/10c552ef-05fc-462d-b9c1-79b56e6daffe)

**Matlab Visualization**

![2](https://github.com/rordenlab/dcm2niix/assets/68840767/637e1133-dbfe-489e-a5ee-ecbe68c47019)

I tried visualizing the other NII files and it seems to show other parts of the CT scan:
<img width="419" alt="image" src="https://github.com/rordenlab/dcm2niix/assets/68840767/7e080c9e-4060-4a9d-8942-d3d624f28514">

**CT Files**

![2](https://github.com/rordenlab/dcm2niix/assets/68840767/aa9043bc-e833-45f6-8121-ccc132bc53af)
<img width="399" alt="image" src="https://github.com/rordenlab/dcm2niix/assets/68840767/212efa18-ea34-4829-9a77-3d1c88f7a1ef">

**Comment by neurolabusc** [comment]
1. You will get the `Unable to determine slice thickness: please check voxel size` error if **both** [Spacing Between Slices (0018,008)](https://dicom.innolitics.com/ciods/nm-image/nm-reconstruction/00180088) and [Slice Thickness  (0018,0050)](https://dicom.innolitics.com/ciods/nm-image/nm-reconstruction/00180050) are not populated. These are required DICOM tags, so you should check the provenance of your images to see if they got removed by an over-zealous anonymization stage. Computing the slice thickness is [tricky](https://dclunie.blogspot.com/2013/10/how-thick-am-i-sad-story-of-lonely-slice.html). Since NIfTI only stores the distance between voxel centers (slice thickness + slice gap), the NIfTI file may be able to resolve the distance by comparing the [Image Position Patient (0020,0032)](https://dicom.innolitics.com/ciods/rt-dose/image-plane/00200032) between two neighboring slices. I would use dcmdump and fslhd to check your input DICOMs and output NIfTI images carefully. 
2. Your visualizations look very squashed in the slice direction, suggesting your images are anisotropic. Do they look squashed with MRIcroGL (suggesting an issue with your DICOMs) or only in Matlab (suggesting the Matlab code assumes isotropic data).
3. By visual inspection, it looks like your images decompressed nicely.

**Comment by neurolabusc** [comment]
1. With MRIcroGL click the 'Options' button on the 'Layer' Panel and select 'Show Header', this will show both the dimensions, spacing and units (e.g. mm) of your image. 
2. MRIcroGL has a Import/Tools/Resize menu item that could allow you to reslice your data to make it isotropic. However, you will necessarily get aliasing artifacts and the file size (and therefore rendering resources) will explode. With MRIcroGL, if you choose Display/Render you will see that it transforms isotropic images on the fly.
3. Anisotropic data viewed with Slicer3D and MRIcroGL will appear crisper or fuzzier depending on the interpolation method used. Try toggling the 'Smooth' button in the '2D Slice Selection' panel of MRIcroGL when the 'Display' menu is set to multiplanar. Note that nearest neighbor interpolation looks jagged, while trilinear interpolation looks fuzzy.
4. Classic DICOM saves each 2D slice as a separate file, a single imaging session is typically composed of several `series`: the first series is used to position the subsequent scans, with subsequent scans using different positioning, parameters and contrast agents to optimize different types of signal. For most series, dcm2niix and MRIcroGL will save each DICOM series as a separate 3D or 4D file. Therefore, a DICOM session with multiple series will yield multiple NIfTI files.
5. Your DICOM images seem to be missing several of the crucial fields required by the DICOM standard. The opportunity for unintended consequences seems high. I would recommend you work with a valid set of DICOM images. If you can not get these locally, there are large public datasets including the [TCIA](https://www.cancerimagingarchive.net/access-data/).
