### ISSUE TITLE
How sform is calculate?

### ISSUE THREAD

**Issue by BrunoFFPP** [rordenlab/dcm2niix#828]
Hi Everyone,
I'm tying to understand how to calculate sform from dicom information or from quaternions.
My dicom data has these information:
(0020,0032): -94,87 | -56,31 | +117,65
(0020,0037): 0,853 | 0,505 | -0,126 | 0,152 | -0,473 | -0,867
The acquisition was coronal (A-->P): 256 slices (matrix 512X512). Voxel spacing (0,375x0.375) and slice thickness (0.38).

I converted this dicom dataset using dcm2niix and I obtained the following header:
<nifti_image
  image_offset = '352'
  ndim = '3'
  nx = '512'
  ny = '256'
  nz = '512'
  nt = '1'
  dx = '0.375'
  dy = '0.38'
  dz = '0.375'
  dt = '1.5'
  datatype = '4'
  nvox = '67108864'
  nbyper = '2'
  scl_slope = '1'
  scl_inter = '0'
  intent_code = '0'
  intent_p1 = '0'
  intent_p2 = '0'
  intent_p3 = '0'
  intent_name = ''
  toffset = '0'
  xyz_units = '2'
  time_units = '8'
  freq_dim = '2'
  phase_dim = '1'
  slice_dim = '3'
  descrip = 'TE=2.4;Time=133342.980;phase=1'
  aux_file = ''
  qform_code = '1'
  qfac = '1'
  quatern_b = '0.257356'
  quatern_c = '0.00680481'
  quatern_d = '0.270387'
  qoffset_x = '-66.1911'
  qoffset_y = '4.53565'
  qoffset_z = '-103.359'
  sform_code = '1'
  sto_xyz_matrix = '0.320133 -0.189304 0.056924 -66.1911 0.18944 0.274099 -0.177681 4.53565 0.0474548 0.182846 0.325291 -103.359 0 0 0 1'
  slice_code = '0'
  slice_start = '0'
  scl_end = '0'
  scl_duration = '0'
/>

I was reading this page: https://nifti.nimh.nih.gov/nifti-1/documentation/nifti1fields/nifti1fields_pages/quatern.html  to try to calculate "sto_xyz_matrix". My first question is: Are the "rotation matrix" and "sto_xyz_matrix" the same issue?

I tried to calculate the rotation matrix R in this way:
quatern_b = b = 0.257 
quatern_c = c = 0.007 
quatern_d = d = 0.270 
quatern_a = a =  sqrt(1 - (b*b+ c*c + d*d) ) = 0.925

R =  (a*a + b*b - c*c - d*d)     (2*b*c - 2*a*d)     (2*b*d + 2*a*c)
        (2*b*c + 2*a*d)     (a*a + c*c - b*b - d*d)     (2*c*d - 2*a*b)  
        (2*b*d - 2*a*c)     (2*c*d + 2*a*b)     (a*a + d*d - c*c - b*b)

R = 0.848   -0.496     0.153
      0.503     0.715     -0.477
      0.127     0.484      0.861

My second question is: how to calculate "sto_xyz_matrix" from "R matrix"?

**Comment by neurolabusc** [comment]
This question is out of scope for dcm2niix. dcm2niix uses [nifti_clib](https://github.com/NIFTI-Imaging/nifti_clib) for these transforms, so that would be the appropriate place for questions. In particular, see [nifti_quatern_to_mat44](https://github.com/NIFTI-Imaging/nifti_clib/blob/f24bec503f1a5d501c0413c1bb8aa3d6e04aebda/niftilib/nifti1_io.c#L1479)

 In brief:
 - The [NIfTI header](https://brainder.org/2012/09/23/the-nifti-file-format/) includes two independent spatial transforms: the Matrix-based SForm (12 degrees of freedom: shear, zoom, rotation, translation each in three dimensions) and the Quaternion-based QForm (9 DoG: [zoom, rotation, translation in 3D](https://www.researchgate.net/figure/Normalization-step-12-parameters-affine-transformations_fig4_257806679)). In general, both initially map the image to native scanner space, and a co-registration can update one or both to warp the image to standard space. You can use the sform_code/q form_code to determine the spatial reference (e.g. native vs standard) of each, but most tools give precedence to the SForm.
 - Your R-matrix is only 3x3, but you need a [4x4 matrix to include the translations](https://en.wikipedia.org/wiki/Transformation_matrix). You must include the [qoffset_x/y/z](https://nifti.nimh.nih.gov/pub/dist/src/niftilib/nifti1.h).
 - You can easily [convert a matrix to a quaternion](https://github.com/rordenlab/dcm2niix/blob/aea081a97ba8c119e2ea1bdf49924a0088ec43fa/console/nifti1_io_core.cpp#L406). However, this transform will be lossy if your transform includes a shear (CT gantry tilt).
 - Note you can losslessly convert a quaternion to a 4x4 matrix.
 - Note that for 3D acquisitions (but not 2D EPI sequences), dcm2niix will losslessly reorient sagittal and coronal slices to be axial slices, with the spatial transforms rotated appropriately.

**Comment by BrunoFFPP** [comment]
Sorry for use the wrong site to post my doubt but thanks for your tips and explanations, they help me a lot.
