### ISSUE TITLE
Suppress ROI1, ROI2, etc. in conversion

### ISSUE THREAD

**Issue by halfSpinDoctor** [rordenlab/dcm2niix#832]
This is a feature request, not a bug _per se_, but I would like to put it here for your consideration. I apologize in advance as I have taken no steps to work on implementing this in code myself.

I would like a flag to disable the generation of ROI1, ROI2, etc. images for datasets that may contain embedded annotations. This breaks certain workflows for us, and in general generates a lot of extra images that we do not need. It is specifically a problem when converting images pulled down from PACs. Thanks in advance,

Best,
Sam

**Comment by neurolabusc** [comment]
For context, a sample DICOM image with an overlay region of interest is [here](https://www.aliza-dicom-viewer.com/download/datasets). The issue is that `one man's trash is another man's treasure.` I do think that dcm2niix already has an overwhelming number of options, and we want it to behave consistently.

For power users, I did add a compiler directive `-DmyNoRois` that if defined will ignore overlays. For testing, I added this as an option to the makefile as `noroi` for you to try out.

```
git clone --branch development https://github.com/rordenlab/dcm2niix.gi...
cd dcm2niix/src
make noroi
```
