### ISSUE TITLE
trailing comma in bids .json

### ISSUE THREAD

**Issue by fliem** [rordenlab/dcm2niix#84]
Somewhere between the 1-Nov-2016 release and the current master the following issue with BIDS .json export sneaked in: The last entry is followed by a ",":
```
{
	[...]
	"RepetitionTime": 0.00818,
}
```

At least python's .json import does not like that, but can deal with the format exported by  the 1-Nov-2016 release:
```
{
	[...]
	"RepetitionTime": 0.00818
}
```

Could you please take a look at that? Thanks.

**Comment by neurolabusc** [comment]
@chrisfilo, @yarikoptic  and @dangom do you want to comment on this? I notice that several of the pull requests that have been recently added ([e.g.](https://github.com/rordenlab/dcm2niix/pull/63/files)) have added trailing commas. If I am correct, the trailing comma is appended to all except the final object in a block {}, [e.g.](http://json.org/example.html). At the moment, the code always adds a trailing comma except for with the final element (PhaseEncodingDirection). The trick is that ALL of these objects are optional, so for example when PhaseEncoding is unknown we do not include it, and therefore one of the other items becomes the final item in the block. In this situation, the current code incorrectly appends a comma to the final item (e.g. TR).

@chrisfilo - maybe you want to suggest the nicest way to adapt the code so that all the elements EXCEPT the last one are terminated with a comma.

At the moment, every element is optional. One easy solution might be to create a new element that is always included and ALWAYS the final object, for example add "dcm2niixVersion" as the final object, so we can be confident that all prior objects can be terminated with a comma:

{
	[...]
	"RepetitionTime": 0.00818,
	"dcm2niixVersion",v1.0.20170101
}

**Comment by neurolabusc** [comment]
I have updated the github code to illustrate my solution, @fliem perhaps you could test this - I assume this will work, because while the RepetitionTime has a trailing comma, it is not the final item. @chrisfilo is the maintainer for the BIDS support, so the current solution is provisional and for demonstration until it receives his blessing.

**Comment by fliem** [comment]
@neurolabusc: that works, thanks.

**Comment by dangom** [comment]
Having an element that is always included as the last is probably the easiest and simplest solution. And probably the best too.

Another option would be to bring in a lightweight header-only lib to deal with json serialization and pretty printing, abstracting away most of our formatting work.

An example using https://github.com/nlohmann/json :


```cpp
#include "json.h"
using json = nlohmann::json;

// Function signature remains the same.
void nii_SaveBIDS(char pathoutname[], struct TDICOMdata d, struct TDCMopts opts, struct TDTI4D *dti4D, struct nifti_1_header *h){
  if (!opts.isCreateBIDS) return;

  // Define an empty json object to hold BIDS data.
  json j;

  // No more worries about commas or proper formatting.
  j["Manufacturer"] = "Manufacturer"; // works as expected.
  j["ManufacturersModelName"] = d.manufacturersModelName;
  j["ProcedureStepDescription"] = d.procedureStepDescription;
  j["ProtocolName"] = d.protocolName;
  j["MagneticFieldStrength"] = d.fieldStrength; // output is a number and not str, as expected.
 // (...)

  // Dump JSON sidecar to file.
  char txtname[2048] = {""};
  strcpy (txtname,pathoutname);
  strcat (txtname,".json");
  FILE *fp = fopen(txtname, "w");
  std::string s = j.dump(4); // Pretty printing
  fprintf(fp, "%s", s.c_str());
  fclose(fp);

}
```

Result (automatically sorted in alphabetic order):

```json
{
    "MagneticFieldStrength": 3,
    "Manufacturer": "Manufacturer",
    "ManufacturersModelName": "Prisma",
    "ProcedureStepDescription": "dangom_test",
    "ProtocolName": "test_data"
}
```

Now, whether this is necessary or even relevant is up to debate, but it would make the BIDS functionality easier to read and maintain.

**Comment by neurolabusc** [comment]
@dangom - I would prefer to leave out the C++ dependencies. Not that I have anything against C++, but I think it makes distribution a bit cleaner and makes it a bit easier for people to integrate it in simple projects.
