### ISSUE TITLE
Addition of MAGNITUDE to ImageType of Siemens data

### ISSUE THREAD

**Issue by mharms** [rordenlab/dcm2niix#851]
I noticed that the current development branch has added MAGNITUDE to the ImageType tag of Siemens data:

`v1.0.20240812`
"ImageType": ["ORIGINAL", "PRIMARY", "M", "NONE", "MAGNITUDE"],

`v1.0.20240202`
"ImageType": ["ORIGINAL", "PRIMARY", "M", "NONE"],

 Is that intentional?  I noticed this recent commit 08aeeef9, but that is framed as only being relevant to GE.

On the one hand, this is a minor change, but on the other hand I think that ImageType should reflect the actual DICOM entry, and not change the behavior for Siemens data unless such change is actually necessary.

@bpinsard: Why was this change necessary for GE data, and why couldn't `heudiconv` have been adapted instead of hacking `dcm2niix` to accommodate `heudiconv`?

**Comment by neurolabusc** [comment]
@mharms I have updated the detection, so the term "MAGNITUDE" will not be appended if either "MAGNITUDE" or "M" already exist in the list of ImageType parameters. It does seem worth explicitly denoting that an image is a magnitude image if the DICOM explicitly declares this but it is not listed in the ImageType.

**Comment by bpinsard** [comment]
You are entirely right, that shouldn't modify the ImageType when the info is not missing in the first place.
Surprisingly, if we check the 2 following lines, that is what happened for the "PHASE" in previous versions.

For GE data, that info is not in the `ImageType`, which is why it needs to be inserted (to avoid ambiguity, notably for dcm2bids that do not parse the dicoms, but use only sidecar contents). 


I would be all for a new generated standardized tag in the sidecar to store that info in a more standardized way and separated from the rest of the ImageType labels.

**Comment by neurolabusc** [comment]
@bpinsard the latest commit only adds terms like PHASE, REAL, etc if the term (e.g. "PHASE") or its alias (e.g. "P") does not exist.
