### ISSUE TITLE
Archive old  dcm2niix repository?

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [rordenlab/dcm2niix#865]
**Describe the bug**

How about archiving https://github.com/neurolabusc/dcm2niix, after adding a redirection to this repository? Unless you no longer have the identifiers associated with the [neurolabusc](https://github.com/neurolabusc/dcm2niix) organisation.

That would prevent confusion around the reference repositories.

**Comment by DimitriPapadopoulos** [comment]
I don't think https://github.com/rordenlab/dcm2niix/pull/864#issuecomment-2367784876 addresses the issue at hand.

**Comment by DimitriPapadopoulos** [comment]
I thought repository [neurolabusc/dcm2niix](https://github.com/neurolabusc/dcm2niix) is obsolete and repository [rordenlab/dcm2niix](https://github.com/rordenlab/dcm2niix) is the current one, with the policy by the BIDS maintainers being implemented as different branches [development](https://github.com/rordenlab/dcm2niix/tree/development) / [master](https://github.com/rordenlab/dcm2niix/tree/master) in the latter.

Are you saying that the policy by the BIDS maintainers is implemented as different repositories [neurolabusc/dcm2niix](https://github.com/neurolabusc/dcm2niix) / [rordenlab/dcm2niix](https://github.com/rordenlab/dcm2niix)?

**Comment by neurolabusc** [comment]
I do not understand the question. The repository [dcm2niix](https://github.com/rordenlab/dcm2niix) has 228 forks. While at your request I did archive the my own [personal fork](https://github.com/neurolabusc/dcm2niix) and include a message in the readme redirecting to the root repository, I do not understand the need for disambiguation. Each fork lists its root fork, I think there are many legitimate active forks to handle unique situations of specific users or explore experimental features. By design, we use a permissive license that encourages others to create their own custom forks. I do not control these forks nor does it seem appropriate to archive these forks that may be appropriate for specific use cases.

**Comment by DimitriPapadopoulos** [comment]
I know that Git is not a centralised VCS. However, a repository usually plays a more central role than others, and that special repository needs to be clearly identified.

At some point, I had cloned [neurolabusc/dcm2niix](https://github.com/neurolabusc/dcm2niix) as my `upstream` Git repository. Either it was indeed the primary repository at the time, where most of the development happens, or it was my mistake - at the time I think repositories were not as clearly identified as forks of another repository as today. Years later, I was tempted to keep using [neurolabusc/dcm2niix](https://github.com/neurolabusc/dcm2niix) because it was not identified as obsolete. I ended up finding [rordenlab/dcm2niix](https://github.com/rordenlab/dcm2niix), using the forking information exactly as you write. But it took me some time.

**Comment by neurolabusc** [comment]
OK, but I archived the neurolabusc repository and clearly redirected to the main repository before I closed this issue, and now you have re-opened this. I think this issue is closed as resolved. Unless you can provide a rationale I think this issue should be closed as resolved.

**Comment by DimitriPapadopoulos** [comment]
I did not repoen after you archived the neurolabusc repository and clearly redirected to the main repository, but before that.

But most importantly, thank you very much for this great piece of software!
