### ISSUE TITLE
Migrate from ConversionSoftware{,Version} to use GeneratedBy

### ISSUE THREAD

**Issue by yarikoptic** [rordenlab/dcm2niix#884]
Inspired by 
- https://github.com/bids-standard/bids-2-devel/issues/80#issuecomment-2437597659

and reflecting on
- https://github.com/bids-standard/bids-specification/pull/440

for GeneratedBy to be universally adopted at the Dataset level.  I just filed 

- https://github.com/bids-standard/bids-specification/issues/1970

at BIDS level and if I find time will propose a PR for that (unless someone beats me to it).  But I think it would already be better for dcm2niix to adopt it since it would be more generic than `ConversionSoftware*` for a number of reasons: 

- `Conversion` term is not clearly defined
- Impossible to chain (e.g. it was dcm2niix + custom script to rename or add extra metadata into header, or convert from nii into zarr-nii, etc)

**Comment by neurolabusc** [comment]
@yarikoptic I am closing this issue here, as we can not get consensus in time for the upcoming stable release. dcm2niix aspires to be a BIDS compliant converter, so if the BIDS specification defines these, dcm2niix will change. 

In general, rather than defining new keys in BIDS, my personal opinion is that it would be better to adopt the informal ones in common use. Both dicm2nii and dcm2niix use ConversionSoftware, and include private keys without a custom prefix. Both were adopted with the explicit encouragement of @chrisgorgo and are found in thousands of public datasets. So I think users are familiar with these terms.

So while I have my own personal opinions on this topic, dcm2niix will abide by the decision of the BIDS community once changes are adopted.
