### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by hajerkr** [rordenlab/dcm2niix#891]
This has been an issue before with other users in closed issues, and I checked the solutions there but that didn't sort out my problem.

The output I get on a .dicom file that is perfectly viewable on Radiant DICOM:

```dcm2niix 12\ -\ PSIF-NOT\ FOR\ DIAGNOSTIC\ USE.dicom
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) GCC13.2.0 x86-64 (64-bit Linux)
Found 1 DICOM file(s)
Warning: Compressed image stored as 40 fragments: if conversion fails decompress with gdcmconv, Osirix, dcmdjpeg or dcmjp2k /home/hajerkr/unity/analysis/12 - PSIF-NOT FOR DIAGNOSTIC USE.dicom
Warning: Unable to determine manufacturer (0008,0070), so conversion is not tuned for vendor.
Segmentation fault (core dumped)
```

I tried to use the dev branch by doing the following: 
```
git clone --branch development https://github.com/rordenlab/dcm2niix.git
cd dcm2niix/console/
make
 ./dcm2niix ./mydicomfile.dicom
```

The output I get:
```
Chris Rorden's dcm2niiX version v1.0.20241111  GCC13.2.0 x86-64 (64-bit Linux)
Found 1 DICOM file(s)
Warning: Unsupported transfer syntax '1.2.840.10008.1.2.4.90' (see www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage)
No valid DICOM images were found
```

Manufacturer is **Hyperfine, Inc**. This only happens with a handful of scans. Could this be due to header corruption? Looking forward to getting your thoughts. Thanks

**Comment by neurolabusc** [comment]
If you want to compile dcm2niix with support for [JPEG2000 transfer syntax](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#DICOM_Transfer_Syntaxes_and_Compressed_Images) you will need to compile it with the OpenJPEG library:

```bash
git clone --branch development  https://github.com/rordenlab/dcm2niix.git
cd dcm2niix
mkdir build && cd build
cmake -DZLIB_IMPLEMENTATION=Cloudflare -DUSE_JPEGLS=ON -DUSE_OPENJPEG=ON ..
make
```
Alternatively, you could decompress your DICOMs and then convert the uncompressed DICOMs with dcm2niix. You could decompress them like this:
```
gdcmconv -w -M compressed.dcm uncompressed.dcm
```
another alternative would be to use [dcmdjpeg](https://support.dcmtk.org/docs/dcmdjpeg.html)

**Comment by hajerkr** [comment]
Alright thanks, so I wasn't able to dcm2niix with the OpenJPEG compiling only, it still gave an error. I had to decompress before that as well, and it worked. And this only works using the version v1.0.20241111 ? I tried using v1.0.20220720 with the decompressed file but it didn't work.

**Comment by neurolabusc** [comment]
Rather than using a dcm2niix release from 2022, you could see if upgrading to the latest stable release fixes your problem. You can get the [compiled stable release here](https://github.com/rordenlab/dcm2niix/releases), alternatively, the [home page](https://github.com/rordenlab/dcm2niix) suggests you can download it with curl:

```bash
curl -fLO https://github.com/rordenlab/dcm2niix/releases/latest/download/dcm2niix_lnx.zip
```
If you want to try the development release compiled with libraries to handle rare transfer syntaxes you can either compile it yourself, of get a compiled version from AppVeyor. Specifically, the AppVeyor badge on the home page shows automated compilations for [Windows, Mac and Linux](https://ci.appveyor.com/project/neurolabusc/dcm2niix) - if you desire Linux, click on that icon and choose the [artifacts page](https://ci.appveyor.com/project/neurolabusc/dcm2niix/build/job/gkfcxy1khp0gx9or/artifacts) - you can download that zip file.

**Comment by hajerkr** [comment]
Thanks so much for your help!
