### ISSUE TITLE
XA61A dicom-enhanced 3-planes localizer stacked in a single volume.

### ISSUE THREAD

**Issue by bpinsard** [rordenlab/dcm2niix#894]
**Describe the bug**

3-planes/3-orientation localizer from XA61A are stacked in a single volume.

see https://github.com/nipy/nibabel/issues/1392

**To reproduce**

dcm2niix -o ./ -d 0 -v 2 ../dicoms/mtl/MRe.1.3.12.2.1107.5.2.63.213014.2024111513211206927679828

**Expected behavior**

multi-frame enhanced dicoms with non-matching orientation should result in multiple niftis with appropriate affines.

**Output log**

![image](https://github.com/user-attachments/assets/c18095d0-945d-4213-a0c8-052196c03413)
(cropping face for "defacing")

**Version**

Chris Rorden's dcm2niiX version v1.0.20240731  (JP2:OpenJPEG) (JP-LS:CharLS) GCC11.4.0 x86-64 (64-bit Linux)

**Comment by bpinsard** [comment]
I will try to get phantom data from that site to be shareable.

**Comment by neurolabusc** [comment]
@bpinsard I can not provide any insights without seeing data. However, here are two thoughts:
 1. I would test the latest commit to the dcm2niix development brnach (v1.0.20241127) which adds several kludges for XA61 data.
 2. I always run dcm2niix with the ignore derived and localizer flag (`-i y`). Localizers are typically only used for planning and derived data are typically of lower quality than what can be achieved with offline tools. I would have thought that would skip this series entirely.

**Comment by neurolabusc** [comment]
As noted [here](https://github.com/nipy/nibabel/issues/1392#issuecomment-2508066687) is a limitation of the DICOM data, not dcm2niix. dcm2niix does warn that slice orientation varies, and dcm2niix will ignore these localizer images if the user chooses the `-i y` option.

**Comment by neurolabusc** [comment]
Previously, dcm2niix generated a warning that the slice orientation varied but would still generate a NIfTI image. I have updated this to an error. While a legal  DICOM series can have multiple slice orientations, NIfTI requires that all slices in a file have the same orientation. Therefore, dcm2niix will fail to convert any enhanced DICOMs with variable slice orientation. In practice this should not influence conversions, as these series are localizers that should be discarded. 

```bash
Error: DICOM incompatible with NIfTI slice orientation varies (issue 894, localizer?) [0 1 0 0 0 -1] != [1 0 0 0 0 -1]
```

**Comment by bpinsard** [comment]
Thanks for the update!
Just to better understand: would splitting a single dicom with multiple stacks (provided that they are properly formatted with separate StackID) into separate niftis require a major refactor of dcm2niix? 
If one develops a sequence with multiple "concurrent" FoV that gets packed into a single dicom, for now dcm2niix won't be able to convert these. The only example I have in mind is this https://onlinelibrary.wiley.com/doi/full/10.1002/mrm.25143 that I have seen used for simultaneous brain and spine BOLD. Pretty niche of course and I don't think this is ported to XA.

**Comment by neurolabusc** [comment]
In general, dcm2niix tries to convert each DICOM series into an individual NIfTI file (though there are exceptions: multi-echo files are parsed into separate NIfTI files). However, NIfTI requires that all slices in a file are co-planar, which is not the case for localizer images. Therefore, a localizer with sagittal, coronal and axial slices in a single series would need to be saved as three separate NIfTI images. Localizer scans are by design quick and dirty - they often show T1 effects where the orthogonal slices were acquired and have fast but poor shimming. I actually think this is really useful for planning scans, as the localizers alert you to problems for subsequent scans. However, due to their artifacts, I always discard localizers (using `-i y`).  As you note, I think the use case is very niche. If a team wants to support these images, they can fork dcm2niix and contribute a pull request if they want to share their modifications.

**Comment by captainnova** [comment]
We just came across an enhanced 3 plane localizer from Siemens XA60 which caused problems because our automated series type classifier misidentified it, due to the lack of BIDS. I would prefer the old behavior of 3 .niis and 3 .jsons being written, even though we would typically discard both, after reading the .jsons. 

Unfortunately the absence of something that will be ignored later often generates a manual hunt for what went "wrong". I'd rather have the option to see the localizers.

**Comment by neurolabusc** [comment]
@captainnova the latest version of the development branch (v1.0.20251015) has a new option `-i o` that overrides the localizer behavior - it will stack and save slices from a localizer as a single NIFTI file even if they are not co-planar. A warning is emitted. I would consider this an advanced user edge case.

**Comment by captainnova** [comment]
It's perfect, thanks!
